"""classrooms: classes, memberships, assignments

Revision ID: 3dbd651eaadf
Revises: 228e107c9731
Create Date: 2026-07-10 00:03:34.135553

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3dbd651eaadf'
down_revision: Union[str, None] = '228e107c9731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('join_code', sa.String(length=8), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_index('ix_classrooms_teacher', 'classrooms', ['teacher_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('target_reviews', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_classroom', 'assignments', ['classroom_id'], unique=False)
    op.create_table('class_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'student_id', name='uq_class_membership')
    )
    op.create_index('ix_class_memberships_student', 'class_memberships', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_class_memberships_student', table_name='class_memberships')
    op.drop_table('class_memberships')
    op.drop_index('ix_assignments_classroom', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_classrooms_teacher', table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
