"""social: friendships

Revision ID: 85be33b86474
Revises: 3dbd651eaadf
Create Date: 2026-07-10 10:49:58.905350

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85be33b86474'
down_revision: Union[str, None] = '3dbd651eaadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('addressee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship')
    )
    op.create_index('ix_friendships_addressee', 'friendships', ['addressee_id'], unique=False)
    op.create_index('ix_friendships_requester', 'friendships', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_friendships_requester', table_name='friendships')
    op.drop_index('ix_friendships_addressee', table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
