"""gamification: user_stats, daily_activity, user_achievements, league_entries

Revision ID: a4e3d6173711
Revises: a438ed7ebc72
Create Date: 2026-07-09 11:41:59.221889

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4e3d6173711'
down_revision: Union[str, None] = 'a438ed7ebc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('goal_reached', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_daily_activity_user_day')
    )
    op.create_index('ix_daily_activity_user_day', 'daily_activity', ['user_id', 'day'], unique=False)
    op.create_table('league_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('iso_week', sa.String(length=8), nullable=False),
    sa.Column('tier_index', sa.Integer(), nullable=False),
    sa.Column('league_group', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'iso_week', name='uq_league_entry_user_week')
    )
    op.create_index('ix_league_group', 'league_entries', ['iso_week', 'tier_index', 'league_group', 'xp'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_user_achievement')
    )
    op.create_index('ix_user_achievements_user', 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_on', sa.Date(), nullable=True),
    sa.Column('streak_freezes', sa.Integer(), nullable=False),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    op.drop_index('ix_user_achievements_user', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_league_group', table_name='league_entries')
    op.drop_table('league_entries')
    op.drop_index('ix_daily_activity_user_day', table_name='daily_activity')
    op.drop_table('daily_activity')
    # ### end Alembic commands ###
