"""coach: sessions, messages, grammar_errors, ielts_reports, character_progress

Revision ID: db3c51824abe
Revises: 408213cc8563
Create Date: 2026-07-15 21:25:33.670541

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db3c51824abe'
down_revision: Union[str, None] = '408213cc8563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_character_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('character', sa.String(length=20), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('friendship_xp', sa.Integer(), nullable=False),
    sa.Column('last_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character', name='uq_coach_progress_user_char')
    )
    op.create_table('coach_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('character', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('ielts_part', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coach_sessions_user_started', 'coach_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('coach_grammar_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('original', sa.String(length=300), nullable=False),
    sa.Column('correction', sa.String(length=300), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coach_errors_user_created', 'coach_grammar_errors', ['user_id', 'created_at'], unique=False)
    op.create_table('coach_ielts_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('band_overall', sa.Float(), nullable=False),
    sa.Column('fluency', sa.Float(), nullable=False),
    sa.Column('lexical', sa.Float(), nullable=False),
    sa.Column('grammar', sa.Float(), nullable=False),
    sa.Column('pronunciation', sa.Float(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('improvements', sa.Text(), nullable=False),
    sa.Column('homework', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_coach_ielts_reports_user_id'), 'coach_ielts_reports', ['user_id'], unique=False)
    op.create_table('coach_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('corrections_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coach_messages_session', 'coach_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coach_messages_session', table_name='coach_messages')
    op.drop_table('coach_messages')
    op.drop_index(op.f('ix_coach_ielts_reports_user_id'), table_name='coach_ielts_reports')
    op.drop_table('coach_ielts_reports')
    op.drop_index('ix_coach_errors_user_created', table_name='coach_grammar_errors')
    op.drop_table('coach_grammar_errors')
    op.drop_index('ix_coach_sessions_user_started', table_name='coach_sessions')
    op.drop_table('coach_sessions')
    op.drop_table('coach_character_progress')
    # ### end Alembic commands ###
