/** Part 3 model answers, one per question.
 *
 *  Like Part 1, these were previously eight generic "points" per topic written
 *  against an older template (why it matters / past vs now / advantages and
 *  disadvantages / what governments should do / age differences / the future /
 *  education / responsibility). The questions were later rewritten per topic
 *  but the answers kept the old order, so "Does tourism help a culture survive?"
 *  was answered with a paragraph about how cheap flights changed travel. Two
 *  further sentences were then appended from shared pools, which is why every
 *  answer closed with lines such as "Any serious judgement should therefore
 *  consider both evidence and context".
 *
 *  Each string answers the question at the same index in
 *  PART3_CONTENT[slug].questions. Part 3 rewards a position, a reason, and a
 *  qualification or counter-example, so that is the shape used throughout.
 */
export type Part3Samples = readonly [string, string, string, string, string, string, string, string];

const SET_A: Record<string, Part3Samples> = {
  "travel-and-culture": [
    "Partly it is curiosity, but I think the stronger motive is contrast. Seeing a place where ordinary assumptions about food, family or time are different forces people to notice their own habits, which is difficult to do at home.",
    "It does both, and the balance depends on who controls the money. Tourist income can fund the restoration of buildings and give young people a reason to learn a craft, but when a ceremony is repeated daily for visitors it gradually becomes a performance rather than a living practice.",
    "It has made the world feel accessible without necessarily making it better understood. People now visit five countries in the time their parents would have spent in one, and a weekend in a city centre produces impressions rather than understanding.",
    "I would say they do, although the responsibility is often exaggerated. An individual tourist should respect local rules and spend money locally, but the serious decisions about how many cruise ships dock or how many flats become short-term rentals are made by governments and companies, not by visitors.",
    "You can understand a great deal, but not everything. Observation tells you how people behave, and food, architecture and daily routines are all readable; what you miss is humour, indirectness and disagreement, which is precisely where a culture's values show most clearly.",
    "In some cases they have little choice. Places such as Venice or Machu Picchu are physically being damaged, so timed entry is simply maintenance. The risk is that limits become a matter of price, which turns access to world heritage into something only wealthy travellers enjoy.",
    "Younger travellers tend to want to live somewhere briefly rather than see it. They stay in ordinary neighbourhoods, work remotely, and value the experience of a normal week over a list of monuments, which is partly a genuine change in taste and partly what social media rewards.",
    "It will replace some journeys, and that would be a good thing for fragile sites. But travel is physically exhausting and unpredictable, and that is where most of its value lies; a perfect image of a place will never involve getting lost, being helped by a stranger, or eating something you cannot identify.",
  ],
  "education-systems": [
    "Its main purpose should be to give people the capacity to keep learning after school ends. Specific facts date quickly, whereas the ability to read carefully, evaluate a claim and structure an argument remains useful whatever career someone eventually enters.",
    "They are fair in a narrow sense and unfair in a broader one. Everyone answers the same paper, which is genuinely more objective than a teacher's impression, but a single timed test measures performance under pressure rather than understanding, and it consistently favours students who can afford preparation.",
    "Yes, though not as a lower-status alternative. Cooking, basic finance and simple repairs are things almost every adult needs, and separating practical from academic education tends to divide students by background long before they have chosen anything.",
    "Usually because the connection between what they study and anything they care about becomes invisible. A twelve-year-old asked to memorise material with no evident purpose, under constant assessment, quite reasonably concludes that the point is the mark rather than the knowledge.",
    "Enough to show that school matters, but not so much that the child never works independently. Involvement helps most in the early years; by adolescence, parents who manage every deadline tend to produce students who cannot organise themselves at university.",
    "It depends heavily on the field and the cost. For medicine, law or engineering the answer is clearly yes, since the qualification is a legal requirement. For many other subjects, three years of fees now buys a signal to employers rather than a skill, and the value of that signal is falling as more people hold it.",
    "They offer comparable information but not comparable structure. An online course can be excellent and is far more accessible, yet completion rates are low precisely because there is no cohort, no timetable and nobody who notices when you disappear.",
    "I would expect less time spent delivering identical content and more spent on discussion and feedback. Software can already explain a topic and set practice at the right level; what it cannot do is notice that a student has understood the method but does not believe they can do it.",
  ],
  "technology-and-society": [
    "It has removed distance as a limitation, which is a much bigger change than it first appears. A team spread across four countries is now ordinary, and that has altered hiring, salaries and even which cities people choose to live in.",
    "Both, but the second more often than we admit. The tools genuinely speed up individual tasks, and then the volume of communication expands to fill the time saved, so people finish the day having answered a great deal and produced very little.",
    "Yes, and the limits should be about purpose rather than quantity. Asking users to accept a fifty-page policy is not meaningful consent; a clearer rule would be that data collected for one service cannot simply be reused for another.",
    "On balance it has done more harm than good at home. Being reachable is useful in an emergency, but work now follows people to the dinner table, and the more common problem is four people sharing a room while attending to four different screens.",
    "Often because they have judged the cost accurately. Older people in particular are asked to relearn a system that already worked for them, and each new interface carries a real risk of losing money or access, so caution is rational rather than stubborn.",
    "Historically automation has created more work than it destroyed, but the transition has never been painless. The jobs that disappear and the jobs that appear rarely belong to the same people or the same regions, and a decade of disruption matters enormously to whoever lives through it.",
    "By teaching them the things that are hard to automate: framing a problem, judging whether an answer is plausible, and working with people who disagree. Teaching a specific software package is far less useful, because the package will be obsolete before they graduate.",
    "At minimum, responsibility for the predictable effects of their own design choices. A platform that optimises for time spent is not neutral about what it promotes, and pretending otherwise while claiming credit for connecting the world is not a consistent position.",
  ],
  "cities-and-transport": [
    "Mainly for work and education, which have concentrated in cities for decades. Wages are higher, universities and hospitals are better, and once a family's children have moved, the pull becomes social rather than purely economic.",
    "Short distances, more than anything. A pleasant city is one where daily needs are within walking distance, there is somewhere green nearby, and the streets are designed for people rather than for the traffic passing through.",
    "Discouraged rather than banned, and only where the alternative already exists. Restricting cars in a centre with a good metro is sensible; doing the same where public transport is unreliable simply penalises people who have no other way to get to work.",
    "Congestion is mostly a question of capacity and pricing rather than road building, since new roads fill up within a few years. What actually works is a combination of frequent public transport, charges for driving into the densest areas, and allowing people to live nearer their jobs.",
    "Very differently. For wealthier residents it is a choice, so they judge it on comfort and speed. For everyone else it is the only option, so reliability and cost matter far more, and a service designed to attract drivers is not necessarily the service most passengers need.",
    "They matter as much, and treating them as competitors is the mistake. Parks are not decoration; they affect temperature, air quality and mental health, and a dense district without any open space quickly becomes the kind of place people leave as soon as they can afford to.",
    "The research is quite consistent that it is one of the strongest predictors of dissatisfaction. Two hours a day comes to something like five hundred hours a year, and that time is taken out of sleep, exercise and family life rather than out of work.",
    "Chiefly housing density and water. Cities will have to build upwards near transport rather than spreading outwards, and in dry regions such as ours the constraint on growth will be water supply long before it is land.",
  ],
  "health-and-lifestyle": [
    "Only partly, and framing it purely as individual responsibility is convenient for everyone else. Personal choices obviously matter, but those choices are made inside an environment of working hours, food prices and air quality that individuals do not control.",
    "Because habits are built from immediate feedback and health offers almost none. Exercise is uncomfortable today and beneficial in twenty years, which is the worst possible structure for motivation, so what succeeds is usually a change to the environment rather than an appeal to willpower.",
    "Regulating advertising is more defensible than regulating the food itself. Adults can decide what to eat, but advertising aimed at children exploits an audience that cannot evaluate a claim, and there is reasonable evidence that restrictions change what families buy.",
    "It has largely removed physical activity from the working day and replaced it with sustained sitting. The result is a strange combination of exhaustion and inactivity, plus the newer problem that work no longer stops when people leave the building.",
    "It is taken more seriously than it was, but not equally. Someone will explain a broken leg to their employer without hesitation and invent a different reason for a mental health appointment, which tells you the stigma has weakened rather than disappeared.",
    "They change awareness reliably and behaviour only sometimes. Campaigns work best when they are paired with something structural, such as a price change or a ban; on their own they tend to reach the people who were already interested.",
    "Basic care should be, in my view, because illness is not distributed according to merit and untreated conditions become far more expensive later. That is different from saying every possible treatment must be free, since no system has unlimited resources.",
    "Conditions linked to sedentary work and diet will keep rising, and I would add antibiotic resistance, which is potentially far more serious and receives much less attention. An ageing population also means dementia care becomes a major social question rather than a purely medical one.",
  ],
  environment: [
    "Individually, very little; collectively and politically, a great deal. The measurable effect of one person recycling is close to zero, but norms spread through households and neighbourhoods, and people who change their own behaviour are much more likely to vote and campaign for larger changes.",
    "Because the harm is distant and the convenience is immediate. There is also a fairness problem: giving up a car feels pointless while industry and aviation continue, so people conclude quite logically that their sacrifice would be symbolic.",
    "There is a strong case that they should, since they produced most of the historical emissions and have more capacity to pay. The practical difficulty is that agreements of this kind are easy to sign and easy to abandon when a government changes.",
    "It is useful for some materials and a distraction for others. Aluminium and paper recycle well, whereas much plastic is downgraded or exported, and the wider problem is that recycling reassures people that consumption itself is fine.",
    "By designing for repair and reuse rather than collection. That means separating waste properly at source, requiring producers to take back packaging, and providing repair services, since most household waste is decided long before it reaches the bin.",
    "Schools should teach the science and the systems, not just the guilt. Children who understand where electricity and water actually come from make better judgements as adults than children who have simply been told to care about the planet.",
    "Laws work better where the cost of compliance is high, because voluntary agreements are abandoned precisely when they start to hurt. Voluntary schemes are useful for moving fast in areas where nobody yet knows what the right standard is.",
    "Cautiously optimistic on technology and pessimistic on speed. Renewable energy has become cheap faster than almost anyone predicted, which is genuinely encouraging, but political timescales are much shorter than climate timescales and that mismatch is the real problem.",
  ],
  "work-and-careers": [
    "Money matters up to the point where it stops being a worry, and after that autonomy usually matters more. Most people I know will accept a lower salary for control over their time, but almost nobody accepts interesting work that does not pay the rent.",
    "It has changed expectations permanently, even at companies that have called people back. Once employees have proved they can work productively from home, being required to commute for tasks they performed perfectly well remotely needs a justification that many employers cannot give.",
    "They should expect it, though not always by choice. Whole categories of work now change within a decade, so the realistic ambition is a set of transferable skills rather than a single profession held for forty years.",
    "Largely because education systems respond slowly and forecast badly. Universities design courses years in advance and expand the fields that are popular rather than the ones that are needed, while employers rarely say clearly what they will require.",
    "Beyond a certain point I doubt they do. Most of the research I have seen suggests output per hour falls somewhere around the fifty-hour mark while errors rise, so very long hours often survive as a signal of commitment rather than because anyone has shown they produce better work.",
    "It matters more than people admit, simply because of the number of hours involved. That said, expecting a job to provide meaning as well as income puts enormous pressure on it, and being competent and reasonably paid is a defensible position.",
    "There is a strong practical argument for it. If a company automates a role it has benefited from that person's work, and retraining is usually cheaper than recruiting; the difficulty is that firms who train staff often lose them to firms who do not.",
    "Routine data handling and standardised written work are already disappearing. What is much less likely to go is anything requiring physical judgement in an unpredictable setting, which is why a plumber's job is safer than many office roles.",
  ],
  "media-and-advertising": [
    "Less by persuading people directly and more by shaping what feels normal. Very few buyers are convinced by a single advertisement, but constant repetition makes a brand the default option at the moment of choice.",
    "Yes, and most countries already accept the principle. Children cannot recognise persuasive intent until around eight, so advertising to them is not a fair exchange; the harder question is what to do about influencers, where the advertising is not labelled at all.",
    "Trust has fallen but not collapsed, and it has become political. People increasingly trust the outlets that match their existing views, which is arguably worse than general scepticism because it feels like discernment.",
    "Because emotional content travels faster than accurate content, and platforms reward engagement. A false claim can be simple and outrageous, whereas the correction requires context, so the correction always arrives late and reaches fewer people.",
    "Practically impossible now that it has moved inside the content itself. You can block advertisements in a browser, but a recommendation from a person you follow is advertising too, and it is designed specifically not to look like it.",
    "They should be transparent about what they promote rather than trying to judge every claim. Deciding truth at that scale is beyond any company, but publishing how ranking works and slowing the spread of unverified material is achievable.",
    "For younger audiences, considerably more, because it comes wrapped in an apparent relationship. That is also its weakness: the influence depends on seeming authentic, and it collapses quickly once the audience decides the recommendation was bought.",
    "It will become more personal and harder to identify. Advertising generated for one individual, in a familiar voice, is far more effective than a billboard, and I suspect regulation will lag behind that by many years.",
  ],
  "family-and-generations": [
    "The clearest change is that women's employment is now normal rather than exceptional, which has altered decisions about childcare, housework and where a family lives. Households have also become smaller, with married couples much more likely to live separately from their parents.",
    "Usually because they are describing genuinely different worlds. My grandparents' assumptions about work and security were formed in conditions that no longer exist, so what looks like stubbornness is often experience that has stopped applying.",
    "Culturally that expectation is very strong here, and I would not want to lose it. But it works only when it is shared rather than falling entirely on one daughter-in-law, and it becomes unrealistic when children live in another country.",
    "Less central for daily life, but still important at moments of pressure. Nobody now relies on cousins for childcare in the way they once did, yet when there is an illness or a wedding the extended family reappears immediately.",
    "It creates freedom and a persistent low-level guilt at the same time. Video calls maintain contact but not presence, and the difficulty is not missing celebrations so much as being unable to help on an ordinary difficult day.",
    "Perspective, mainly. Older relatives have seen problems resolve that felt permanent at the time, and they hold practical knowledge, from cooking to craftwork, that disappears entirely if nobody asks while they are still there to ask.",
    "Yes, in fairly predictable ways. Children in small families receive more attention and resources and tend to do well academically, but they negotiate less, and much of what siblings teach about conflict has to be learned later.",
    "I expect households to keep shrinking and people to have children later, with more families spread across countries. What I do not expect to disappear is the obligation itself, which seems to survive changes in how families are arranged.",
  ],
  "friendship-and-community": [
    "Repeated unplanned contact, more than shared values. Communities form where people keep encountering each other without arranging it, in courtyards, markets and schools, which is why neighbourhoods designed only for cars rarely develop one.",
    "Considerably harder, mostly for structural reasons. Friendship needs unstructured repeated time, which school and university supply automatically and adult life does not, so adults have to schedule what used to happen by itself.",
    "It has widened the word without deepening it. Maintaining contact across distance is genuinely valuable, but the same word now covers someone you would drive across the country for and someone whose posts you occasionally see.",
    "Because density is not contact. A city offers thousands of interactions with no obligation attached, and loneliness comes from being unnecessary to anyone rather than from being alone, which a crowd does nothing to solve.",
    "Expected is too strong; available is closer. A reasonable expectation is that neighbours will notice a problem and respond to a request, which is not the same as an obligation to be involved in each other's lives.",
    "Formal volunteering has declined in many countries, but a good deal of informal help has simply moved online or into messaging groups. What has genuinely weakened is the institutional structure, the clubs and unions that used to organise it.",
    "Enormously, and this is the most underrated part of planning. Courtyards, shared laundries and local shops produce recognition between people, whereas a building where everyone drives into an underground garage can house hundreds of strangers.",
    "The practical measures are unglamorous: transport, accessible public space, and reasons to leave the house. Programmes that pair generations, such as students living cheaply in exchange for time with older residents, work better than visits from professionals.",
  ],
  "money-and-success": [
    "Traditionally it has been defined by family standing, education and being able to support relatives, and property is still the clearest marker. Among younger people that is shifting towards independence and international opportunity, which is a noticeably more individual definition.",
    "Up to a point, and then unreliably. Additional income makes a large difference while it removes insecurity, and after that the effect flattens, partly because expectations rise to match whatever a person now earns.",
    "Yes, and it is one of the clearest gaps in most curricula. Interest, debt and basic contracts affect every adult, and leaving people to learn about them through their own mistakes is an expensive way to teach.",
    "Because they were formed under different conditions. Generations who experienced currency instability save differently from those who grew up with accessible credit, and each finds the other's behaviour irresponsible for reasons that made sense at the time.",
    "The evidence suggests it is, beyond a certain level. Very unequal societies tend to have weaker social trust and more contested politics, and the mechanism seems to be that the wealthy stop using the same schools, hospitals and transport as everyone else.",
    "I would say obligations follow from how wealth is created rather than from generosity. Almost every large fortune depends on public infrastructure, education and legal protection, so contributing through tax is closer to settling a bill than to charity.",
    "Substantially, because it changed the reference group. People once compared themselves with neighbours; now the comparison is with an edited version of the most fortunate people they have ever seen, which makes an ordinary standard of living feel like failure.",
    "It will become marginal rather than disappear entirely. Cash is resilient in a way digital systems are not, and it protects privacy and people outside the banking system, so eliminating it completely would create real problems for those who can least manage them.",
  ],
  "art-and-creativity": [
    "Because it is how societies process experience that argument cannot reach. Every known culture has produced music, decoration and story, which suggests it meets a need as basic as communication rather than being a luxury added once other needs are met.",
    "Yes, on the same grounds as funding parks or libraries. Work that is difficult or slow to find an audience will not survive on ticket sales alone, and the main risk of public funding is not waste but the temptation to fund only what is politically comfortable.",
    "The techniques certainly can, and much of what looks like inspiration is fluency acquired through practice. What is harder to teach is the willingness to produce bad work for long enough to reach good work, which is temperament as much as skill.",
    "They deserve serious time, though I would not insist on equality of hours. Art teaches judgement in situations with no correct answer, which no science lesson does, and treating it as an optional extra is what convinces most children they are not creative.",
    "It has removed the gatekeepers and, with them, most of the filtering. Anyone can now record and distribute work, which is a genuine democratisation, but the scarce resource has moved from production to attention, and attention is distributed very unevenly.",
    "It depends entirely on consent rather than on quality. A commissioned mural on a bare wall is clearly legitimate, and painting someone's house without permission is clearly not; the fact that the result may be good does not settle the question of whose wall it is.",
    "Usually because they address something that does not date, using technique good enough to survive changing fashion. There is also an element of accident, since institutions and reputation keep certain works visible while equally good work is forgotten.",
    "It will be a tool for most artists and a threat to the commercial middle of the market. Illustration and stock music are already affected, but these systems produce work that resembles what already exists, and that is the opposite of one person having something specific to say.",
  ],
  "food-and-globalisation": [
    "Because it solves a real problem cheaply. It is fast, predictable and affordable in cities where people have long commutes and little time, and the marketing then attaches it to convenience and status rather than to nutrition.",
    "Not disappearing, but narrowing. The dishes served at celebrations are secure, whereas the more complicated everyday recipes are quietly being lost because they take three hours that nobody working full time has.",
    "The evidence from sugar taxes is that they change what companies produce more than what consumers choose, which is arguably the point. The fair objection is that such taxes fall hardest on people with the least money, so they work best when paired with subsidies for better options.",
    "It gives consumers year-round variety and gives farmers unpredictable competition. Local producers cannot match the price of imports grown in a better climate, so without some protection or a market that values local food, the response is usually to stop farming.",
    "They cook less often but arguably more consciously. Previous generations cooked because there was no alternative; now cooking is partly a choice, which means it is done with more interest by fewer people and skipped entirely by many.",
    "Still important, and not primarily because of the food. A shared meal is one of the few occasions when a family talks without a purpose, and once that is lost the only conversations left are logistical ones.",
    "They broaden expectations and then get adapted. Dishes arrive, get adjusted to local taste within a decade, and are eventually treated as ordinary, so the influence runs in both directions rather than being simple replacement.",
    "More plant protein and more precisely targeted advice, driven by cost and climate rather than by preference. I doubt traditional food disappears, though; it tends to become occasional and ceremonial rather than daily.",
  ],
  "sports-and-discipline": [
    "Losing, mainly, in a setting where it does not matter. Team sport teaches children to be dependent on people they did not choose and to keep cooperating after a bad result, which classrooms rarely require of them.",
    "Their pay reflects the revenue they generate, so it is not irrational, but the distribution is troubling. A handful of athletes earn enormous sums while most professionals in the same sport earn very little and retire early with injuries.",
    "Participation should be, but competitive sport should not. Compulsory competition is precisely what makes unathletic children avoid exercise for the rest of their lives, whereas a wider choice of activity keeps far more of them moving.",
    "Because supporting a team is an inherited identity as much as an interest. It offers belonging that requires no qualification, and shared emotion with strangers, which modern life provides in very few other places.",
    "It helps when the emphasis is on improvement and harms when it is on selection. Early specialisation and constant ranking produce burnout and injury, and the children who are physically developed earliest are often mistaken for the most talented.",
    "More than we would like, particularly on younger audiences. That influence extends beyond sport to behaviour and health, which is why an athlete's conduct off the field is treated as a legitimate public matter rather than a private one.",
    "Rarely, on the evidence. The economic benefits projected before major events almost never appear, and cities are frequently left with facilities they cannot maintain; investment in ordinary local sport reaches far more people for less money.",
    "Officiating is already being changed by video and sensors, and that will continue, though it has made decisions slower rather than simpler. The bigger change may be in training, where detailed physiological data allows workloads to be managed individually.",
  ],
  "books-and-reading": [
    "Because reading now competes with media designed to be far more immediately rewarding. It is not that people read less text; they read enormous amounts on screens, but sustained attention on one long argument has become genuinely rare.",
    "Yes, though the value is indirect. Following a character whose reasoning you do not share is one of the few reliable ways to practise understanding another mind, and there is reasonable evidence linking it to empathy and to writing ability.",
    "More necessary than they appear, and less about books than they used to be. Libraries now function as free, warm, quiet public space with internet access, which for students and older residents is often the point of them.",
    "They make reading more convenient and slightly more shallow. Search and portability are real advantages, but people remember location within a physical book, and a device that also delivers messages is a poor place to concentrate.",
    "A common core is defensible, provided it is not the whole diet. Shared texts allow a class to argue about the same thing, but a curriculum made entirely of difficult classics is very effective at persuading teenagers that reading is a chore.",
    "Almost certainly, because it supplies patterns rather than rules. People who read widely produce more varied sentences without being able to explain why, in the same way that listening produces pronunciation.",
    "Usually because they deal with situations that keep recurring, and because each generation finds a different meaning in them. Institutional momentum plays a part too, since a book on every syllabus stays in print regardless of its merits.",
    "Fragmented and increasingly audio. That is not simply a decline, since audiobooks have brought long-form work back to people who commute, but I do think uninterrupted reading will become a deliberate practice rather than an ordinary habit.",
  ],
  "language-and-identity": [
    "Because a mother tongue carries more than meaning. It holds humour, family memory and the particular way a community expresses affection, so criticism of the language is experienced as criticism of the people who speak it.",
    "It changes what you notice more than how you reason. Different languages force attention to different things, such as formality or evidence, and learning one also gives you the useful experience of being unable to express yourself, which is humbling in a productive way.",
    "Protection is worth attempting, but law alone is not enough. A language survives when it is used for ordinary purposes, so schooling, media and employment matter far more than official status, which can be granted while the language still disappears.",
    "It is dominant, and the effects are mixed. A common language makes research and trade enormously easier, yet it also means native speakers gain a permanent advantage in international careers and much good work never travels because it was written in the wrong language.",
    "Very much so, and usually unconsciously. Studies consistently show accents affecting assumptions about competence, which is unjust given that an accent reflects where someone learned to speak rather than how well they think.",
    "Chiefly ways of describing things that other languages do not need. When a language goes, so do its songs, plant names and oral history, and the community loses direct access to its own past, which is the more painful loss.",
    "Early exposure helps pronunciation most, and that advantage is real. But motivation matters more overall, and an adult with a clear reason to learn usually progresses faster than a child in compulsory lessons.",
    "It will reduce the need for functional translation and not the need for fluency. Software can order food or handle documents, but negotiation, humour and trust depend on speaking to someone directly, and people respond quite differently to those who made the effort.",
  ],
  "shopping-and-consumption": [
    "Because buying resolves a feeling rather than a need. Purchasing offers a small, immediate sense of progress, and marketing attaches identity to objects, so people are often buying a version of themselves rather than the product.",
    "It has improved choice and price while damaging the streets themselves. Many town centres have lost the shops that gave people a reason to be there, and once that happens the remaining businesses fail too, which is a cost that does not appear in the price of delivery.",
    "Yes, and I would say the case for regulating this is stronger than for most consumer questions. The same manufacturer will sell a repairable model where the law requires spare parts and a sealed one where it does not, which suggests short lifespans are a commercial decision rather than a technical necessity.",
    "They encourage volume rather than need, which is precisely their purpose. A discount reframes spending as saving, and events like large seasonal sales generate enormous quantities of returned and discarded goods.",
    "Some, but far less than campaigns imply. Consumers cannot audit a supply chain from a label, and asking individuals to solve conditions in factories they cannot see shifts responsibility away from the companies and regulators who can.",
    "Considerably more acceptable, especially among younger buyers, and cost is the main reason. The change in status matters too, since buying second-hand is now read as environmentally aware rather than as an indication of poverty.",
    "Repair remains much more common here than in wealthier countries. There are still workshops for shoes, phones and appliances in most neighbourhoods, though that is gradually weakening as goods become cheaper and harder to open.",
    "I expect more subscription and rental, and slower delivery presented as a virtue rather than a failure. The direction of regulation on repair and packaging will probably shape habits more than consumer preference does.",
  ],
  "crime-and-safety": [
    "Familiarity more than policing. People feel safe where they recognise faces, where streets are lit and overlooked by windows, and where there is activity in the evening; a well-patrolled but empty district still feels threatening.",
    "Prevention is more effective and much less visible, which is why it is politically difficult. Investment in education, employment and mental health reduces offending years later, whereas punishment produces an immediate response that voters can see.",
    "Widely is the word I would question. The evidence suggests cameras work well in defined places such as car parks and much less well across open streets, so general surveillance asks citizens to accept permanent monitoring for a fairly modest benefit.",
    "Part of it is genuine and part of it is measurement. Areas with less policing presence and lower reporting rates can look safer than they are, and beyond that the strongest predictors seem to be transience and weak local ties rather than income by itself.",
    "The evidence is that certainty of being caught deters far more than severity of sentence. Longer sentences do incapacitate individuals, but they are expensive and they do little to change the calculation of someone who does not expect to be caught at all.",
    "The relationship is real but not simple. Poverty alone does not produce crime; poverty combined with visible inequality and few routes out does, which is why unequal wealthy cities often have worse problems than uniformly poor areas.",
    "A considerable one, mostly by keeping young people attached to something. Schools that identify difficulties early and offer activity outside lesson hours do more preventive work than any policing initiative aimed at the same age group.",
    "It removes distance and scale as limits, so one person can defraud thousands in another jurisdiction. It is also under-reported, because victims feel foolish and often do not know which authority to approach, which makes it hard to measure honestly.",
  ],
  "science-and-innovation": [
    "Mostly because research is a long-term investment that only wealthy or strategically confident states can sustain. Countries with unstable budgets fund what shows results within an electoral cycle, and basic research almost never does.",
    "They should be central to the discussion but not the only voice. Researchers understand the risks in a way nobody else does, yet the consequences fall on the public, so decisions of that kind need scientific input rather than scientific authority.",
    "By being honest about uncertainty rather than simplifying it away. The public handles probability better than communicators assume, and the damage to trust comes from confident statements that are later reversed, not from admitting what is unknown.",
    "It is well funded relative to most fields, but distributed by market size rather than by need. Conditions common in poorer countries attract very little investment, which is a failure of incentives rather than of science.",
    "Broadly yes, though trust in institutions is weaker than trust in the science itself. People generally accept medical advice from their own doctor while doubting the agency that issued it, which suggests the problem is one of relationships rather than evidence.",
    "Yes, and preferably before the capability exists rather than after. Autonomous weapons and large-scale surveillance are the clearest cases, and the difficulty is that any country imposing limits alone worries about disadvantaging itself.",
    "Essential, and it is one of the few areas where cooperation has genuinely survived political hostility. Large facilities are too expensive for any single country, and problems such as pandemics and climate do not respect borders in the slightest.",
    "Probably advances in biology rather than in computing. Gene therapies and better diagnostics could change ordinary life expectancy substantially, though whether they reach everyone or only wealthy patients is a separate question.",
  ],
  "tradition-and-modern-life": [
    "The ones that do actual work, such as hospitality and the customs around births and funerals. They organise support at moments when people cannot organise it themselves, which is quite different from traditions kept only because they are old.",
    "Often because the custom is presented as an obligation without an explanation. Young people also encounter alternatives constantly, so a practice that is never justified competes badly, and some traditions are rejected for good reasons rather than out of fashion.",
    "It can, but it becomes fragile. A practice continued out of habit still creates the gathering and the shared memory, which has real value; the risk is that once nobody can explain it, there is nothing left to defend it with.",
    "They tend to become larger, more expensive and more standardised. Commercial pressure does keep some celebrations alive by making them profitable, but it also turns participation into spending, and families who cannot spend feel excluded from their own culture.",
    "Support is justified where a craft carries knowledge that would otherwise be lost, since a technique takes years to learn and dies with the last practitioner. It works best as training and market access rather than as a subsidy that removes any need to find buyers.",
    "Honestly, no, and that is the main threat rather than any hostility to tradition. Practices that assume an unhurried afternoon do not survive a two-hour commute, so what survives is whatever can be compressed into a weekend.",
    "Mostly through food and celebration rather than through instruction. That transmission is now much more deliberate than it was, since children no longer absorb it simply by being present, and a good deal is preserved online instead.",
    "The framework will probably survive while the details change beyond recognition. I would expect hospitality and the major celebrations to continue in some form, because they answer a need, and much of the accompanying detail to be quietly replaced.",
  ],
};

export const PART3_SAMPLES: Record<string, Part3Samples> = { ...SET_A };
