/** Part 1 model answers, one per question.
 *
 *  These used to be seven generic "points" per topic written for an older set
 *  of template questions (like it? / how often? / past vs now? / your country? /
 *  more important now? / future? / an example). When the questions were
 *  rewritten per topic, the answers stayed in that old order, so the app showed
 *  "Where is your hometown?" answered with "I am fond of my hometown because it
 *  has a calm rhythm". Two further sentences were then bolted on from a shared
 *  pool, which is why every answer ended with lines like "That is the aspect I
 *  would emphasise in a natural conversation".
 *
 *  Each string below answers the question at the same index in
 *  PART1_CONTENT[slug].questions, and is complete on its own: a direct answer,
 *  a reason or detail, and one concrete example. Two to three sentences, which
 *  is what Part 1 actually rewards.
 */
export type Part1Samples = readonly [string, string, string, string, string, string, string];

const SET_A: Record<string, Part1Samples> = {
  "work-study": [
    "I am a student. I am in my third year of software engineering at a university in Tashkent, and I also do a few hours of freelance work most weeks to keep my skills current.",
    "The most interesting part is building something that actually runs. In our database module we designed a small system from scratch, and seeing real queries return results made the theory finally click.",
    "I would like fewer lectures and more lab time. We spend a lot of hours listening to material that is already in the textbook, whereas the practical sessions are where I genuinely learn.",
    "Definitely the morning. My concentration is sharpest before about eleven, so I save difficult coding for then and leave email and admin tasks for the late afternoon.",
    "Physics, mainly because of the teacher I had in the last two years. She explained everything through everyday examples, so it never felt like memorising formulas for an exam.",
    "Probably not exactly the same thing. I expect to still be in software, but I would like to have moved from writing code alone to leading a small team on a product I believe in.",
    "It depends on the task. I prefer working alone when I need deep concentration, but for anything involving design decisions a team catches mistakes that I would never notice by myself.",
  ],
  hometown: [
    "My hometown is Namangan, in the Fergana Valley in the east of Uzbekistan. It is one of the larger cities in the country, although it feels much calmer than Tashkent.",
    "I lived there for eighteen years, until I moved to the capital for university. I still go back every few months, usually during holidays and for family events.",
    "It is known for its fruit and its flowers, especially in spring. There is also a long tradition of craftwork, and the older parts of the city still have workshops that have been in the same families for generations.",
    "It has changed a great deal. Whole districts of apartment blocks have gone up, the main road was widened, and several of the small orchards I remember from childhood are now shopping centres.",
    "Visitors usually mention the food and the hospitality. People there invite guests home very quickly, so someone who expected a purely sightseeing trip often ends up spending an afternoon at a stranger's table.",
    "It is a comfortable place to live but a limited one to build a career in. It is safe, everything is close and the rent is low, yet most of my classmates still moved to Tashkent, as I did, because that is where the work is.",
    "I might, but not permanently. I would like to work abroad for a few years to gain experience, and then come back, because my parents and my oldest friends are still there.",
  ],
  home: [
    "I live in an apartment, on the fourth floor of a nine-storey block in Tashkent. I rent it with my younger brother, who started university a year after me, so it is only the two of us.",
    "The kitchen, without question. It is where we eat, where I study when the table is free, and where everyone ends up sitting when friends come round, rather than in the other room.",
    "I would add proper storage. We have books and equipment stacked in every corner simply because there are not enough shelves, and the flat feels more crowded than it really is.",
    "At home, generally. Hosting is normal in my family and it is much cheaper than a restaurant, although I meet friends outside when I want a change of scene.",
    "Yes, with my younger brother, back in Namangan. We argued about the light and the noise constantly, so it is slightly funny that we now share a flat by choice.",
    "Something modest but bright. I do not need a large house; I would rather have big windows, a quiet room to work in, and a small garden or terrace for the summer.",
    "There is, although it is nothing dramatic. I look out onto a courtyard with a few old trees, and in spring it is genuinely pleasant to work with the window open.",
  ],
  friends: [
    "I have a few close ones. I know a lot of people through university, but there are maybe four I would call at midnight if something went wrong.",
    "I met my closest friend on the first day of secondary school, when we were put at the same desk. We had almost nothing in common at first, but we ended up walking home together every day for six years.",
    "Nothing elaborate, usually. We meet in a café, walk around the city, and talk for hours; occasionally we play football at the weekend if enough people are free.",
    "It is reasonably easy, especially through study or work. What is harder is turning an acquaintance into a real friendship, because everyone here is quite busy once they start working.",
    "They have, mostly in how often we meet. We used to see each other daily without planning anything, whereas now it takes two weeks of messages to arrange a single evening.",
    "Honesty, above all. I would rather have a friend who tells me directly that I am wrong than one who agrees with everything, and reliability matters more to me than being entertaining.",
    "Face to face, definitely. Messaging is convenient for arranging things, but you miss tone completely, and half the value of seeing someone is noticing they are not actually fine.",
  ],
  music: [
    "Mostly instrumental music, film scores and some jazz. I also listen to a lot of Uzbek pop when I am with friends, although I would not choose it myself.",
    "Almost always while I am doing something else, such as commuting or working. If I am reading something difficult I turn it off, because lyrics make it impossible to concentrate.",
    "I learned the guitar for about two years in secondary school. I can still play a handful of songs, but I stopped practising when exams started and never really went back.",
    "Recordings, for everyday listening. A concert is a much stronger experience, though, because the energy of the crowd changes the music itself, so I go whenever there is something worth seeing.",
    "It has changed a lot. As a teenager I mainly listened to whatever was popular, and over time I moved towards quieter, more instrumental things, partly because I use music for focus now.",
    "Among most young people, not really, at least not for everyday listening. It comes back at weddings and celebrations, though, and there are a few musicians mixing traditional instruments with modern production who are genuinely popular.",
    "I would like to go back to the guitar. I have thought about the piano as well, but I know from experience that I need something I can pick up for ten minutes rather than a serious commitment.",
  ],
  movies: [
    "Perhaps one or two a week, usually at the weekend. During exam periods it drops to nothing, and then I catch up on everything I missed in a couple of days.",
    "At home, for practical reasons. I can pause it, it costs nothing, and I can put the subtitles on; the cinema is better for anything visual, but I only go two or three times a year.",
    "Horror. I do not find it enjoyable to be frightened deliberately, and the plots usually depend on characters making decisions no reasonable person would make.",
    "Yes, The Martian. I have seen it three or four times, because it is essentially about solving problems calmly, which I find oddly reassuring before a stressful week.",
    "A lot, mostly cartoons and old Soviet films that my grandfather had on tape. We watched them together on Sundays, and I still recognise the music from them immediately.",
    "The original language, with subtitles. Dubbing changes the performance completely, and watching in English has also done more for my listening than most of my classes.",
    "Yes, but I would choose carefully. I would not recommend something long or slow; I would pick a film with a strong story and let them discover the rest themselves.",
  ],
  food: [
    "Plov, without hesitation. It sounds like the predictable answer for someone from Uzbekistan, but it genuinely is the dish I would choose, especially the version my uncle makes with quince.",
    "Mainly at home. Eating out has become expensive, and home cooking is simply better most of the time, so I eat out perhaps once a week when I meet friends.",
    "At my parents' place it is my mother during the week, and my father takes over completely for the plov at weekends. In our flat here I do almost all of it, mostly because my brother is worse at it than I am.",
    "They have. I eat far less bread than I used to, and I have had to cook for myself since I moved to Tashkent, which has made me much more aware of what actually goes into a meal.",
    "Pumpkin. As a child I refused anything with pumpkin in it, and now I actually enjoy it, particularly in samsa, which I would have found unthinkable at ten years old.",
    "Plov again, but I would also make a simple salad and serve fresh non with it. It is the meal people here are proud of, and it works well for a group.",
    "I do, though not obsessively. I try to eat vegetables with most meals and avoid eating late at night, but I am not counting anything or following a specific diet.",
  ],
  shopping: [
    "Not particularly. I find it tiring rather than relaxing, so I tend to decide what I need beforehand and get it done quickly.",
    "Mostly online now, especially for electronics and books. For clothes I still prefer a physical shop, because sizes vary so much that ordering is a gamble.",
    "A pair of running shoes, about a month ago. I had been putting it off for a long time, and my old ones were genuinely worn through.",
    "I plan, generally. I keep a list on my phone and add things to it over a week, which stops me buying something on impulse and regretting it.",
    "Yes, there is a large bazaar about fifteen minutes away. I go mainly for fruit and vegetables, because the quality is better and it costs noticeably less than a supermarket.",
    "It has changed enormously. Online shopping and card payments were unusual when I was at school, and now even small sellers at the bazaar accept transfers by phone.",
    "Occasionally, yes. It is usually small things such as coffee or apps rather than anything large, but they add up more than I would like to admit.",
  ],
  sports: [
    "I play football, though only casually. A group of us book a pitch most Saturdays, and I run two or three times during the week on my own.",
    "Football, by a long way. Almost every boy grows up playing it, and when the national team plays an important match the streets are genuinely empty.",
    "Taking part, definitely. I enjoy watching a big match, but an hour of playing badly is more satisfying to me than ninety minutes of watching other people play well.",
    "We had physical education twice a week, which was mostly football and running. I was not on any team, but I liked it more than I expected because it broke up the day.",
    "Running, mainly, plus the football at weekends. I also try to walk instead of taking the bus when I have time, which is probably more useful than it sounds.",
    "I would like to try swimming properly. I can stay afloat, but I have never learned technique, and I know it is one of the few sports that uses everything at once.",
    "I follow Uzbekistan's national team closely, and I watch Barcelona when I can. I would not call myself a serious fan, though, because I rarely watch a full league season.",
  ],
  technology: [
    "My laptop, easily. My phone is always in my hand, but almost everything that actually matters, studying, coding and writing, happens on the laptop.",
    "Constantly, for study more than entertainment. I look up documentation, watch tutorials, take an online course most terms, and use it for banking and transport as well.",
    "Reasonably good, yes. I do not read instructions; I open the app and press things until I understand it, which works most of the time and occasionally causes problems.",
    "Completely. I can find a clear explanation of almost anything in a few minutes, which is a huge advantage, although it also makes it very easy to feel that I have learned something when I have only watched it.",
    "I remember a shared family computer with a very slow connection. I was about eight, and I was allowed thirty minutes at a time, which made those thirty minutes feel enormously important.",
    "Notifications. I would not give up the phone itself, but the constant interruptions break my concentration, and I now keep almost all of them switched off.",
    "I imagine much more will be voice-based and automated. I expect AI tools to handle the routine parts of programming, which means the valuable skill will be deciding what to build rather than typing it.",
  ],
  books: [
    "Less than I would like. I read a great deal of technical material for my course, but proper reading for pleasure is usually limited to holidays.",
    "Non-fiction, mostly, particularly popular science and books about how people work. I read novels occasionally, though I find I remember them less clearly.",
    "On a screen, for convenience. I read on my laptop or phone because I always have them with me, but I concentrate noticeably better on paper.",
    "Yes, my grandmother read to me almost every evening. They were mainly folk tales, and I think that is where my habit of reading before sleeping came from.",
    "Atomic Habits, by James Clear. It is quite simple, but it changed how I approach studying, because it treats consistency as a design problem rather than a question of willpower.",
    "Probably less, at least in the traditional sense. People read constantly on their phones, but sitting with a book for an hour has become unusual among people my age.",
    "Perhaps a technical one, eventually. I would not attempt a novel, but I could imagine writing a practical guide for beginners in programming once I actually know enough to be useful.",
  ],
  holidays: [
    "Usually somewhere within Uzbekistan, such as the mountains near Chimgan or a few days in Samarkand. International travel is expensive, so it tends to be one big trip every few years.",
    "Short breaks suit me better. After about a week I start feeling restless, and several long weekends spread across a year give me more benefit than one long holiday.",
    "Normally with friends or with my family, depending on the trip. I have never travelled completely alone, though I would like to try it once.",
    "I went to Samarkand for three days with two university friends. We travelled by the fast train, walked far more than we planned, and spent most of the money on food.",
    "I like a rough plan, not a schedule. I book transport and somewhere to stay in advance, and then leave the days themselves fairly open, because the best parts are usually unplanned.",
    "Navruz, more than any other. The city genuinely feels different, everyone cooks together, and it comes at the point in spring when the weather has just turned.",
    "Japan, without much hesitation. I would spend most of it in Kyoto and the smaller towns rather than Tokyo, because I am more curious about ordinary daily life than the famous sights.",
  ],
  weather: [
    "It is quite extreme, actually. Summers reach forty degrees and are very dry, winters can fall well below zero, and spring and autumn are short but genuinely beautiful.",
    "Autumn, easily. It is warm without being exhausting, the fruit is at its best, and it is the only time of year when walking across the city is a pleasure.",
    "More than I would expect. Several grey days in a row make me noticeably slower and less willing to go out, whereas a bright morning gets me working early.",
    "Only in summer and winter, when it matters. In summer I check the temperature to decide when to go out, and in winter I check whether I need to leave earlier for the ice.",
    "Honestly, I quite enjoy it. Rain is rare here, so it feels like an event; I usually stay in, cook something slowly and get through work I have been avoiding.",
    "It seems to have. The summers feel longer and hotter than I remember, and we get much less snow than we did when I was at primary school, although I know memory is unreliable.",
    "Somewhere milder, yes. I would not want anywhere cold and dark for months, but a climate without forty-degree summers would suit me very well.",
  ],
  neighbours: [
    "Reasonably well, yes. I could not tell you much about their work, but I know all their names, and we would notice immediately if something was wrong.",
    "Briefly, most days. It is usually a few words in the stairwell or by the entrance rather than a real conversation, but that adds up over the years.",
    "Being considerate about noise, mainly. Beyond that, a good neighbour notices things without interfering, so they ask if you seem to have a problem but do not appear at your door every evening.",
    "Yes, several times. Once we were away and a pipe burst, and the woman below noticed the water, called my father and let the plumber in before any real damage was done.",
    "They were closer, I think. We lived in a house then, all the children played in the street together, and the adults sat outside in the evenings in a way that does not happen in an apartment block.",
    "Generally, yes, particularly at times of celebration or difficulty. If there is a wedding or a funeral in the building, everyone contributes something without being asked.",
    "Somewhere quieter. I like being near the centre, but the traffic under the window is constant, and I have noticed how much better I sleep at my grandparents' house.",
  ],
  clothes: [
    "Fairly plain things, mostly. Jeans, a shirt or a jumper, and trainers; I keep the colours simple so that I do not have to think about it in the morning.",
    "Slightly, yes. At university it is casual, but I have a shirt and proper shoes for presentations and interviews, because appearance affects how people listen to you.",
    "Not very often, perhaps every few months. I tend to wear things until they wear out and then replace them, rather than buying regularly.",
    "Not really. I notice what is popular, but I would not buy something simply because it is fashionable, partly because it usually stops being fashionable within a year.",
    "Not until I was about twelve. My mother chose everything before that, and I remember arguing about a jacket that I refused to wear because it was the wrong colour.",
    "Yes, though mainly for occasions. People wear a chapan or a traditional dress at weddings and for Navruz, and the embroidery patterns have also come back into everyday fashion recently.",
    "Comfort, for me. I would not wear something I disliked the look of, but if a jacket is uncomfortable I simply stop wearing it, however good it looks.",
  ],
  pets: [
    "Not at the moment. I live in an apartment and I am out for most of the day, which would not be fair on an animal.",
    "We had a cat for about ten years. She essentially adopted us; she appeared in the courtyard one winter and never left.",
    "Cats are quite common, especially in apartments, and dogs are more usual in houses and villages where they also guard the property. Keeping unusual animals is rare here.",
    "The routine it creates, I think. An animal makes you get up and go outside regardless of your mood, and there is something genuinely calming about looking after something else.",
    "Yes, if the family is honest about who will do the work. Children learn responsibility from it, but only when they are actually the ones feeding and cleaning rather than just playing.",
    "A snake, or anything similar. I have no particular fear of them, but I could not relax in a flat knowing there was one in the next room.",
    "Probably, once I have a place of my own with more space. I would choose a cat rather than a dog, because it fits the hours I work.",
  ],
  photography: [
    "I do, though I am not serious about it. I take a lot of pictures when I travel and very few otherwise, which is probably the wrong way round.",
    "Buildings and streets, mostly. I rarely photograph people, partly because I never feel comfortable asking, so my photos are quiet in a way that is sometimes a bit empty.",
    "They stay on my phone, unfortunately. I have printed perhaps ten in my life, and those are the ones I actually look at, which tells me something.",
    "Enormously easier. My phone takes better pictures than a proper camera did fifteen years ago, and the cost of taking a thousand photographs is now zero.",
    "Not really. I am the one holding the camera in most family photos, which I suspect is partly deliberate on my part.",
    "Only by accident, when I am looking for something else. Then I lose half an hour, because a picture brings back things I had completely forgotten.",
    "I would like to. What interests me is not the equipment but composition, understanding why one photograph works and a very similar one does not.",
  ],
  "social-media": [
    "Telegram most of all, which here is used for everything from group chats to news. I also have Instagram, and I use YouTube constantly, if that counts.",
    "More than I would like. Telegram is probably an hour in total, spread across the whole day, and Instagram perhaps twenty minutes of genuinely wasted time.",
    "Mostly reading. I post a few pictures after a trip and almost nothing otherwise, because I have never really understood the appeal of documenting an ordinary day.",
    "Completely. I keep in touch with people I would definitely have lost contact with, though the contact itself is much shallower than it used to be.",
    "Some of them. Telegram was already everywhere, but Instagram became popular around the time I finished school, so I remember the period before it quite clearly.",
    "Some people do, yes, particularly about their families. What concerns me more is not the oversharing but how carefully edited everything is, because it gives a very false impression of other people's lives.",
    "Yes, and I have done it. I deleted the apps during exams last year, and after two uncomfortable days I did not miss them at all, which was slightly humbling.",
  ],
  running: [
    "Yes, two or three times a week, usually early in the morning. It is nothing impressive, about five kilometres, but it is the one form of exercise I have kept up.",
    "In the parks, mainly, and along the canal path. The pavements are not really designed for it, so most people go somewhere with a bit of green space.",
    "By making it small. I promise myself only twenty minutes, which removes the excuse, and I almost always run longer once I am outside.",
    "Alone, for running. I use the time to think, and having to hold a conversation ruins it, whereas for football or the gym I would much rather have company.",
    "Only when we were made to. I disliked it intensely then, mainly because it was always presented as a test rather than something you might enjoy.",
    "Noticeably, yes, especially in the cities. There are far more people out in the parks in the morning than five years ago, and organised runs have started appearing.",
    "I would, at some point. A half marathon would be a sensible target, though I would want a proper training plan first rather than simply hoping for the best.",
  ],
  cooking: [
    "Yes, though within limits. I can make maybe ten dishes well and I improvise badly, so I would not want to cook for a large group.",
    "My mother, mostly, although she taught me by giving me jobs rather than lessons. I peeled and chopped for years before I was allowed to decide anything.",
    "Fried eggs, which barely counts. The first real dish was a simple lagman, which took me about three attempts before the noodles were edible.",
    "From memory, mainly, which is why the results vary. I look up a recipe the first time and then never open it again, adjusting as I go.",
    "Four or five times, usually in the evening. I tend to cook enough for two days at once, because doing it every single day is not realistic with my timetable.",
    "It is becoming one, yes, particularly among young men, which would have been unusual a generation ago. Social media has a lot to do with it, since cooking videos are everywhere.",
    "Proper plov, made in a kazan. I can make an acceptable version in a pan, but the traditional method is a genuine skill and I would like to learn it from my uncle before he stops cooking.",
  ],
  travelling: [
    "Within the country, quite a lot. Internationally, very little; I have only been abroad twice, once to Kazakhstan and once to Turkey, and both were short trips.",
    "By train between cities, because the fast trains are comfortable and reliable. Within a city I walk as much as possible, since that is where you actually see things.",
    "Istanbul, which is not very far by international standards. It was the first place I had been outside Central Asia, and what struck me most was how familiar parts of it felt.",
    "Cities, generally, though I need a day in the countryside afterwards. I like the density of a city, the food and the museums, but three or four days is my limit.",
    "Not much, and mostly to relatives. Holidays meant going to my grandparents' village rather than anywhere new, which I resented at the time and now remember fondly.",
    "A power bank, headphones, and far too many cables. I have also learned to pack one set of clothes fewer than I think I need, because I never wear them.",
    "Japan, as I mentioned, and after that Italy. Both interest me for the same reason, that they have kept something old alive inside a very modern country.",
  ],
  "daily-routine": [
    "Around half past six on weekdays. I am not naturally an early riser, but my first class is at eight and the commute takes forty minutes.",
    "I get up, run or have breakfast depending on the day, and I am at university from eight until about two. Afterwards I study in the library, get home by six, and spend the evening on my own projects or calling my parents.",
    "Broadly the same on weekdays, and completely different at weekends. That contrast matters to me, because otherwise the weeks would blur into each other entirely.",
    "Mid-morning, between nine and midday. There is a second, weaker window around nine in the evening, but anything I write late at night I usually rewrite the next day.",
    "It has, quite a lot. I started running and moved my difficult work to the morning, and those two changes together made more difference than anything else I have tried.",
    "Roughly. I write three things I must finish the night before, which is realistic, whereas the detailed hour-by-hour plans I used to make were abandoned by ten in the morning.",
    "Reading properly, for pleasure. I keep telling myself I will read before bed and then spend that time on my phone instead.",
  ],
  teachers: [
    "My physics teacher in the last two years of school, Nodira Rustamovna. She had a reputation for being demanding, which turned out to be entirely accurate and exactly what I needed.",
    "She explained why things were true rather than what to memorise. She also admitted when she did not know something and came back the next week with an answer, which taught me more than the physics did.",
    "Strict, if the strictness has a reason. I have had relaxed teachers whose classes were pleasant and taught me nothing; what I dislike is arbitrary strictness about rules rather than standards.",
    "Yes, several online courses. The best of them was as good as anything at university, although you lose the ability to ask a question the moment you are confused, which matters more than I expected.",
    "It is respected in principle, certainly, and teachers are treated with real courtesy. The pay does not always match that respect, though, which is why many good graduates go elsewhere.",
    "Reaching thirty people who are all at different levels. Some are bored and some are lost, and the teacher has to keep both groups engaged for the same forty-five minutes.",
    "I have thought about it. I would enjoy it part-time, teaching programming to beginners, but I doubt I have the patience to do it full-time for a whole career.",
  ],
  "public-transport": [
    "Mainly by metro, and by bus when the metro does not reach where I am going. I walk the last part of most journeys, which is usually faster than waiting.",
    "The metro is very reliable, and it is genuinely one of the best things about the city. The buses are less predictable, because they are stuck in the same traffic as everyone else.",
    "About forty minutes door to door. Roughly half of that is the metro, and the rest is walking and waiting, which I have learned to plan around.",
    "The metro, easily. It is faster, it is not affected by traffic, and the older stations are beautiful enough that I still notice them after three years.",
    "It has improved noticeably. There are new lines, the payment system works by card now, and the newer buses are far better, though the routes still do not connect very logically.",
    "I read or listen to something. The metro is too crowded to hold a book at rush hour, so it is usually a podcast, and that is where a lot of my English listening practice happens.",
    "Not really, in this city. Driving here means traffic and nowhere to park, so I would only want a car for travelling outside Tashkent at weekends.",
  ],
  art: [
    "Moderately, yes. I would not claim any expertise, but I go to exhibitions when there is something interesting and I pay attention to design in a way I did not before.",
    "Not especially. We copied things rather than made anything, and since I could not draw well it felt like a subject I was simply bad at.",
    "Yes, I went to the Museum of Applied Arts a few months ago. What stayed with me was the ceramics rather than the paintings, particularly how much of the pattern work is mathematical.",
    "Yes, but taught differently. It should be about looking carefully and making things, not about producing an accurate drawing, because most children conclude far too early that they have no talent.",
    "The suzani embroidery my grandmother made. It is not in a gallery and it is not famous, but the design is genuinely sophisticated and it took her years.",
    "Occasionally, badly. I sketch interfaces when I am designing something, which is a very functional kind of drawing, but I find the process itself enjoyable.",
    "Very much so, though more in craft than in painting. Architecture, tilework, textiles and music are woven into ordinary life here in a way that fine art in a gallery is not.",
  ],
  money: [
    "Easier than I used to. I set aside a fixed amount as soon as I am paid, and because I never see it in my main account, I do not spend it.",
    "By card, almost always. Cash was standard until quite recently, and now even the bazaar mostly takes transfers, which is convenient but makes spending far less noticeable.",
    "A small amount, yes, and I spent all of it immediately on sweets. My father eventually gave me a month's worth at once, which was a deliberate and quite effective lesson.",
    "Food and transport take most of it, and after that books and software subscriptions. The subscriptions are the ones I should probably review, since several renew without my noticing.",
    "Enormously. Cash was normal five or six years ago, and now almost everything is on a phone, including transfers between individuals, which older relatives still find slightly alarming.",
    "Loosely. I check the app every week or so rather than recording each purchase, which is enough to notice a problem without turning into a second job.",
    "I would rather save, generally. Small treats disappear without leaving much behind, whereas saving for something specific gives the whole month a purpose.",
  ],
  health: [
    "Reasonably, yes, with obvious gaps. I exercise and eat fairly well, but my sleep is poor during exam periods and I sit down for far too much of the day.",
    "About seven hours, though it varies. I know I need eight, and the difference between seven and eight is very obvious in how well I concentrate the next morning.",
    "I go for a walk, usually without my phone. Exercise works better for me than anything else, and talking it through with a friend helps more than trying to solve it alone at midnight.",
    "It has. I eat far less sugar and many more vegetables, and I have almost stopped buying things in packets, which I used to live on during my first year here.",
    "Younger people increasingly do, yes. Older generations tend to rely on traditional remedies and family advice, and there is still some reluctance to see a doctor before a problem becomes serious.",
    "Not as often as I should. I go when something is wrong rather than for a routine check, which I know is the wrong way round.",
    "My phone use before sleeping. It is the single habit that damages everything else, because a bad night affects my concentration, my mood and even whether I bother to exercise.",
  ],
  "language-learning": [
    "About nine years in total, since I was eleven. The early school lessons achieved very little apart from the last two years, and the real progress started when I began using English for things I actually cared about.",
    "Speaking, without question. I can read technical material comfortably, but producing a fluent sentence in real time under pressure is a completely different skill.",
    "I speak with a study partner twice a week, and I record myself answering questions. Recording is uncomfortable but useful, because I hear mistakes I never notice while speaking.",
    "Yes, a spaced-repetition app for vocabulary and a few podcasts. The app works because it schedules reviews just before I would forget, which is far more efficient than rereading a list.",
    "Vaguely. I remember being made to repeat the alphabet aloud and finding the letter combinations completely illogical, which, in fairness, they are.",
    "I would like to learn Turkish. It is close to Uzbek grammatically, so it would be realistic, and I would be able to use it fairly quickly.",
    "Use it before you feel ready. Most beginners wait until they are confident, but confidence comes from having spoken badly many times, not from more preparation.",
  ],
  childhood: [
    "Playing outside, mostly. We were in the courtyard until dark every evening, and I also took apart anything electronic I could get hold of, which my parents tolerated remarkably well.",
    "In Namangan, in a house with a small garden, until we moved to an apartment when I was ten. I still think of the house rather than the flat when I picture home.",
    "My grandfather. He was retired and had time, so he was the one who answered my questions properly instead of telling me to go and play.",
    "Football in the courtyard, and a hiding game we played across the whole block. There was also a game with knucklebones that my grandfather taught me and almost nobody plays now.",
    "Yes, quite clearly. I remember the smell of the corridor and being terrified of the older children, and also my first teacher, who was much kinder than I deserved.",
    "Very different, mainly because of screens. Children have far more information and far more organised activities, but much less unsupervised time outside, and I think that loss is underestimated.",
    "The lack of consequences. Nothing I did at nine mattered very much, and there is a lightness in that which you cannot recreate once you have real responsibilities.",
  ],
  weekends: [
    "Saturday is usually football in the morning and seeing friends later, and Sunday is family, chores and preparation for the week. I try to keep at least one of the two completely unplanned.",
    "It depends on the week. After a heavy week I stay in entirely, but if I do that two weekends in a row I start to feel isolated, so I try to alternate.",
    "Friends, mostly, since my parents are in Namangan. My uncle's family live here, though, and Sunday lunch at their house is not exactly optional.",
    "Completely different, deliberately. I get up two hours later, I do not open my email, and I try not to be anywhere at a fixed time.",
    "Very little, and that was the point. I played football, slept for an hour in the afternoon, and helped my uncle put up a shelf, which took twice as long as it should have.",
    "Sometimes, before a deadline. I try to avoid it, because working every weekend for a month leaves me slower on Monday than if I had rested properly.",
    "Nothing exotic. A run in the morning, unhurried breakfast, a few hours on a project I actually chose, and dinner with people I like, with nothing scheduled after it.",
  ],
};

export const PART1_SAMPLES: Record<string, Part1Samples> = { ...SET_A };
