import type { GrammarLesson } from "./types";

/** A1 — absolute foundations. Every later structure builds on these. */
export const A1_LESSONS: GrammarLesson[] = [
  {
    slug: "to-be",
    level: "A1",
    title: "The verb 'to be'",
    titleUz: "'To be' fe'li (am/is/are)",
    emoji: "🧱",
    explanation: [
      "Ingliz tilidagi ENG MUHIM fe'l — 'to be' (bo'lmoq). O'zbek tilida biz \"Men o'qituvchiman\" deymiz va hech qanday fe'l ishlatmaymiz. Ingliz tilida esa bunday gapda albatta 'to be' kerak: \"I am a teacher\". \"I a teacher\" deyish — eng ko'p uchraydigan xato.",
      "'To be' shaxsga qarab uch shaklga kiradi: I bilan — am, he/she/it bilan — is, you/we/they bilan — are. Bu uchta shaklni avtomatik darajada yodlab oling — ular minglab gaplarning asosi.",
      "Inkor uchun 'not' qo'shiladi: I am not, he is not (isn't), they are not (aren't). Savol uchun 'to be' egadan OLDINGA o'tadi: Are you tired? Is she a doctor?",
    ],
    formula: "I am · he/she/it is · you/we/they are",
    examples: [
      { en: "I am a student at Tashkent university.", uz: "Men Toshkent universitetida talabaman." },
      { en: "She is my older sister.", uz: "U mening opam." },
      { en: "We are from Uzbekistan.", uz: "Biz O'zbekistondanmiz." },
      { en: "It is very hot today.", uz: "Bugun juda issiq." },
      { en: "They are not at home now.", uz: "Ular hozir uyda emas." },
      { en: "Are you ready? — Yes, I am.", uz: "Tayyormisiz? — Ha, tayyorman." },
    ],
    mistakes: [
      { wrong: "I student.", right: "I am a student.", note: "O'zbekchada fe'l kerak emas, inglizchada 'am/is/are' MAJBURIY." },
      { wrong: "He are my friend.", right: "He is my friend.", note: "He/she/it bilan doim 'is' ishlatiladi." },
      { wrong: "You is late.", right: "You are late.", note: "You bilan doim 'are' — hatto bitta odamga aytilsa ham." },
    ],
    quiz: [
      { q: "I ___ from Samarkand.", options: ["am", "is", "are", "be"], answer: 0 },
      { q: "My brother ___ a doctor.", options: ["am", "is", "are", "be"], answer: 1 },
      { q: "___ you hungry?", options: ["Am", "Is", "Are", "Be"], answer: 2 },
      { q: "They ___ not at school today.", options: ["am", "is", "are", "be"], answer: 2 },
      { q: "To'g'ri gapni tanlang:", options: ["I a teacher.", "I am a teacher.", "I is a teacher.", "Am I a teacher"], answer: 1 },
    ],
  },
  {
    slug: "articles",
    level: "A1",
    title: "Articles: a / an / the",
    titleUz: "Artikllar: a / an / the",
    emoji: "🔖",
    explanation: [
      "O'zbek tilida artikl YO'Q, shuning uchun bu mavzu bizga eng qiyinlardan biri. Qoida aslida sodda: birlikdagi sanaladigan ot yolg'iz turolmaydi — oldida a/an yoki the bo'lishi kerak.",
      "'A/an' — noaniq artikl: birinchi marta aytilayotgan yoki \"qandaydir bitta\" narsa haqida. 'A' undosh tovushdan oldin (a book, a university — 'yu' tovushi), 'an' unli tovushdan oldin (an apple, an hour — 'h' o'qilmaydi).",
      "'The' — aniq artikl: suhbatdoshingiz QAYSI narsa haqida gap ketayotganini biladi. Ikkinchi marta tilga olingan narsa, dunyoda yagona narsalar (the sun, the internet) va aniq ko'rsatilgan narsalar bilan ishlatiladi.",
      "Umumiy gaplarda ko'plikdagi otlar artiklsiz yuradi: \"I like apples\" (umuman olma yoqadi), lekin \"I like the apples from our garden\" (aynan bizning bog'dagi olmalar).",
    ],
    formula: "a + undosh tovush · an + unli tovush · the = aniq narsa",
    examples: [
      { en: "I bought a phone yesterday. The phone is very fast.", uz: "Kecha telefon oldim. (O'sha) telefon juda tez." },
      { en: "She is an engineer.", uz: "U muhandis." },
      { en: "The sun rises in the east.", uz: "Quyosh sharqdan chiqadi." },
      { en: "Can you open the window?", uz: "Derazani ochib bera olasizmi? (ikkalamiz ham qaysi deraza ekanini bilamiz)" },
      { en: "I need an umbrella.", uz: "Menga soyabon kerak (qandaydir bittasi)." },
      { en: "Dogs are loyal animals.", uz: "Itlar sodiq hayvonlar. (umuman — artiklsiz)" },
    ],
    mistakes: [
      { wrong: "I am teacher.", right: "I am a teacher.", note: "Kasb aytilganda doim a/an kerak." },
      { wrong: "She has an university degree.", right: "She has a university degree.", note: "'University' 'yu' (undosh) tovushi bilan boshlanadi — 'a' ishlatiladi." },
      { wrong: "The life is beautiful.", right: "Life is beautiful.", note: "Mavhum tushunchalar umumiy ma'noda artiklsiz ishlatiladi." },
    ],
    quiz: [
      { q: "She is ___ engineer.", options: ["a", "an", "the", "—"], answer: 1 },
      { q: "I saw a cat. ___ cat was black.", options: ["A", "An", "The", "—"], answer: 2 },
      { q: "___ moon is bright tonight.", options: ["A", "An", "The", "—"], answer: 2 },
      { q: "I like ___ books. (umuman)", options: ["a", "an", "the", "—"], answer: 3 },
      { q: "He works at ___ university.", options: ["a", "an", "the", "—"], answer: 0 },
    ],
  },
  {
    slug: "plural-nouns",
    level: "A1",
    title: "Plural nouns",
    titleUz: "Otlarning ko'plik shakli",
    emoji: "🔢",
    explanation: [
      "Ko'plik odatda -s bilan yasaladi: book → books, car → cars. Lekin bir nechta muhim istisno guruhlari bor, ularni bilmasdan to'g'ri gapirib bo'lmaydi.",
      "-s/-sh/-ch/-x bilan tugagan so'zlarga -es qo'shiladi: bus → buses, watch → watches. Undoshdan keyingi -y esa -ies ga aylanadi: city → cities (lekin day → days, chunki 'y' oldida unli bor).",
      "Eng ko'p ishlatiladigan NOTO'G'RI ko'pliklar yodlanadi: man → men, woman → women, child → children, person → people, foot → feet, tooth → teeth. \"Childs\" yoki \"peoples\" deyish qo'pol xato.",
    ],
    formula: "+s · -es (s/sh/ch/x) · -y → -ies · istisnolar: men, women, children, people",
    examples: [
      { en: "Two coffees and three cakes, please.", uz: "Ikki kofe va uchta tort, iltimos." },
      { en: "The city has many old buildings.", uz: "Shaharda ko'plab eski binolar bor." },
      { en: "Children learn languages quickly.", uz: "Bolalar tillarni tez o'rganadi." },
      { en: "Most people here are friendly.", uz: "Bu yerdagi ko'pchilik odamlar samimiy." },
      { en: "My feet hurt after the long walk.", uz: "Uzoq yurishdan keyin oyoqlarim og'ridi." },
      { en: "She has two children — a boy and a girl.", uz: "Uning ikki farzandi bor — o'g'il va qiz." },
    ],
    mistakes: [
      { wrong: "Three childs are playing.", right: "Three children are playing.", note: "'Child'ning ko'pligi — children, -s qo'shilmaydi." },
      { wrong: "Many peoples came.", right: "Many people came.", note: "'People' allaqachon ko'plik — yana -s kerak emas." },
      { wrong: "Two citys", right: "Two cities", note: "Undoshdan keyin -y → -ies bo'ladi." },
    ],
    quiz: [
      { q: "'Watch' so'zining ko'pligi:", options: ["watchs", "watches", "watchies", "watch"], answer: 1 },
      { q: "'Woman' so'zining ko'pligi:", options: ["womans", "womens", "women", "womanes"], answer: 2 },
      { q: "'Baby' so'zining ko'pligi:", options: ["babys", "babyes", "babies", "baby"], answer: 2 },
      { q: "To'g'ri variantni tanlang:", options: ["three persons", "three peoples", "three people", "three person"], answer: 2 },
      { q: "'Foot' so'zining ko'pligi:", options: ["foots", "feets", "feet", "footes"], answer: 2 },
    ],
  },
  {
    slug: "pronouns-possessives",
    level: "A1",
    title: "Pronouns & possessives",
    titleUz: "Olmoshlar va egalik shakllari",
    emoji: "👤",
    explanation: [
      "Ingliz tilida olmoshlarning TO'RT qatori bor va ularni aralashtirish gapni butunlay buzadi: I/me/my/mine, he/him/his/his, she/her/her/hers, we/us/our/ours, they/them/their/theirs.",
      "Birinchi ustun (I, he, she...) — ega: kim bajaryapti. Ikkinchi ustun (me, him, her...) — to'ldiruvchi: kimga/kimni. \"Me went home\" emas, \"I went home\"; \"She called I\" emas, \"She called me\".",
      "'My/your/his...' dan keyin DOIM ot keladi: my phone. 'Mine/yours/his...' esa yakka o'zi turadi: This phone is mine. O'zbekcha \"meniki\" — aynan 'mine'.",
      "Diqqat: 'its' (egalik: uning) va 'it's' (= it is) — butunlay boshqa narsalar. Apostrof bor bo'lsa, bu doim \"it is\" qisqartmasi.",
    ],
    formula: "I→me→my→mine · he→him→his→his · she→her→her→hers · they→them→their→theirs",
    examples: [
      { en: "She gave me her book.", uz: "U menga o'z kitobini berdi." },
      { en: "This bag is mine, that one is yours.", uz: "Bu sumka meniki, anavi sizniki." },
      { en: "We invited them to our house.", uz: "Biz ularni uyimizga taklif qildik." },
      { en: "The dog wagged its tail.", uz: "It dumini likillatdi." },
      { en: "Tell him the truth.", uz: "Unga haqiqatni ayting." },
      { en: "Their car is faster than ours.", uz: "Ularning mashinasi biznikidan tezroq." },
    ],
    mistakes: [
      { wrong: "Me and my friend went out.", right: "My friend and I went out.", note: "Ega o'rnida 'me' emas, 'I' ishlatiladi." },
      { wrong: "This is my.", right: "This is mine.", note: "'My'dan keyin ot kerak; yakka holda 'mine' ishlatiladi." },
      { wrong: "The cat licked it's paw.", right: "The cat licked its paw.", note: "'It's' = it is. Egalik uchun apostrofsiz 'its'." },
    ],
    quiz: [
      { q: "Give the keys to ___.", options: ["I", "me", "my", "mine"], answer: 1 },
      { q: "Is this pen ___?", options: ["your", "yours", "you", "yourself"], answer: 1 },
      { q: "___ sister lives in Bukhara.", options: ["Me", "Mine", "My", "I"], answer: 2 },
      { q: "The company changed ___ logo.", options: ["it's", "its", "his", "their"], answer: 1 },
      { q: "We saw ___ at the market.", options: ["they", "their", "them", "theirs"], answer: 2 },
    ],
  },
  {
    slug: "present-simple",
    level: "A1",
    title: "Present Simple",
    titleUz: "Oddiy hozirgi zamon",
    emoji: "☀️",
    explanation: [
      "Present Simple — odatlar, doimiy holatlar va umumiy haqiqatlar zamoni: har kuni qilinadigan ishlar, kasb, yoqtirishlar. \"Men har kuni ishga boraman\", \"U Toshkentda yashaydi\" — bularning bari Present Simple.",
      "OLTIN QOIDA: he/she/it bilan fe'lga -s qo'shiladi: I work → He works. Bu kichkina -s ingliz tilidagi eng ko'p unutiladigan narsa — unga alohida e'tibor bering.",
      "Inkor va savol 'do/does' yordamchisi bilan yasaladi: I don't like tea. Does she work here? Muhim: 'does' kelganda asosiy fe'l -s siz qoladi — does he workS emas, does he work.",
      "Vaqt belgilari: every day, usually, often, sometimes, never, on Mondays.",
    ],
    formula: "I/you/we/they + V · he/she/it + V-s · savol: Do/Does + ega + V?",
    examples: [
      { en: "I drink green tea every morning.", uz: "Men har kuni ertalab ko'k choy ichaman." },
      { en: "My father works at a bank.", uz: "Otam bankda ishlaydi." },
      { en: "She doesn't eat meat.", uz: "U go'sht yemaydi." },
      { en: "Do you speak English?", uz: "Inglizcha gapirasizmi?" },
      { en: "Does the shop open at nine?", uz: "Do'kon to'qqizda ochiladimi?" },
      { en: "Water boils at 100 degrees.", uz: "Suv 100 darajada qaynaydi. (umumiy haqiqat)" },
    ],
    mistakes: [
      { wrong: "He work in a hospital.", right: "He works in a hospital.", note: "He/she/it bilan fe'lga -s qo'shiladi." },
      { wrong: "Does she works here?", right: "Does she work here?", note: "'Does' bo'lganda fe'l -s siz qoladi — -s allaqachon 'does'da." },
      { wrong: "I no like coffee.", right: "I don't like coffee.", note: "Inkor 'don't/doesn't' bilan yasaladi." },
    ],
    quiz: [
      { q: "She ___ to work by bus.", options: ["go", "goes", "going", "gos"], answer: 1 },
      { q: "___ they live in Fergana?", options: ["Does", "Is", "Do", "Are"], answer: 2 },
      { q: "My brother ___ football on Sundays.", options: ["play", "plays", "playing", "is play"], answer: 1 },
      { q: "He ___ like loud music.", options: ["don't", "isn't", "doesn't", "not"], answer: 2 },
      { q: "Does she ___ English?", options: ["speaks", "speak", "speaking", "spoke"], answer: 1 },
    ],
  },
  {
    slug: "present-continuous",
    level: "A1",
    title: "Present Continuous",
    titleUz: "Hozirgi davomli zamon",
    emoji: "🏃",
    explanation: [
      "Present Continuous — AYNI PAYTDA bo'layotgan ish-harakat: \"Men hozir kitob o'qiyapman\". Yasalishi: am/is/are + fe'l-ing. Ikkala qism ham majburiy!",
      "Present Simple bilan farqi: \"I read books\" (umuman, odat) vs \"I am reading a book\" (hozir, shu daqiqada). O'zbekchada bu farq \"o'qiyman\" va \"o'qiyapman\" orqali beriladi — juda o'xshash!",
      "Yaqin kelajakdagi aniq rejalar uchun ham ishlatiladi: \"I am meeting Aziz tomorrow\" (ertaga Aziz bilan uchrashyapman — kelishilgan).",
      "Ba'zi fe'llar -ing shaklida ishlatilmaydi (holat fe'llari): know, like, love, want, need, understand. \"I am knowing\" emas, doim \"I know\".",
    ],
    formula: "am/is/are + V-ing",
    examples: [
      { en: "I am writing an essay right now.", uz: "Men hozir insho yozyapman." },
      { en: "She is cooking plov for dinner.", uz: "U kechki ovqatga palov pishiryapti." },
      { en: "They are waiting for the bus.", uz: "Ular avtobus kutishyapti." },
      { en: "Why are you laughing?", uz: "Nega kulyapsiz?" },
      { en: "We are flying to Istanbul on Friday.", uz: "Biz juma kuni Istanbulga uchyapmiz. (reja)" },
      { en: "It isn't raining anymore.", uz: "Endi yomg'ir yog'mayapti." },
    ],
    mistakes: [
      { wrong: "I working now.", right: "I am working now.", note: "'To be' (am/is/are) tushirib qoldirilmaydi." },
      { wrong: "She is cook dinner.", right: "She is cooking dinner.", note: "Fe'lga -ing qo'shilishi shart." },
      { wrong: "I am wanting a new phone.", right: "I want a new phone.", note: "'Want' holat fe'li — continuous'da ishlatilmaydi." },
    ],
    quiz: [
      { q: "Listen! Someone ___ the piano.", options: ["plays", "is playing", "play", "played"], answer: 1 },
      { q: "I ___ for my keys. Have you seen them?", options: ["look", "am looking", "looks", "looking"], answer: 1 },
      { q: "They ___ TV at the moment.", options: ["is watching", "watch", "are watching", "watches"], answer: 2 },
      { q: "Qaysi gap XATO?", options: ["I am reading now.", "She is sleeping.", "I am knowing him.", "We are studying."], answer: 2 },
      { q: "What ___ you doing?", options: ["is", "are", "do", "does"], answer: 1 },
    ],
  },
  {
    slug: "there-is-are",
    level: "A1",
    title: "There is / There are",
    titleUz: "There is / There are (bor/mavjud)",
    emoji: "📍",
    explanation: [
      "Biror joyda nimadir BORLIGINI aytish uchun ingliz tili 'there is/are' qurilmasini ishlatadi. O'zbekcha \"Xonada stol bor\" — \"There is a table in the room\".",
      "Birlik bilan 'there is', ko'plik bilan 'there are': There is a mosque near my house. There are two universities in this city.",
      "Inkor: There isn't / There aren't. Savol: Is there...? / Are there...? Javob: Yes, there is. / No, there aren't.",
      "'It is' bilan adashtirmaslik kerak: 'There is a book' — kitob borligi haqida; 'It is a book' — bu narsa kitob ekani haqida.",
    ],
    formula: "There is + birlik · There are + ko'plik",
    examples: [
      { en: "There is a park near our school.", uz: "Maktabimiz yonida bog' bor." },
      { en: "There are many cafés on this street.", uz: "Bu ko'chada ko'p kafelar bor." },
      { en: "There isn't any milk in the fridge.", uz: "Muzlatkichda sut yo'q." },
      { en: "Are there any questions?", uz: "Savollar bormi?" },
      { en: "There is someone at the door.", uz: "Eshik oldida kimdir bor." },
      { en: "There are 12 months in a year.", uz: "Bir yilda 12 oy bor." },
    ],
    mistakes: [
      { wrong: "In my city is a big bazaar.", right: "There is a big bazaar in my city.", note: "\"Bor\" ma'nosi uchun gap 'there is' bilan boshlanadi." },
      { wrong: "There is many people here.", right: "There are many people here.", note: "'People' ko'plik — 'there are' kerak." },
      { wrong: "Have a problem.", right: "There is a problem.", note: "\"Muammo bor\" = There is a problem ('have' emas)." },
    ],
    quiz: [
      { q: "___ a big park in the city centre.", options: ["There is", "There are", "It is", "Is"], answer: 0 },
      { q: "___ any good restaurants nearby?", options: ["Is there", "Are there", "There are", "There is"], answer: 1 },
      { q: "There ___ five students in the classroom.", options: ["is", "are", "be", "am"], answer: 1 },
      { q: "There ___ any sugar left.", options: ["isn't", "aren't", "is", "not"], answer: 0 },
      { q: "\"Stolda ikkita kitob bor\" — to'g'ri tarjima:", options: ["On the table is two books.", "There are two books on the table.", "There is two books on the table.", "Two books is on the table."], answer: 1 },
    ],
  },
  {
    slug: "can-cant",
    level: "A1",
    title: "Can / Can't",
    titleUz: "Can / Can't (qila olmoq)",
    emoji: "💪",
    explanation: [
      "'Can' — qobiliyat (\"qila olaman\"), ruxsat (\"mumkinmi\") va iltimos uchun ishlatiladigan modal fe'l. Modal fe'llarning qulayligi: hamma shaxs uchun BIR XIL shakl — he can, I can, they can. Hech qanday -s yo'q!",
      "'Can'dan keyin fe'l doim asl shaklda ('to'siz infinitiv): can swim, can speak. \"Can to swim\" yoki \"can swimming\" — xato.",
      "Inkor: can't (cannot). Savol: Can + ega + fe'l? — Can you help me? Javob: Yes, I can / No, I can't.",
    ],
    formula: "ega + can/can't + V (asl shakl)",
    examples: [
      { en: "I can drive a car.", uz: "Men mashina hayday olaman." },
      { en: "She can speak three languages.", uz: "U uch tilda gapira oladi." },
      { en: "We can't come to the party tonight.", uz: "Biz bugun kechqurun bazmga kela olmaymiz." },
      { en: "Can I open the window?", uz: "Derazani ochsam mumkinmi?" },
      { en: "Can you pass the salt, please?", uz: "Tuzni uzatib yubora olasizmi, iltimos?" },
      { en: "My grandfather can't use a smartphone.", uz: "Bobom smartfondan foydalana olmaydi." },
    ],
    mistakes: [
      { wrong: "He cans swim.", right: "He can swim.", note: "Modal fe'llarga -s qo'shilmaydi." },
      { wrong: "I can to help you.", right: "I can help you.", note: "'Can'dan keyin 'to' ishlatilmaydi." },
      { wrong: "Do you can drive?", right: "Can you drive?", note: "'Can' o'z savolini o'zi yasaydi — 'do' kerak emas." },
    ],
    quiz: [
      { q: "She ___ play the dutar very well.", options: ["cans", "can", "can to", "is can"], answer: 1 },
      { q: "___ you help me with this bag?", options: ["Do can", "Can", "Are", "Does"], answer: 1 },
      { q: "I ___ find my glasses anywhere.", options: ["can", "can't", "no can", "don't can"], answer: 1 },
      { q: "He can ___ English fluently.", options: ["speaks", "speaking", "speak", "to speak"], answer: 2 },
      { q: "Qaysi gap TO'G'RI?", options: ["He cans cook.", "He can cooks.", "He can cook.", "He can to cook."], answer: 2 },
    ],
  },
  {
    slug: "prepositions-time-place",
    level: "A1",
    title: "Prepositions: in / on / at",
    titleUz: "Predloglar: in / on / at",
    emoji: "🧭",
    explanation: [
      "In/on/at — vaqt va joy uchun eng muhim uchta predlog. Ularning mantig'i: IN — katta narsaning ichida, ON — yuzada/ustida, AT — aniq nuqtada.",
      "VAQT: in — oylar, yillar, fasllar (in May, in 2025, in winter); on — kunlar va sanalar (on Monday, on 12 March); at — soatlar va ba'zi iboralar (at 7 o'clock, at night, at the weekend).",
      "JOY: in — shahar, mamlakat, xona ichida (in Tashkent, in the kitchen); on — yuzada, ko'chada, qavatda (on the table, on the second floor); at — aniq nuqta yoki muassasa (at home, at school, at the bus stop).",
      "Yodda tuting: in the morning/afternoon/evening, LEKIN at night — bu istisno ko'p so'raladi.",
    ],
    formula: "in = ichida/katta davr · on = ustida/kun · at = nuqta/soat",
    examples: [
      { en: "My birthday is in September.", uz: "Tug'ilgan kunim sentyabrda." },
      { en: "The lesson starts at 9 o'clock on Monday.", uz: "Dars dushanba kuni soat 9 da boshlanadi." },
      { en: "She lives in Namangan.", uz: "U Namanganda yashaydi." },
      { en: "Your keys are on the table.", uz: "Kalitlaringiz stol ustida." },
      { en: "I'll meet you at the metro station.", uz: "Siz bilan metro bekatida uchrashaman." },
      { en: "We usually relax at the weekend.", uz: "Biz odatda dam olish kunlari hordiq chiqaramiz." },
    ],
    mistakes: [
      { wrong: "I was born on 1998.", right: "I was born in 1998.", note: "Yillar bilan 'in' ishlatiladi." },
      { wrong: "See you in Monday.", right: "See you on Monday.", note: "Hafta kunlari bilan 'on'." },
      { wrong: "He is on home.", right: "He is at home.", note: "'Home' bilan 'at' — turg'un ibora." },
    ],
    quiz: [
      { q: "The meeting is ___ Friday.", options: ["in", "on", "at", "to"], answer: 1 },
      { q: "I wake up ___ 6 o'clock.", options: ["in", "on", "at", "by"], answer: 2 },
      { q: "They live ___ Bukhara.", options: ["in", "on", "at", "of"], answer: 0 },
      { q: "The picture is ___ the wall.", options: ["in", "on", "at", "under"], answer: 1 },
      { q: "I can't sleep ___ night.", options: ["in", "on", "at", "the"], answer: 2 },
    ],
  },
  {
    slug: "questions-word-order",
    level: "A1",
    title: "Questions & word order",
    titleUz: "Savollar va so'z tartibi",
    emoji: "❓",
    explanation: [
      "Ingliz gapida so'z tartibi QAT'IY: Ega + Fe'l + To'ldiruvchi. O'zbekchada erkin tartib mumkin (\"Kitobni men o'qidim\"), inglizchada esa \"I read the book\" — faqat shu tartib.",
      "Savol so'zlari: What (nima), Where (qayerda), When (qachon), Who (kim), Why (nega), How (qanday), How many/much (nechta/qancha).",
      "Savol formulasi: Savol so'zi + yordamchi (do/does/is/are/can) + ega + fe'l: Where do you live? What is she doing? Yordamchini tushirib qoldirish — klassik xato: \"Where you live?\" noto'g'ri.",
      "'Who' ega bo'lganda yordamchisiz ham bo'ladi: Who lives here? (kim yashaydi — 'who'ning o'zi ega).",
    ],
    formula: "Savol so'zi + do/does/is/are + ega + fe'l?",
    examples: [
      { en: "Where do you work?", uz: "Qayerda ishlaysiz?" },
      { en: "What time does the train leave?", uz: "Poyezd soat nechada jo'naydi?" },
      { en: "Why are you sad?", uz: "Nega xafasiz?" },
      { en: "How many brothers do you have?", uz: "Nechta akangiz/ukangiz bor?" },
      { en: "Who is that man?", uz: "Anavi kishi kim?" },
      { en: "How do I get to the airport?", uz: "Aeroportga qanday boraman?" },
    ],
    mistakes: [
      { wrong: "Where you live?", right: "Where do you live?", note: "Savolda yordamchi fe'l (do/does) majburiy." },
      { wrong: "What she is doing?", right: "What is she doing?", note: "Yordamchi fe'l egadan OLDIN keladi." },
      { wrong: "I very much like plov.", right: "I like plov very much.", note: "'Very much' gap oxiriga qo'yiladi." },
    ],
    quiz: [
      { q: "___ does she get up early?", options: ["What", "Why", "Who", "Where"], answer: 1 },
      { q: "Where ___ your parents live?", options: ["does", "are", "do", "is"], answer: 2 },
      { q: "To'g'ri savolni tanlang:", options: ["What you want?", "What do you want?", "What want you?", "What you do want?"], answer: 1 },
      { q: "How ___ sugar do you take?", options: ["many", "much", "often", "any"], answer: 1 },
      { q: "___ wrote this letter? (kim yozdi?)", options: ["Who did", "Who does", "Who", "Whom"], answer: 2 },
    ],
  },
];
