import type { GrammarLesson } from "./types";

/** B1 — the intermediate core: perfect vs past, passive, reported speech. */
export const B1_LESSONS: GrammarLesson[] = [
  {
    slug: "present-perfect-vs-past",
    level: "B1",
    title: "Present Perfect vs Past Simple",
    titleUz: "Present Perfect va Past Simple farqi",
    emoji: "⚔️",
    explanation: [
      "Bu ikki zamonni farqlash — B1 darajasining eng katta sinovi. Qoida bitta savolga qaytadi: VAQT ANIQMI?",
      "Aniq o'tgan vaqt bor (yesterday, in 2020, two hours ago, when I was young) → Past Simple. Vaqt aytilmagan yoki davr hali tugamagan (today, this week, ever, never, since, for) → Present Perfect.",
      "'For' va 'since' farqi: for + davomiylik (for five years — besh yildan beri), since + boshlanish nuqtasi (since 2019 — 2019-yildan beri).",
      "Taqqoslang: \"I have worked here for three years\" (hozir ham ishlayapman) vs \"I worked there for three years\" (endi ishlamayman — tugagan).",
    ],
    formula: "aniq vaqt → Past Simple · vaqtsiz/davom etayotgan → Present Perfect",
    examples: [
      { en: "I have lived in Tashkent since 2018.", uz: "Men 2018-yildan beri Toshkentda yashayman. (hozir ham)" },
      { en: "I lived in Andijan for two years.", uz: "Men Andijonda ikki yil yashaganman. (tugagan)" },
      { en: "Have you finished the report? — Yes, I finished it an hour ago.", uz: "Hisobotni tugatdingizmi? — Ha, bir soat oldin tugatdim." },
      { en: "She has written three books so far.", uz: "U hozirgacha uchta kitob yozgan." },
      { en: "We visited Khiva last spring.", uz: "Biz o'tgan bahorda Xivaga borganmiz." },
      { en: "He has been ill since Monday.", uz: "U dushanbadan beri kasal." },
    ],
    mistakes: [
      { wrong: "I have graduated in 2021.", right: "I graduated in 2021.", note: "Aniq yil ko'rsatilgan — Past Simple." },
      { wrong: "I live here since 2020.", right: "I have lived here since 2020.", note: "'Since' bilan Present Perfect ishlatiladi (Present Simple emas)." },
      { wrong: "She works here for ten years.", right: "She has worked here for ten years.", note: "Hozirgacha davom etayotgan davr — Present Perfect." },
    ],
    quiz: [
      { q: "We ___ in this house since 2015.", options: ["live", "lived", "have lived", "living"], answer: 2 },
      { q: "They ___ the match two days ago.", options: ["have won", "won", "win", "has won"], answer: 1 },
      { q: "I've known him ___ ten years.", options: ["since", "for", "from", "ago"], answer: 1 },
      { q: "___ you ever ___ Bukhara?", options: ["Did / visit", "Have / visited", "Do / visit", "Had / visit"], answer: 1 },
      { q: "She ___ her keys — she can't get in.", options: ["lost", "has lost", "loses", "losing"], answer: 1 },
    ],
  },
  {
    slug: "past-continuous",
    level: "B1",
    title: "Past Continuous",
    titleUz: "O'tgan davomli zamon",
    emoji: "🎬",
    explanation: [
      "Past Continuous (was/were + V-ing) — o'tmishdagi muayyan paytda DAVOM ETAYOTGAN ish: \"At 8 pm I was having dinner\" (soat 8da ovqatlanayotgan edim).",
      "Eng kuchli ishlatilishi — 'kadr ichida kadr': uzun ish davom etayotganda qisqa ish sodir bo'ladi. Uzun ish — Past Continuous, qisqa ish — Past Simple: \"I was walking home when it started to rain\".",
      "'When' va 'while' farqi: while + davomli ish (While I was cooking...), when + qisqa voqea (...when the phone rang).",
      "Hikoya boshida fon yaratish uchun ham ishlatiladi: \"The sun was shining, birds were singing...\"",
    ],
    formula: "was/were + V-ing · uzun ish (Continuous) + when + qisqa ish (Simple)",
    examples: [
      { en: "I was sleeping when you called.", uz: "Siz qo'ng'iroq qilganingizda uxlayotgan edim." },
      { en: "While she was studying, her brother was playing games.", uz: "U o'qiyotganda, ukasi o'yin o'ynayotgan edi." },
      { en: "What were you doing at 10 pm yesterday?", uz: "Kecha soat 22 da nima qilayotgan edingiz?" },
      { en: "They were living in Nukus when their son was born.", uz: "O'g'illari tug'ilganda ular Nukusda yashashayotgan edi." },
      { en: "He cut his finger while he was cooking.", uz: "U ovqat pishirayotib barmog'ini kesib oldi." },
      { en: "It was raining all morning.", uz: "Ertalab davomida yomg'ir yog'ayotgan edi." },
    ],
    mistakes: [
      { wrong: "When you called, I slept.", right: "When you called, I was sleeping.", note: "Davom etayotgan ish — Past Continuous." },
      { wrong: "While I was cook dinner...", right: "While I was cooking dinner...", note: "-ing tushirib qoldirilmaydi." },
      { wrong: "I was knowing the answer.", right: "I knew the answer.", note: "Holat fe'llari (know, want, like) continuous'da ishlatilmaydi." },
    ],
    quiz: [
      { q: "I ___ TV when the lights went out.", options: ["watched", "was watching", "am watching", "watch"], answer: 1 },
      { q: "While he ___ to work, he saw an accident.", options: ["drove", "was driving", "is driving", "drives"], answer: 1 },
      { q: "What ___ you ___ at midnight?", options: ["did / do", "were / doing", "was / doing", "have / done"], answer: 1 },
      { q: "She ___ her leg while she was skiing.", options: ["was breaking", "broke", "breaks", "has broken"], answer: 1 },
      { q: "They ___ football all afternoon.", options: ["was playing", "were playing", "played were", "playing"], answer: 1 },
    ],
  },
  {
    slug: "used-to",
    level: "B1",
    title: "Used to",
    titleUz: "Used to (ilgari ... bo'lardi)",
    emoji: "📼",
    explanation: [
      "'Used to + fe'l' — o'tmishdagi odat yoki holat HOZIR YO'Q ekanini bildiradi: \"I used to smoke\" (ilgari chekardim, endi chekmayman). O'zbekcha \"...rdi\" qo'shimchasiga juda mos: yashardim, o'ynardim.",
      "Inkor va savolda 'use to' (d-siz!): I didn't use to like tea. Did you use to play football?",
      "Adashtirmang: 'be used to + -ing' = ko'nikkan (I am used to getting up early — erta turishga o'rganganman) va 'get used to + -ing' = ko'nikmoq. Bular butunlay boshqa qurilmalar!",
    ],
    formula: "used to + V (o'tgan odat) · be/get used to + V-ing (ko'nikish)",
    examples: [
      { en: "I used to live in a village.", uz: "Ilgari qishloqda yashardim." },
      { en: "She used to have long hair.", uz: "Uning sochlari ilgari uzun edi." },
      { en: "Did you use to play games as a child?", uz: "Bolaligingizda o'yin o'ynarmidingiz?" },
      { en: "We didn't use to have a car.", uz: "Ilgari mashinamiz yo'q edi." },
      { en: "He is used to working at night.", uz: "U tunda ishlashga o'rgangan." },
      { en: "You will get used to the new schedule.", uz: "Yangi jadvalga ko'nikib ketasiz." },
    ],
    mistakes: [
      { wrong: "I use to play football. (o'tmish)", right: "I used to play football.", note: "O'tgan odat — 'used to' (d bilan)." },
      { wrong: "Did you used to live here?", right: "Did you use to live here?", note: "'Did' bilan 'use to' (d-siz) ishlatiladi." },
      { wrong: "I am used to get up early.", right: "I am used to getting up early.", note: "'Be used to'dan keyin V-ing keladi." },
    ],
    quiz: [
      { q: "There ___ be a cinema here.", options: ["used to", "use to", "is used to", "used"], answer: 0 },
      { q: "___ you ___ to wear glasses?", options: ["Did / used", "Did / use", "Do / use", "Were / used"], answer: 1 },
      { q: "She is used ___ in a big city.", options: ["to live", "to living", "living", "live"], answer: 1 },
      { q: "I ___ like coffee, but now I love it.", options: ["didn't use to", "didn't used to", "don't use to", "am not used to"], answer: 0 },
      { q: "\"Ilgari bu yerda daraxt bor edi\":", options: ["A tree is used to be here.", "There used to be a tree here.", "There was used to a tree.", "A tree used to being here."], answer: 1 },
    ],
  },
  {
    slug: "second-conditional",
    level: "B1",
    title: "Second Conditional",
    titleUz: "2-shart gapi (xayoliy hozirgi)",
    emoji: "💭",
    explanation: [
      "Second Conditional — HOZIRGI xayoliy vaziyatlar: \"Agar millioner bo'lganimda...\" (lekin emasman). Formula: If + Past Simple, would + fe'l.",
      "Past Simple bu yerda o'tmishni EMAS, xayoliylikni bildiradi: \"If I had wings, I would fly\" — hozir haqida, lekin real emas.",
      "'To be' bilan barcha shaxslarda 'were' afzal: If I were you, I would apologize (agar sizning o'rningizda bo'lganimda) — bu ibora maslahat berishning eng chiroyli yo'li.",
      "First bilan farqi: If I have time, I will help (real imkoniyat) vs If I had time, I would help (hozir vaqtim yo'q — xayoliy).",
    ],
    formula: "If + Past Simple, would + V",
    examples: [
      { en: "If I won the lottery, I would buy a house by the sea.", uz: "Lotereyada yutsam, dengiz bo'yidan uy olardim." },
      { en: "If I were you, I would accept the offer.", uz: "Sizning o'rningizda bo'lsam, taklifni qabul qilardim." },
      { en: "She would travel more if she had more money.", uz: "Puli ko'proq bo'lganida u ko'proq sayohat qilardi." },
      { en: "What would you do if you lost your phone?", uz: "Telefoningizni yo'qotib qo'ysangiz nima qilardingiz?" },
      { en: "If people didn't use plastic, the oceans would be cleaner.", uz: "Odamlar plastik ishlatmaganida okeanlar tozaroq bo'lardi." },
      { en: "I wouldn't say that if I didn't believe it.", uz: "Ishonmaganimda buni aytmasdim." },
    ],
    mistakes: [
      { wrong: "If I would have money, I would travel.", right: "If I had money, I would travel.", note: "'If' qismida 'would' ishlatilmaydi — Past Simple." },
      { wrong: "If I was you...", right: "If I were you...", note: "Shart gapida barcha shaxslar bilan 'were' afzal (ayniqsa imtihonda)." },
      { wrong: "If she studied, she will pass. (xayoliy)", right: "If she studied, she would pass.", note: "Second Conditional'da asosiy qism 'would' bilan." },
    ],
    quiz: [
      { q: "If I ___ rich, I would help the poor.", options: ["am", "were", "will be", "would be"], answer: 1 },
      { q: "If he had a car, he ___ to work.", options: ["will drive", "drives", "would drive", "drove"], answer: 2 },
      { q: "What ___ you do if you saw a snake?", options: ["will", "do", "did", "would"], answer: 3 },
      { q: "If we ___ in London, we would speak English every day.", options: ["live", "lived", "would live", "living"], answer: 1 },
      { q: "'Sizning o'rningizda bo'lsam' inglizchasi:", options: ["If I am you", "If I be you", "If I were you", "If I would be you"], answer: 2 },
    ],
  },
  {
    slug: "passive-voice",
    level: "B1",
    title: "Passive Voice",
    titleUz: "Majhul nisbat",
    emoji: "🏭",
    explanation: [
      "Passiv — ish-harakat KIMGA/NIMAGA qilingani muhim bo'lganda, bajaruvchi esa noma'lum yoki ahamiyatsiz bo'lganda ishlatiladi: \"This mosque was built in the 15th century\" (kim qurgani emas, qachon qurilgani muhim).",
      "Formula: to be (kerakli zamonda) + V3. Present: is/are made. Past: was/were built. Future: will be finished. Present Perfect: has/have been sold.",
      "Bajaruvchini aytish kerak bo'lsa 'by' ishlatiladi: The novel was written by Abdulla Qodiriy.",
      "IELTS Writing'da passiv juda qadrlanadi — jarayonlarni tasvirlashda (Task 1) deyarli majburiy: \"The cocoa beans are dried and then transported...\"",
    ],
    formula: "to be (zamonga mos) + V3 · bajaruvchi: by + kim",
    examples: [
      { en: "Rice is grown in many regions of Uzbekistan.", uz: "Sholi O'zbekistonning ko'p hududlarida yetishtiriladi." },
      { en: "The Registan was built centuries ago.", uz: "Registon asrlar oldin qurilgan." },
      { en: "My phone was stolen on the bus.", uz: "Telefonim avtobusda o'g'irlandi." },
      { en: "The results will be announced tomorrow.", uz: "Natijalar ertaga e'lon qilinadi." },
      { en: "This song has been played millions of times.", uz: "Bu qo'shiq millionlab marta ijro etilgan." },
      { en: "English is spoken all over the world.", uz: "Ingliz tilida butun dunyoda gaplashiladi." },
    ],
    mistakes: [
      { wrong: "The letter was wrote yesterday.", right: "The letter was written yesterday.", note: "Passivda fe'lning 3-shakli (V3) ishlatiladi." },
      { wrong: "The house building in 1990.", right: "The house was built in 1990.", note: "'To be' tushirib qoldirilmaydi." },
      { wrong: "The cake made by my mother.", right: "The cake was made by my mother.", note: "'Was/were'siz passiv bo'lmaydi." },
    ],
    quiz: [
      { q: "This bridge ___ in 1985.", options: ["built", "was built", "is build", "was build"], answer: 1 },
      { q: "Cotton ___ in Fergana Valley.", options: ["grows", "is grown", "is growing", "grown"], answer: 1 },
      { q: "The winners ___ next week.", options: ["will announce", "will be announced", "are announcing", "announced"], answer: 1 },
      { q: "'Hamlet' ___ by Shakespeare.", options: ["wrote", "was written", "was wrote", "is writing"], answer: 1 },
      { q: "The room ___ every day.", options: ["cleans", "is cleaned", "cleaned", "is cleaning"], answer: 1 },
    ],
  },
  {
    slug: "reported-speech",
    level: "B1",
    title: "Reported Speech",
    titleUz: "O'zlashtirma gap",
    emoji: "🗣️",
    explanation: [
      "Birovning gapini yetkazganda zamonlar BIR QADAM ORQAGA suriladi: \"I am tired\" → He said (that) he was tired. Present → Past, Past → Past Perfect, will → would, can → could.",
      "Olmoshlar ham moslashadi: \"I like your idea\" → She said she liked my idea.",
      "Vaqt so'zlari o'zgaradi: today → that day, tomorrow → the next day, yesterday → the day before, here → there.",
      "'Say' va 'tell' farqi: say + gap (He said that...), tell + KIMGA + gap (He told me that...). \"He said me\" — xato, \"He told to me\" ham xato.",
    ],
    formula: "zamon bir qadam orqaga · said (that) · told + kimga",
    examples: [
      { en: "\"I work in a bank.\" → He said he worked in a bank.", uz: "U bankda ishlashini aytdi." },
      { en: "\"We will come tomorrow.\" → They said they would come the next day.", uz: "Ular ertasi kuni kelishlarini aytishdi." },
      { en: "\"I have finished.\" → She told me she had finished.", uz: "U menga tugatganini aytdi." },
      { en: "\"I can help you.\" → He said he could help me.", uz: "U menga yordam bera olishini aytdi." },
      { en: "She told us she was leaving.", uz: "U bizga ketayotganini aytdi." },
      { en: "He asked where I lived.", uz: "U qayerda yashashimni so'radi. (savolda tartib oddiy gap kabi)" },
    ],
    mistakes: [
      { wrong: "He said me that he was busy.", right: "He told me that he was busy.", note: "KIMGA aytilgani bilan — 'tell' ishlatiladi." },
      { wrong: "She said she is tired.", right: "She said she was tired.", note: "Zamon orqaga suriladi: is → was." },
      { wrong: "He asked where do I live.", right: "He asked where I lived.", note: "O'zlashtirma savolda oddiy gap tartibi — 'do' yo'q." },
    ],
    quiz: [
      { q: "\"I am happy.\" → She said she ___ happy.", options: ["is", "was", "were", "be"], answer: 1 },
      { q: "\"We will win.\" → They said they ___ win.", options: ["will", "would", "can", "won"], answer: 1 },
      { q: "He ___ me that he had a new job.", options: ["said", "told", "said to", "spoke"], answer: 1 },
      { q: "\"I can swim.\" → He said he ___ swim.", options: ["can", "could", "would", "may"], answer: 1 },
      { q: "She asked where ___.", options: ["do I work", "I worked", "did I work", "I am working"], answer: 1 },
    ],
  },
  {
    slug: "relative-clauses",
    level: "B1",
    title: "Relative clauses",
    titleUz: "Aniqlovchi ergash gaplar",
    emoji: "🧩",
    explanation: [
      "Relative clauses ikkita gapni bitta chiroyli gapga birlashtiradi: \"The man lives next door. He is a doctor.\" → \"The man who lives next door is a doctor.\"",
      "Bog'lovchilar: who — odamlar, which — narsalar/hayvonlar, that — ikkalasi ham (norasmiyroq), where — joy, whose — kimning.",
      "To'ldiruvchi o'rnidagi who/which/that tushirilishi mumkin: \"The book (that) I read was great\". Lekin ega o'rnida tushirilmaydi: \"The man who called...\" — 'who' majburiy.",
      "IELTS uchun muhim: aniqlovchi gaplar Writing'da gap murakkabligini ko'rsatadi va bandni oshiradi.",
    ],
    formula: "who (odam) · which (narsa) · that (ikkalasi) · where (joy) · whose (kimning)",
    examples: [
      { en: "The woman who teaches us English is from Canada.", uz: "Bizga ingliz tilidan dars beradigan ayol Kanadadan." },
      { en: "This is the photo which won the prize.", uz: "Mana mukofot yutgan surat." },
      { en: "The plov (that) my mother makes is the best.", uz: "Onam pishiradigan palov eng zo'ri." },
      { en: "That's the café where we first met.", uz: "Mana biz birinchi marta uchrashgan kafe." },
      { en: "I have a friend whose father is a pilot.", uz: "Otasi uchuvchi bo'lgan do'stim bor." },
      { en: "People who exercise regularly live longer.", uz: "Muntazam shug'ullanadigan odamlar uzoqroq yashaydi." },
    ],
    mistakes: [
      { wrong: "The man which lives here...", right: "The man who lives here...", note: "Odamlar bilan 'who' (yoki 'that'), 'which' emas." },
      { wrong: "The book who I read...", right: "The book which/that I read...", note: "Narsalar bilan 'which/that'." },
      { wrong: "The city which I was born...", right: "The city where I was born...", note: "Joy ma'nosida 'where' ishlatiladi." },
    ],
    quiz: [
      { q: "The doctor ___ treated me was very kind.", options: ["which", "who", "where", "whose"], answer: 1 },
      { q: "The film ___ we watched was boring.", options: ["who", "where", "which", "whose"], answer: 2 },
      { q: "That's the school ___ I studied.", options: ["which", "who", "where", "that"], answer: 2 },
      { q: "The boy ___ bike was stolen is crying.", options: ["who", "which", "that", "whose"], answer: 3 },
      { q: "Qaysi gapda bog'lovchini TUSHIRISH mumkin?", options: ["The man who called you...", "The car that hit him...", "The book that I bought...", "People who smoke..."], answer: 2 },
    ],
  },
  {
    slug: "gerund-infinitive",
    level: "B1",
    title: "Gerund vs Infinitive",
    titleUz: "Gerund va infinitiv (V-ing yoki to V)",
    emoji: "🔀",
    explanation: [
      "Fe'ldan keyin ikkinchi fe'l qaysi shaklda kelishi — inglizchaning \"yodlanadigan\" qismi. Ba'zi fe'llar V-ing talab qiladi, ba'zilari to V.",
      "V-ing (gerund) keladi: enjoy, finish, mind, avoid, suggest, keep, practise + predloglardan keyin doim (interested in learning, good at cooking).",
      "To V (infinitiv) keladi: want, need, decide, hope, plan, promise, agree, learn, would like.",
      "Ikkalasi ham mumkin, LEKIN ma'no o'zgaradi: stop smoking (chekishni tashlash) vs stop to smoke (chekish uchun to'xtash); remember doing (qilganini eslash) vs remember to do (qilishni unutmaslik).",
    ],
    formula: "enjoy/finish/avoid + V-ing · want/decide/hope + to V · predlog + V-ing",
    examples: [
      { en: "I enjoy reading before bed.", uz: "Uxlashdan oldin kitob o'qishni yoqtiraman." },
      { en: "She decided to change her job.", uz: "U ishini o'zgartirishga qaror qildi." },
      { en: "He avoided answering my question.", uz: "U savolimga javob berishdan qochdi." },
      { en: "We hope to see you soon.", uz: "Tez orada ko'rishishga umid qilamiz." },
      { en: "I'm interested in learning Arabic.", uz: "Arab tilini o'rganishga qiziqaman." },
      { en: "Remember to lock the door!", uz: "Eshikni qulflashni unutmang!" },
    ],
    mistakes: [
      { wrong: "I enjoy to swim.", right: "I enjoy swimming.", note: "'Enjoy'dan keyin doim V-ing." },
      { wrong: "She wants going home.", right: "She wants to go home.", note: "'Want'dan keyin doim to V." },
      { wrong: "I'm good at cook.", right: "I'm good at cooking.", note: "Predlogdan keyin fe'l doim V-ing shaklida." },
    ],
    quiz: [
      { q: "I enjoy ___ football.", options: ["play", "to play", "playing", "played"], answer: 2 },
      { q: "They decided ___ a taxi.", options: ["taking", "to take", "take", "took"], answer: 1 },
      { q: "She is afraid of ___ alone.", options: ["fly", "to fly", "flying", "flies"], answer: 2 },
      { q: "Please stop ___ so much noise!", options: ["to make", "making", "make", "made"], answer: 1 },
      { q: "He promised ___ me with the project.", options: ["helping", "help", "to help", "helped"], answer: 2 },
    ],
  },
  {
    slug: "modals-deduction",
    level: "B1",
    title: "Modals of deduction",
    titleUz: "Taxmin modallari: must / might / can't",
    emoji: "🕵️",
    explanation: [
      "Dalillarga qarab xulosa chiqarish uchun modallar ishlatiladi — ishonch darajasiga qarab tanlanadi.",
      "'Must' — deyarli aniq HA (90%+): \"He must be at work — his car isn't here\" (ishda bo'lsa kerak). Diqqat: bu majburiyat emas, mantiqiy xulosa!",
      "'Might / may / could' — ehtimol (50%): \"She might be sleeping\" (uxlayotgan bo'lishi mumkin).",
      "'Can't' — deyarli aniq YO'Q: \"That can't be true!\" (bunday bo'lishi mumkin emas). Taxminda 'mustn't' ISHLATILMAYDI — faqat can't.",
    ],
    formula: "must be (aniq ha) · might be (ehtimol) · can't be (aniq yo'q)",
    examples: [
      { en: "The lights are on — they must be at home.", uz: "Chiroqlar yoniq — ular uyda bo'lsa kerak." },
      { en: "He might come later, I'm not sure.", uz: "U keyinroq kelishi mumkin, aniq bilmayman." },
      { en: "You've been working all day — you must be tired.", uz: "Kun bo'yi ishladingiz — charchagan bo'lsangiz kerak." },
      { en: "This bill can't be right — it's too high!", uz: "Bu hisob to'g'ri bo'lishi mumkin emas — juda katta!" },
      { en: "She may be stuck in traffic.", uz: "U tirbandlikda qolib ketgan bo'lishi mumkin." },
      { en: "It could be a mistake.", uz: "Bu xato bo'lishi mumkin." },
    ],
    mistakes: [
      { wrong: "He mustn't be at home. (taxmin)", right: "He can't be at home.", note: "Taxminda inkor 'can't' bilan — 'mustn't' taqiq uchun." },
      { wrong: "She must to be tired.", right: "She must be tired.", note: "Modaldan keyin 'to' yo'q." },
      { wrong: "It can be John at the door. (ehtimol)", right: "It might/could be John.", note: "Bir martalik ehtimol uchun 'might/could' ishlatiladi." },
    ],
    quiz: [
      { q: "He isn't answering — he ___ be busy.", options: ["can't", "must", "should", "would"], answer: 1 },
      { q: "That ___ be Aziza — she's in London now!", options: ["must", "might", "can't", "may"], answer: 2 },
      { q: "I'm not sure, but it ___ rain later.", options: ["must", "can't", "might", "will must"], answer: 2 },
      { q: "You got the highest score — you ___ be proud!", options: ["can't", "might", "must", "mustn't"], answer: 2 },
      { q: "Taxminda \"bo'lishi mumkin emas\":", options: ["mustn't be", "can't be", "may not be", "shouldn't be"], answer: 1 },
    ],
  },
];
