import type { GrammarLesson } from "./types";

/** B2 — upper-intermediate: perfect past, unreal past, advanced passive. */
export const B2_LESSONS: GrammarLesson[] = [
  {
    slug: "past-perfect",
    level: "B2",
    title: "Past Perfect",
    titleUz: "O'tgan tugallangan zamon",
    emoji: "⏮️",
    explanation: [
      "Past Perfect (had + V3) — \"o'tmishdan ham oldingi o'tmish\": ikki o'tgan voqeadan QAYSI BIRI OLDIN bo'lganini ko'rsatadi. \"When I arrived, the film had started\" — men kelganimda film allaqachon boshlanib bo'lgan edi.",
      "Taqqoslang: \"When I arrived, the film started\" (men kelganimdan KEYIN boshlandi) vs \"...the film had started\" (men kelishimdan OLDIN boshlangan edi). Bitta 'had' butun ma'noni o'zgartiradi.",
      "Belgilar: by the time, already, after, before, when. Ko'pincha 'because' bilan sabab tushuntirishda: \"He was hungry because he hadn't eaten all day\".",
      "Hikoyada voqealar tartibda aytilsa, Past Perfect shart emas — faqat tartib buzilganda kerak.",
    ],
    formula: "had + V3 — ikki o'tmishdan oldingisi",
    examples: [
      { en: "By the time we got to the station, the train had left.", uz: "Bekatga yetib borganimizda poyezd ketib bo'lgan edi." },
      { en: "She had never seen the sea before that trip.", uz: "O'sha safargacha u dengizni hech ko'rmagan edi." },
      { en: "I recognized him because I had met him before.", uz: "Uni tanidim, chunki oldin uchratgan edim." },
      { en: "After they had finished dinner, they went for a walk.", uz: "Kechki ovqatni tugatib bo'lgach, sayrga chiqishdi." },
      { en: "He couldn't pay — he had forgotten his wallet.", uz: "U to'lay olmadi — hamyonini unutib qoldirgan edi." },
      { en: "The garden was beautiful: someone had planted roses everywhere.", uz: "Bog' go'zal edi: kimdir hamma yoqqa atirgul ekib qo'ygan edi." },
    ],
    mistakes: [
      { wrong: "When I arrived, the meeting already started.", right: "...the meeting had already started.", note: "Oldinroq bo'lgan voqea — Past Perfect." },
      { wrong: "She had went home.", right: "She had gone home.", note: "'Had'dan keyin V3 (gone)." },
      { wrong: "I had seen him yesterday. (yakka voqea)", right: "I saw him yesterday.", note: "Yakka o'tgan voqea — Past Simple; Past Perfect faqat ikki o'tmishni solishtirishda." },
    ],
    quiz: [
      { q: "The film ___ by the time we arrived.", options: ["ended", "had ended", "has ended", "was ending"], answer: 1 },
      { q: "He told me he ___ my message.", options: ["didn't receive", "hasn't received", "hadn't received", "doesn't receive"], answer: 2 },
      { q: "After she ___ the letter, she cried.", options: ["read", "had read", "has read", "was reading"], answer: 1 },
      { q: "I was nervous because I ___ an exam before.", options: ["never took", "have never taken", "had never taken", "never take"], answer: 2 },
      { q: "When we got home, someone ___ the window.", options: ["broke", "had broken", "has broken", "breaks"], answer: 1 },
    ],
  },
  {
    slug: "third-conditional",
    level: "B2",
    title: "Third & mixed conditionals",
    titleUz: "3-shart va aralash shart gaplari",
    emoji: "🕰️",
    explanation: [
      "Third Conditional — O'TMISHDAGI xayoliy vaziyat, ya'ni bo'lib o'tgan narsaga afsus yoki tahlil: \"If I had studied harder, I would have passed\" (o'qimadim, o'ta olmadim — endi kech).",
      "Formula: If + Past Perfect, would have + V3. Ikkala qism ham \"og'ir\": had known / would have told.",
      "Mixed Conditional — o'tmishdagi shart, hozirgi natija: \"If I had taken that job, I would be rich now\" (o'shanda olmagandim, hozir boy emasman).",
      "Og'zaki nutqda qisqaradi: would have → would've, had → 'd. \"If I'd known, I would've come.\"",
    ],
    formula: "3: If + had V3, would have V3 · mixed: If + had V3, would + V (hozir)",
    examples: [
      { en: "If you had told me, I would have helped you.", uz: "Aytganingizda, yordam bergan bo'lardim." },
      { en: "She would have caught the flight if she had left earlier.", uz: "Ertaroq chiqqanida samolyotga ulgurardi." },
      { en: "If we hadn't missed the bus, we wouldn't have been late.", uz: "Avtobusni o'tkazib yubormaganimizda kechikmasdik." },
      { en: "If I had learned English at school, I would have a better job now.", uz: "Maktabda ingliz tilini o'rganganimda, hozir yaxshiroq ishim bo'lardi. (aralash)" },
      { en: "What would you have done if you had been there?", uz: "U yerda bo'lganingizda nima qilardingiz?" },
      { en: "If he hadn't moved to the city, he would still live in the village.", uz: "Shaharga ko'chmaganida, hali ham qishloqda yashardi. (aralash)" },
    ],
    mistakes: [
      { wrong: "If I would have known, I would have come.", right: "If I had known, I would have come.", note: "'If' qismida 'would' bo'lmaydi — Past Perfect." },
      { wrong: "If she had studied, she would pass. (o'tmish natija)", right: "...she would have passed.", note: "O'tmishdagi natija — would have + V3." },
      { wrong: "If I had went...", right: "If I had gone...", note: "'Had'dan keyin V3." },
    ],
    quiz: [
      { q: "If they ___ earlier, they would have got tickets.", options: ["came", "had come", "would come", "come"], answer: 1 },
      { q: "I ___ you if I had seen the message.", options: ["would call", "would have called", "called", "will call"], answer: 1 },
      { q: "If he ___ the map, we wouldn't have got lost.", options: ["brought", "would bring", "had brought", "brings"], answer: 2 },
      { q: "If she had saved money, she ___ a car now. (aralash)", options: ["would have", "would have had", "has", "had"], answer: 0 },
      { q: "Qaysi gap TO'G'RI?", options: ["If I would have known, I'd have come.", "If I had known, I'd have come.", "If I had known, I came.", "If I knew, I would have come."], answer: 1 },
    ],
  },
  {
    slug: "passive-advanced",
    level: "B2",
    title: "Passive: all tenses",
    titleUz: "Majhul nisbat: barcha zamonlarda",
    emoji: "🏗️",
    explanation: [
      "B2 darajasida passiv barcha zamonlarda erkin ishlatilishi kerak: is being built (hozir qurilyapti), has been sold (sotilib bo'lingan), had been stolen (o'g'irlangan edi), will have been finished (tugallangan bo'ladi).",
      "Modal + passiv: must be done (bajarilishi shart), can be seen (ko'rish mumkin), should be checked (tekshirilishi kerak) — rasmiy va akademik yozuvning asosi.",
      "Ikki to'ldiruvchili fe'llar ikki xil passiv beradi: \"They gave him a prize\" → \"He was given a prize\" (ko'proq ishlatiladi) yoki \"A prize was given to him\".",
      "IELTS Task 1 (jarayon) deyarli to'liq passivda yoziladi: \"The beans are harvested, then they are dried and roasted...\"",
    ],
    formula: "is being V3 · has been V3 · had been V3 · modal + be + V3",
    examples: [
      { en: "A new metro line is being built in Tashkent.", uz: "Toshkentda yangi metro liniyasi qurilmoqda." },
      { en: "All the tickets have been sold.", uz: "Barcha chiptalar sotib bo'lingan." },
      { en: "The documents must be signed by Friday.", uz: "Hujjatlar jumagacha imzolanishi shart." },
      { en: "When we arrived, the room had been cleaned.", uz: "Kelganimizda xona tozalab qo'yilgan edi." },
      { en: "He was given a second chance.", uz: "Unga ikkinchi imkoniyat berildi." },
      { en: "This medicine should be kept in a cool place.", uz: "Bu dori salqin joyda saqlanishi kerak." },
    ],
    mistakes: [
      { wrong: "The road is been repaired.", right: "The road is being repaired.", note: "Davomli passiv: is BEING + V3." },
      { wrong: "The work must been finished.", right: "The work must be finished.", note: "Modaldan keyin 'be + V3'." },
      { wrong: "The letter has wrote.", right: "The letter has been written.", note: "Perfect passiv: has BEEN + V3." },
    ],
    quiz: [
      { q: "The bridge ___ at the moment.", options: ["is repairing", "is being repaired", "is repaired being", "repairs"], answer: 1 },
      { q: "The email ___ yet.", options: ["hasn't been sent", "hasn't sent", "didn't send", "isn't sending"], answer: 0 },
      { q: "Seatbelts ___ at all times.", options: ["must wear", "must be worn", "must be wearing", "must worn"], answer: 1 },
      { q: "By 2030 the project ___.", options: ["will finish", "will be finishing", "will have been completed", "has completed"], answer: 2 },
      { q: "She ___ a scholarship last year.", options: ["was awarded", "awarded", "has awarded", "was awarding"], answer: 0 },
    ],
  },
  {
    slug: "reported-questions",
    level: "B2",
    title: "Reported questions & requests",
    titleUz: "O'zlashtirma savol va iltimoslar",
    emoji: "❔",
    explanation: [
      "Savolni yetkazishda gap tartibi ODDIY GAPGA qaytadi va 'do/does/did' yo'qoladi: \"Where do you live?\" → He asked where I lived.",
      "Ha/yo'q savollari 'if' yoki 'whether' bilan: \"Are you married?\" → She asked if I was married.",
      "Iltimos va buyruqlar 'to + fe'l' bilan: \"Please wait\" → He asked me to wait. \"Don't touch it!\" → She told me not to touch it. Inkorda 'not to' — 'to don't' emas!",
      "Savol belgisi o'zlashtirma gapda YOZILMAYDI: He asked where I lived. (nuqta, so'roq emas)",
    ],
    formula: "asked + wh + oddiy tartib · asked if/whether · asked/told + kimni + (not) to V",
    examples: [
      { en: "\"What time is it?\" → He asked what time it was.", uz: "U soat necha bo'lganini so'radi." },
      { en: "\"Do you like jazz?\" → She asked if I liked jazz.", uz: "U jazzni yoqtirishimni so'radi." },
      { en: "\"Open the window, please.\" → He asked me to open the window.", uz: "U mendan derazani ochishni iltimos qildi." },
      { en: "\"Don't be late!\" → She told us not to be late.", uz: "U bizga kechikmaslikni aytdi." },
      { en: "They asked whether we had booked a table.", uz: "Ular stol band qilganimizni so'rashdi." },
      { en: "The teacher told the students to switch off their phones.", uz: "O'qituvchi talabalarga telefonlarini o'chirishni aytdi." },
    ],
    mistakes: [
      { wrong: "He asked where did I work.", right: "He asked where I worked.", note: "O'zlashtirma savolda 'did' yo'q, tartib oddiy." },
      { wrong: "She told me to not worry.", right: "She told me not to worry.", note: "Inkor: 'not to + fe'l'." },
      { wrong: "He asked me that I help him.", right: "He asked me to help him.", note: "Iltimos 'to + fe'l' bilan yasaladi." },
    ],
    quiz: [
      { q: "\"Where are you going?\" → She asked where ___.", options: ["was I going", "I was going", "am I going", "I am going"], answer: 1 },
      { q: "\"Can you swim?\" → He asked ___ I could swim.", options: ["that", "what", "if", "do"], answer: 2 },
      { q: "\"Please help me.\" → She asked me ___ her.", options: ["helping", "that I help", "to help", "help"], answer: 2 },
      { q: "\"Don't open the box!\" → He told me ___ the box.", options: ["to not open", "not to open", "don't open", "not opening"], answer: 1 },
      { q: "\"Did you see it?\" → They asked if I ___ it.", options: ["saw", "had seen", "see", "have seen"], answer: 1 },
    ],
  },
  {
    slug: "wish-if-only",
    level: "B2",
    title: "Wish / If only",
    titleUz: "Wish / If only (afsus va orzu)",
    emoji: "🌠",
    explanation: [
      "'Wish' hozirgi holatdan norozilikni bildirsa, PAST SIMPLE ishlatiladi: \"I wish I had more time\" (vaqtim ko'proq bo'lishini istardim — lekin yo'q).",
      "O'tmishdagi afsus uchun PAST PERFECT: \"I wish I had studied medicine\" (o'qimaganman — afsus).",
      "Birovning g'ashga tegadigan odati haqida: wish + would: \"I wish you would stop smoking\" (chekishni tashlashingizni istardim).",
      "'If only' — xuddi shu qoidalar, lekin his-tuyg'u kuchliroq: \"If only I had listened to you!\" (qaniydi sizga quloq solganimda!).",
    ],
    formula: "wish + Past (hozirgi afsus) · wish + Past Perfect (o'tmish afsusi) · wish + would (odat)",
    examples: [
      { en: "I wish I knew the answer.", uz: "Javobni bilganimda edi. (hozir bilmayman)" },
      { en: "She wishes she lived closer to her family.", uz: "U oilasiga yaqinroq yashashni istaydi." },
      { en: "I wish I hadn't said that.", uz: "Qaniydi buni aytmagan bo'lsam. (aytdim — afsus)" },
      { en: "If only we had bought those tickets!", uz: "Qaniydi o'sha chiptalarni olganimizda!" },
      { en: "I wish my neighbours would turn the music down.", uz: "Qo'shnilarim musiqani pasaytirishsa edi." },
      { en: "He wishes he were taller.", uz: "U bo'yi balandroq bo'lishini istaydi." },
    ],
    mistakes: [
      { wrong: "I wish I have more money.", right: "I wish I had more money.", note: "Hozirgi orzu — Past Simple bilan." },
      { wrong: "I wish I didn't say that. (o'tmish)", right: "I wish I hadn't said that.", note: "O'tmishdagi afsus — Past Perfect." },
      { wrong: "I wish to my brother would call.", right: "I wish my brother would call.", note: "'Wish'dan keyin to'g'ridan-to'g'ri gap keladi." },
    ],
    quiz: [
      { q: "I wish I ___ how to drive.", options: ["know", "knew", "have known", "would know"], answer: 1 },
      { q: "She wishes she ___ to the party last night.", options: ["went", "had gone", "would go", "goes"], answer: 1 },
      { q: "I wish it ___ raining — we want to play outside.", options: ["stops", "stopped", "would stop", "will stop"], answer: 2 },
      { q: "If only I ___ his advice!", options: ["took", "had taken", "would take", "take"], answer: 1 },
      { q: "I wish I ___ rich. (hozir)", options: ["am", "was/were", "had been", "will be"], answer: 1 },
    ],
  },
  {
    slug: "causative",
    level: "B2",
    title: "Causative: have/get something done",
    titleUz: "Kauzativ: have/get something done",
    emoji: "🔧",
    explanation: [
      "Ishni O'ZIMIZ emas, BOSHQA birov biz uchun qilganda 'have/get + narsa + V3' ishlatiladi: \"I had my hair cut\" (sochimni oldirdim — sartarosh kesdi, men emas).",
      "Taqqoslang: \"I cut my hair\" (o'zim kesdim!) vs \"I had my hair cut\" (oldirdim). O'zbekchadagi \"-dir\" nisbatiga mos: qurdirdim, tiktirdim, oldirdim.",
      "'Get' norasmiyroq, 'have' neytral: I got my phone fixed = I had my phone fixed.",
      "Yoqimsiz hodisalar uchun ham: \"He had his car stolen\" (mashinasi o'g'irlandi).",
    ],
    formula: "have/get + object + V3",
    examples: [
      { en: "I'm having my car repaired tomorrow.", uz: "Ertaga mashinamni tuzattiryapman." },
      { en: "She had a new dress made for the wedding.", uz: "U to'y uchun yangi ko'ylak tiktirdi." },
      { en: "We got the house painted last summer.", uz: "O'tgan yozda uyni bo'yattirdik." },
      { en: "Where do you have your suits cleaned?", uz: "Kostyumlaringizni qayerda tozalattirasiz?" },
      { en: "He had his teeth checked last week.", uz: "U o'tgan hafta tishlarini tekshirtirdi." },
      { en: "They had their roof damaged in the storm.", uz: "Bo'ronda ularning tomi shikastlandi." },
    ],
    mistakes: [
      { wrong: "I cut my hair at the barber's.", right: "I had my hair cut at the barber's.", note: "Boshqa odam qilgan ish — kauzativ kerak." },
      { wrong: "I had repaired my phone. (usta tuzatgan)", right: "I had my phone repaired.", note: "Tartib: have + NARSA + V3." },
      { wrong: "She had her nails do.", right: "She had her nails done.", note: "Oxirida V3 (done) keladi." },
    ],
    quiz: [
      { q: "I need to ___ my water heater fixed.", options: ["have", "make", "do", "let"], answer: 0 },
      { q: "She ___ her photo taken for the passport.", options: ["had", "did", "made", "took"], answer: 0 },
      { q: "We're having the kitchen ___ next month.", options: ["renovate", "renovated", "renovating", "to renovate"], answer: 1 },
      { q: "\"Sochimni oldirdim\":", options: ["I cut my hair.", "I had my hair cut.", "My hair cut.", "I had cut my hair."], answer: 1 },
      { q: "He got his essay ___ by a teacher.", options: ["check", "checking", "checked", "to check"], answer: 2 },
    ],
  },
  {
    slug: "future-perfect-continuous",
    level: "B2",
    title: "Future Perfect & Continuous",
    titleUz: "Kelasi tugallangan va davomli zamon",
    emoji: "🚀",
    explanation: [
      "Future Continuous (will be + V-ing) — kelajakdagi muayyan paytda DAVOM ETAYOTGAN ish: \"This time tomorrow I will be flying to Dubai\" (ertaga shu payt uchayotgan bo'laman).",
      "Future Perfect (will have + V3) — kelajakdagi nuqtaGACHA TUGAGAN ish: \"By 2030 I will have finished university\" (2030-gacha bitirgan bo'laman). Belgisi — 'by' (…gacha).",
      "Future Perfect Continuous (will have been + V-ing) — kelajak nuqtasigacha qancha DAVOM ETGANini ta'kidlaydi: \"By June I will have been working here for five years\".",
      "Bu zamonlar IELTS Speaking Part 3 va Writing'da kelajak prognozlarida yuqori band belgisi hisoblanadi.",
    ],
    formula: "will be V-ing (jarayonda) · will have V3 (tugagan) · by + vaqt",
    examples: [
      { en: "Don't call at 9 — I will be driving.", uz: "9 da qo'ng'iroq qilmang — mashina haydayotgan bo'laman." },
      { en: "By next year, they will have built the new stadium.", uz: "Kelasi yilgacha ular yangi stadionni qurib bitkazishadi." },
      { en: "She will have graduated by the time she turns 22.", uz: "22 yoshga to'lguncha u universitetni bitirgan bo'ladi." },
      { en: "This time next week we will be lying on the beach.", uz: "Kelasi hafta shu payt plyajda yotgan bo'lamiz." },
      { en: "By December I will have been learning English for two years.", uz: "Dekabrgacha ingliz tilini o'rganayotganimga ikki yil bo'ladi." },
      { en: "The meeting will have ended by 5 pm.", uz: "Yig'ilish soat 17 gacha tugagan bo'ladi." },
    ],
    mistakes: [
      { wrong: "By Friday I will finish the report. (…gacha)", right: "By Friday I will have finished the report.", note: "'By + vaqt' bilan Future Perfect ishlatiladi." },
      { wrong: "I will be work at 8 pm.", right: "I will be working at 8 pm.", note: "Continuous: will be + V-ing." },
      { wrong: "She will have been finish...", right: "She will have finished...", note: "Perfect: will have + V3 (been faqat continuous'da)." },
    ],
    quiz: [
      { q: "This time tomorrow, I ___ on a plane.", options: ["will sit", "will be sitting", "will have sat", "sit"], answer: 1 },
      { q: "By 2028, she ___ her PhD.", options: ["will finish", "will be finishing", "will have finished", "finishes"], answer: 2 },
      { q: "By May, we ___ here for ten years.", options: ["will live", "will be living", "will have been living", "live"], answer: 2 },
      { q: "Don't visit at noon — they ___ lunch.", options: ["will have", "will be having", "will have had", "have"], answer: 1 },
      { q: "The builders ___ the work by winter.", options: ["will have completed", "will completing", "complete", "will be complete"], answer: 0 },
    ],
  },
  {
    slug: "linking-contrast",
    level: "B2",
    title: "Linking: although / despite / however",
    titleUz: "Bog'lovchilar: although / despite / however",
    emoji: "🌉",
    explanation: [
      "Qarama-qarshilik bog'lovchilari IELTS Writing'ning yuragi — lekin ularning GRAMMATIKASI har xil.",
      "'Although / even though' + TO'LIQ GAP: Although it was raining, we went out.",
      "'Despite / in spite of' + OT yoki V-ing: Despite the rain, we went out. Despite being tired, she kept working. \"Despite of\" degan shakl MAVJUD EMAS!",
      "'However' ikki alohida gapni bog'laydi va verguldan keyin keladi: It was expensive. However, we bought it. Gap o'rtasida esa: We bought it, however, only after a discount.",
    ],
    formula: "although + gap · despite + ot/V-ing · gap. However, gap",
    examples: [
      { en: "Although he was ill, he came to work.", uz: "Kasal bo'lsa ham, ishga keldi." },
      { en: "Despite the traffic, we arrived on time.", uz: "Tirbandlikka qaramay, o'z vaqtida yetib keldik." },
      { en: "In spite of studying hard, she failed the test.", uz: "Qattiq o'qiganiga qaramay, testdan yiqildi." },
      { en: "The hotel was expensive. However, the service was poor.", uz: "Mehmonxona qimmat edi. Biroq xizmat sifati past edi." },
      { en: "Even though prices rose, demand stayed high.", uz: "Narxlar oshsa-da, talab yuqoriligicha qoldi." },
      { en: "Despite his age, he runs a marathon every year.", uz: "Yoshiga qaramay, u har yili marafon yuguradi." },
    ],
    mistakes: [
      { wrong: "Despite of the rain...", right: "Despite the rain... / In spite of the rain...", note: "'Despite of' mavjud emas: yo 'despite', yo 'in spite of'." },
      { wrong: "Although the rain, we went out.", right: "Although it was raining, we went out.", note: "'Although'dan keyin to'liq gap keladi." },
      { wrong: "It was cold, however we swam.", right: "It was cold. However, we swam.", note: "'However' yangi gapni boshlaydi va vergul bilan ajratiladi." },
    ],
    quiz: [
      { q: "___ being tired, he finished the project.", options: ["Although", "Despite", "However", "Even though"], answer: 1 },
      { q: "___ it was late, they continued working.", options: ["Despite", "In spite of", "Although", "However"], answer: 2 },
      { q: "The food was cheap. ___, it was delicious.", options: ["Although", "Despite", "However", "Because"], answer: 2 },
      { q: "Qaysi shakl XATO?", options: ["despite the cost", "in spite of the cost", "despite of the cost", "although it costs a lot"], answer: 2 },
      { q: "___ the bad weather, the match went ahead.", options: ["Although", "Even though", "However", "In spite of"], answer: 3 },
    ],
  },
  {
    slug: "articles-advanced",
    level: "B2",
    title: "Articles: advanced cases",
    titleUz: "Artikllar: murakkab holatlar",
    emoji: "🎯",
    explanation: [
      "Geografiya qoidalari: daryolar, dengizlar, tog' TIZMALARI, davlat nomida ko'plik/so'z birikmasi — THE bilan (the Amu Darya, the Pamirs, the UK, the USA). Yakka tog'lar, ko'llar, shaharlar, aksariyat davlatlar — artiklsiz (Uzbekistan, Tashkent, Lake Aydarkul).",
      "Muassasalar maqsadida ishlatilsa artiklsiz: go to school (o'qish uchun), be in hospital (davolanish uchun), lekin binoga borish ma'nosida the bilan: go to the school (masalan, ota-onalar yig'ilishiga).",
      "Umumiylik: The + birlik ilmiy uslubda turni bildiradi (The snow leopard is endangered), ko'plik artiklsiz — oddiy umumiylik (Snow leopards are endangered).",
      "Turg'un iboralar: in the morning, on the one hand, at night, by car, watch TV (artiklsiz!), listen to the radio.",
    ],
    formula: "the + daryo/dengiz/tizma/ko'plik-davlat · Ø + shahar/ko'l/aksariyat davlatlar",
    examples: [
      { en: "The Syr Darya flows into the Aral Sea region.", uz: "Sirdaryo Orol dengizi hududiga quyiladi." },
      { en: "She studied in the United States.", uz: "U Qo'shma Shtatlarda o'qigan." },
      { en: "Mount Everest is in the Himalayas.", uz: "Everest tog'i Himolay tizmasida." },
      { en: "My son goes to school by bus.", uz: "O'g'lim maktabga avtobusda boradi." },
      { en: "Her grandfather is in hospital.", uz: "Uning bobosi kasalxonada (davolanmoqda)." },
      { en: "The tiger is one of the largest cats.", uz: "Yo'lbars eng yirik mushuksimonlardan biri." },
    ],
    mistakes: [
      { wrong: "I visited USA last year.", right: "I visited the USA last year.", note: "Qisqartma-davlatlar (the USA, the UK) doim 'the' bilan." },
      { wrong: "The Tashkent is beautiful.", right: "Tashkent is beautiful.", note: "Shahar nomlari artiklsiz." },
      { wrong: "He watches the TV every evening.", right: "He watches TV every evening.", note: "'Watch TV' turg'un ibora — artiklsiz." },
    ],
    quiz: [
      { q: "___ Amu Darya is the longest river in Central Asia.", options: ["A", "An", "The", "—"], answer: 2 },
      { q: "They live in ___ Uzbekistan.", options: ["the", "a", "an", "—"], answer: 3 },
      { q: "She is ___ hospital after the operation.", options: ["in", "in the", "at a", "on"], answer: 0 },
      { q: "We flew over ___ Alps.", options: ["—", "a", "the", "an"], answer: 2 },
      { q: "I never watch ___ TV in the morning.", options: ["the", "a", "—", "an"], answer: 2 },
    ],
  },
];
