import type { GrammarLesson } from "./types";

/** IELTS/C1 — the structures that separate band 6 from band 8 writing. */
export const IELTS_LESSONS: GrammarLesson[] = [
  {
    slug: "complex-sentences",
    level: "IELTS",
    title: "Complex sentences for Writing",
    titleUz: "Murakkab gaplar (Writing uchun)",
    emoji: "🏛️",
    explanation: [
      "IELTS baholash mezonida \"a mix of simple and complex sentences\" talab qilinadi. Murakkab gap = bosh gap + ergash gap (because, although, while, if, when, which bilan).",
      "Band 6 yozuvchi sodda gaplarni ketma-ket teradi: \"Cars cause pollution. Governments should act.\" Band 8: \"Since private cars remain a major source of urban pollution, governments should invest in public transport.\"",
      "Formulalar to'plami: sabab (since/as/because), qarama-qarshilik (although/while/whereas), shart (provided that/unless), maqsad (so that/in order to), natija (so ... that/such ... that).",
      "MUHIM: har gapni murakkab qilmaslik kerak — aralashtirish (2 sodda + 1 murakkab) eng tabiiy o'qiladi. Juda uzun gap band tushiradi, ko'tarmasin.",
    ],
    formula: "bosh gap + bog'lovchi + ergash gap · aralash uslub = band 7+",
    examples: [
      { en: "While technology connects people, it can also isolate them.", uz: "Texnologiya odamlarni bog'lasa-da, ularni yakkalab ham qo'yishi mumkin." },
      { en: "Since housing costs keep rising, many young people rent for longer.", uz: "Uy-joy narxlari oshib borayotgani sabab, ko'p yoshlar uzoqroq ijarada yashaydi." },
      { en: "Governments should fund education so that everyone has equal opportunities.", uz: "Hamma teng imkoniyatga ega bo'lishi uchun davlat ta'limni moliyalashtirishi kerak." },
      { en: "The problem is so serious that immediate action is required.", uz: "Muammo shu qadar jiddiyki, zudlik bilan chora talab qilinadi." },
      { en: "Whereas older people prefer print media, the young rely on social networks.", uz: "Keksalar bosma nashrni afzal ko'rsa, yoshlar ijtimoiy tarmoqlarga tayanadi." },
      { en: "Unless stricter laws are introduced, the situation will deteriorate.", uz: "Qattiqroq qonunlar kiritilmasa, vaziyat yomonlashadi." },
    ],
    mistakes: [
      { wrong: "Although it was expensive, but we bought it.", right: "Although it was expensive, we bought it.", note: "'Although' va 'but' birga ishlatilmaydi — bittasi yetarli." },
      { wrong: "Because pollution is increasing. Governments must act.", right: "Because pollution is increasing, governments must act.", note: "'Because'li ergash gap yolg'iz tura olmaydi — bosh gapga ulanadi." },
      { wrong: "The weather was so cold that's why we stayed home.", right: "The weather was so cold that we stayed home.", note: "'So ... that' qurilmasida 'that's why' emas, 'that' keladi." },
    ],
    quiz: [
      { q: "___ the price was high, the product sold well.", options: ["Despite", "Although", "Because", "However"], answer: 1 },
      { q: "Save your work regularly ___ you don't lose it.", options: ["so that", "because", "although", "unless"], answer: 0 },
      { q: "The lecture was ___ boring that half the students left.", options: ["such", "very", "so", "too"], answer: 2 },
      { q: "___ demand increases, prices will remain stable.", options: ["Because", "Unless", "So that", "Despite"], answer: 1 },
      { q: "Qaysi gap band 8 uslubiga eng yaqin?", options: ["Pollution is bad. We must act.", "Pollution is bad and we must act and it is important.", "Since pollution threatens public health, urgent measures are essential.", "Pollution!"], answer: 2 },
    ],
  },
  {
    slug: "participle-clauses",
    level: "IELTS",
    title: "Participle clauses",
    titleUz: "Sifatdosh o'ramlar",
    emoji: "✂️",
    explanation: [
      "Participle clause — gapni qisqartirib, akademik uslub beruvchi qurilma: \"Because she felt tired, she went home\" → \"Feeling tired, she went home\".",
      "V-ing — faol ma'no va bir vaqtdalik: \"Walking home, I met an old friend\" (uyga ketayotib...). Having + V3 — oldinroq tugagan ish: \"Having finished the report, he left\" (hisobotni tugatib bo'lib...).",
      "V3 — passiv ma'no: \"Built in the 15th century, the mosque attracts thousands of visitors\" (15-asrda qurilgan bo'lib...).",
      "XAVF: o'ram egasi bosh gap egasi bilan BIR XIL bo'lishi shart. \"Walking home, the rain started\" — xato: yomg'ir yurmaydi! Bu 'dangling participle' deyiladi.",
    ],
    formula: "V-ing (faol) · Having V3 (oldin tugagan) · V3 (passiv)",
    examples: [
      { en: "Feeling exhausted, she cancelled the meeting.", uz: "O'zini holsiz sezib, u yig'ilishni bekor qildi." },
      { en: "Having lived abroad, he understands cultural differences well.", uz: "Chet elda yashagani uchun u madaniy farqlarni yaxshi tushunadi." },
      { en: "Founded in 1918, the university is among the oldest in the region.", uz: "1918-yilda asos solingan bu universitet mintaqadagi eng qadimiylardan." },
      { en: "Looking at the data, we can see a clear upward trend.", uz: "Ma'lumotlarga qarab, aniq o'sish tendensiyasini ko'ramiz." },
      { en: "Not knowing the answer, I stayed silent.", uz: "Javobni bilmaganim uchun jim qoldim." },
      { en: "Having been warned twice, the driver lost his licence.", uz: "Ikki marta ogohlantirilgach, haydovchi guvohnomasidan ayrildi." },
    ],
    mistakes: [
      { wrong: "Walking to work, the rain started.", right: "Walking to work, I got caught in the rain.", note: "O'ram egasi bosh gap egasi bilan bir xil bo'lishi kerak." },
      { wrong: "After finished the task, we rested.", right: "After finishing the task, we rested.", note: "Predlogdan keyin V-ing keladi." },
      { wrong: "Having eat dinner, they left.", right: "Having eaten dinner, they left.", note: "'Having'dan keyin V3." },
    ],
    quiz: [
      { q: "___ the exam, she celebrated with friends.", options: ["Passing", "Having passed", "Passed", "To pass"], answer: 1 },
      { q: "___ in 2005, the bridge needs repairs already.", options: ["Building", "Having built", "Built", "To build"], answer: 2 },
      { q: "___ what to say, he remained silent.", options: ["Not knowing", "Not known", "Don't knowing", "Not to know"], answer: 0 },
      { q: "Qaysi gap XATO (dangling)?", options: ["Feeling ill, she left early.", "Driving home, my phone rang.", "Having won, the team celebrated.", "Written in English, the book sold worldwide."], answer: 1 },
      { q: "___ the results, the scientists drew conclusions.", options: ["Analysed", "Having analysed", "Being analysed", "To analyse"], answer: 1 },
    ],
  },
  {
    slug: "inversion",
    level: "IELTS",
    title: "Inversion",
    titleUz: "Inversiya (teskari tartib)",
    emoji: "🔄",
    explanation: [
      "Inversiya — ta'kid uchun gapni savol tartibida qurish. Band 8-9 yozuv va nutqning \"mo'jizaviy quroli\": \"Never have I seen such dedication\" (oddiy: I have never seen...).",
      "Inkor ravishlardan keyin: Never, Rarely, Seldom, Little, Under no circumstances, Not only... — dan keyin yordamchi fe'l EGADAN OLDIN keladi: \"Not only does exercise improve health, but it also boosts mood.\"",
      "'Only' qurilmalari: \"Only when we lose something do we appreciate it\" (faqat yo'qotgandagina qadrlaymiz).",
      "Shartda 'if'siz inversiya: \"Had I known, I would have come\" (= If I had known). \"Should you need help, contact us\" (= If you need). Rasmiy xatlarda juda chiroyli.",
    ],
    formula: "Inkor ravish + yordamchi + ega + fe'l · Had/Should + ega (= if)",
    examples: [
      { en: "Never have I heard such a beautiful voice.", uz: "Bunday go'zal ovozni hech qachon eshitmaganman." },
      { en: "Not only did prices rise, but quality also fell.", uz: "Narxlar oshibgina qolmay, sifat ham tushdi." },
      { en: "Rarely do we consider the long-term effects.", uz: "Uzoq muddatli oqibatlarni kamdan-kam o'ylaymiz." },
      { en: "Only after the accident did the city install traffic lights.", uz: "Faqat avariyadan keyingina shahar svetofor o'rnatdi." },
      { en: "Had I known about the meeting, I would have attended.", uz: "Yig'ilish haqida bilganimda, qatnashgan bo'lardim." },
      { en: "Under no circumstances should children be left alone in cars.", uz: "Hech qanday holatda bolalarni mashinada yolg'iz qoldirib bo'lmaydi." },
    ],
    mistakes: [
      { wrong: "Never I have seen this.", right: "Never have I seen this.", note: "Inkor ravishdan keyin yordamchi fe'l egadan oldin keladi." },
      { wrong: "Not only prices rose, but...", right: "Not only did prices rise, but...", note: "'Not only'dan keyin yordamchi (did) kerak." },
      { wrong: "Had I known it, I would come.", right: "Had I known it, I would have come.", note: "O'tmish sharti — natija 'would have + V3'." },
    ],
    quiz: [
      { q: "Never ___ such heavy rain.", options: ["I saw", "have I seen", "I have seen", "saw I"], answer: 1 },
      { q: "Not only ___ late, but he also forgot the documents.", options: ["he was", "was he", "he is", "is he"], answer: 1 },
      { q: "Only then ___ the truth.", options: ["I understood", "did I understand", "I did understand", "understood I"], answer: 1 },
      { q: "___ you require assistance, please call reception.", options: ["If should", "Should", "Would", "Had"], answer: 1 },
      { q: "Seldom ___ so moved by a performance.", options: ["the audience was", "was the audience", "the audience is", "audience was"], answer: 1 },
    ],
  },
  {
    slug: "cleft-sentences",
    level: "IELTS",
    title: "Cleft sentences",
    titleUz: "Ajratilgan (cleft) gaplar",
    emoji: "💎",
    explanation: [
      "Cleft gaplar fikrning BIR qismini yoritqichga oladi. Oddiy: \"I need more time.\" Cleft: \"What I need is more time\" (menga kerak bo'lgani — vaqt).",
      "'What' clefti: What matters most is honesty. What surprised me was his calmness. Speaking'da fikrlashga vaqt yutish va urg'u berishning a'lo usuli.",
      "'It' clefti: It was the manager who made the mistake (aynan menejer xato qildi — boshqa emas). It is education that transforms societies.",
      "IELTS Writing 2'da pozitsiyani kuchli ifodalash uchun: \"It is governments, rather than individuals, that must lead this change.\"",
    ],
    formula: "What + gap + is/was ... · It is/was X that/who ...",
    examples: [
      { en: "What I love about Tashkent is its food culture.", uz: "Toshkentda menga yoqadigani — uning taom madaniyati." },
      { en: "It was my grandmother who taught me patience.", uz: "Menga sabrni o'rgatgan — buvim edi." },
      { en: "What the city needs is a better metro system.", uz: "Shaharga kerak bo'lgani — yaxshiroq metro tizimi." },
      { en: "It is consistency that leads to success, not luck.", uz: "Muvaffaqiyatga olib boradigani omad emas — izchillik." },
      { en: "What worries scientists is the speed of change.", uz: "Olimlarni tashvishga solayotgani — o'zgarish tezligi." },
      { en: "It was only in 2020 that the law was passed.", uz: "Qonun faqat 2020-yildagina qabul qilindi." },
    ],
    mistakes: [
      { wrong: "What I need is I need more practice.", right: "What I need is more practice.", note: "'Is'dan keyin faqat urg'u berilayotgan qism keladi." },
      { wrong: "It was him who did it. (rasmiy)", right: "It was he who did it.", note: "Rasmiy uslubda 'It was he/she who...' afzal (og'zakida 'him' ham yuradi)." },
      { wrong: "That I want is peace.", right: "What I want is peace.", note: "Cleft 'what' bilan boshlanadi." },
    ],
    quiz: [
      { q: "___ I admire about her is her honesty.", options: ["That", "Which", "What", "Who"], answer: 2 },
      { q: "It was the design ___ attracted investors.", options: ["what", "who", "that", "whose"], answer: 2 },
      { q: "What this district needs ___ more green spaces.", options: ["are", "is", "be", "were"], answer: 1 },
      { q: "\"Aynan mashq muvaffaqiyat keltiradi\":", options: ["Practice is it that brings success.", "It is practice that brings success.", "What practice brings is success it.", "That practice brings success."], answer: 1 },
      { q: "It was in Bukhara ___ they first met.", options: ["where", "that", "which", "when"], answer: 1 },
    ],
  },
  {
    slug: "nominalization",
    level: "IELTS",
    title: "Nominalization (academic style)",
    titleUz: "Nominalizatsiya (akademik uslub)",
    emoji: "🎓",
    explanation: [
      "Nominalizatsiya — fe'l/sifatni OTGA aylantirish. Akademik ingliz tilining DNKsi: \"The government decided to...\" → \"The government's decision to...\"",
      "Taqqoslang: \"Because people use cars more, the air got dirtier\" (og'zaki) → \"The increase in car use has led to a decline in air quality\" (band 8). Fikr bir xil, daraja boshqa.",
      "Asosiy juftliklar: grow → growth, reduce → reduction, improve → improvement, fail → failure, develop → development, aware → awareness, able → ability.",
      "Formulla: [Ot ko'rinishdagi jarayon] + leads to / results in / contributes to + [ot ko'rinishdagi natija]. Task 1 trend tasvirlash: \"a sharp rise in prices\", \"a gradual fall in demand\".",
    ],
    formula: "fe'l → ot: growth, reduction, improvement · X leads to Y",
    examples: [
      { en: "The growth of online shopping has transformed retail.", uz: "Onlayn xaridlarning o'sishi chakana savdoni o'zgartirib yubordi." },
      { en: "A reduction in working hours may improve productivity.", uz: "Ish soatlarining qisqarishi samaradorlikni oshirishi mumkin." },
      { en: "There has been a significant improvement in literacy rates.", uz: "Savodxonlik darajasida sezilarli yaxshilanish yuz berdi." },
      { en: "The failure of the project was due to poor planning.", uz: "Loyihaning muvaffaqiyatsizligi rejaning zaifligidan edi." },
      { en: "Public awareness of climate change is rising.", uz: "Iqlim o'zgarishi haqidagi jamoatchilik xabardorligi ortmoqda." },
      { en: "The graph shows a steady decline in birth rates.", uz: "Grafik tug'ilish darajasining barqaror pasayishini ko'rsatadi." },
    ],
    mistakes: [
      { wrong: "People buy more online and shops close, this is bad.", right: "The shift to online shopping has caused many shops to close.", note: "Akademik uslub: jarayonni ot qilib, aniq bog'lang." },
      { wrong: "The improve of education...", right: "The improvement of education...", note: "Ot shakli: improvement." },
      { wrong: "A rise of prices", right: "A rise in prices", note: "Trend otlari 'in' bilan: a rise/fall/increase IN." },
    ],
    quiz: [
      { q: "'Develop' fe'lining ot shakli:", options: ["developness", "development", "developing", "developed"], answer: 1 },
      { q: "There was a sharp ___ in fuel prices.", options: ["rise", "risen", "rising", "rose"], answer: 0 },
      { q: "The chart shows an increase ___ internet use.", options: ["of", "in", "on", "at"], answer: 1 },
      { q: "Akademik variantni tanlang:", options: ["Cities got bigger fast.", "The cities grew and grew.", "Rapid urban growth occurred.", "Cities big now."], answer: 2 },
      { q: "'Fail' so'zining ot shakli:", options: ["failness", "failure", "failing", "failed"], answer: 1 },
    ],
  },
  {
    slug: "hedging",
    level: "IELTS",
    title: "Hedging (cautious language)",
    titleUz: "Ehtiyotkor til (hedging)",
    emoji: "🛡️",
    explanation: [
      "Akademik yozuvda qat'iy da'vo xavfli: \"Technology makes people lazy\" — isbotlab bo'lmaydi. Hedging — fikrni himoyalangan qilish: \"Technology may make some people less active.\"",
      "Asboblar: modal fe'llar (may, might, could), yumshoq fe'llar (tend to, appear to, seem to), ravishlar (arguably, generally, relatively), miqdor (some, many, a number of).",
      "IELTS Writing 2 uchun oltin shakllar: \"It could be argued that...\", \"This suggests that...\", \"...is likely to...\", \"In many cases,...\"",
      "Muvozanat muhim: har gapni hedge qilish ishonchsiz ko'rsatadi. Faktlar qat'iy, bashorat va umumlashmalar — ehtiyotkor.",
    ],
    formula: "may/might/could · tend to / seem to · arguably / generally · It could be argued that...",
    examples: [
      { en: "Remote work tends to blur the line between office and home.", uz: "Masofaviy ish odatda ish va uy chegarasini xiralashtiradi." },
      { en: "This policy could lead to unintended consequences.", uz: "Bu siyosat kutilmagan oqibatlarga olib kelishi mumkin." },
      { en: "It could be argued that advertising fuels overconsumption.", uz: "Reklama ortiqcha iste'molni kuchaytiradi, deb aytish mumkin." },
      { en: "Young people appear to prefer visual content.", uz: "Yoshlar vizual kontentni afzal ko'radiganga o'xshaydi." },
      { en: "In many cases, early diagnosis saves lives.", uz: "Ko'p hollarda erta tashxis hayotni saqlab qoladi." },
      { en: "The data suggests that the trend will continue.", uz: "Ma'lumotlar tendensiya davom etishini ko'rsatadi." },
    ],
    mistakes: [
      { wrong: "Social media destroys all friendships.", right: "Social media may weaken some friendships.", note: "Mutlaq da'vo (all, destroys) o'rniga ehtiyotkor shakl." },
      { wrong: "Everyone knows that...", right: "It is widely believed that...", note: "'Hamma biladi' — akademik uslubda ishlatilmaydi." },
      { wrong: "This will definitely happen.", right: "This is likely to happen.", note: "Bashoratda 'definitely' o'rniga 'likely'." },
    ],
    quiz: [
      { q: "Stricter laws ___ reduce crime rates.", options: ["will definitely", "may", "must always", "absolutely"], answer: 1 },
      { q: "City dwellers ___ to have less free time.", options: ["tend", "must", "will", "definitely"], answer: 0 },
      { q: "It could be ___ that exams cause unnecessary stress.", options: ["said definitely", "argued", "proven always", "known"], answer: 1 },
      { q: "Eng akademik variant:", options: ["All teenagers are addicted to phones.", "Many teenagers appear to overuse their phones.", "Teenagers always use phones.", "Phones destroy every teenager."], answer: 1 },
      { q: "The evidence ___ that diet affects mood.", options: ["proves 100%", "suggests", "commands", "insists definitely"], answer: 1 },
    ],
  },
  {
    slug: "conditionals-advanced",
    level: "IELTS",
    title: "Advanced conditionals",
    titleUz: "Murakkab shart shakllari",
    emoji: "🧠",
    explanation: [
      "'If' o'rniga boyroq bog'lovchilar band ko'taradi: provided (that) / as long as — \"...sharti bilan\": \"You can borrow my car provided that you drive carefully.\"",
      "'Unless' = if not: \"Unless we act now, it will be too late\" (hozir harakat qilmasak...). Diqqat: unless'dan keyin inkor QO'SHILMAYDI.",
      "'In case' — ehtiyot chorasi (agar emas!): \"Take an umbrella in case it rains\" (yomg'ir yog'ib qolsa deb). \"If it rains\" — yog'sa ochasiz; \"in case it rains\" — oldindan olasiz.",
      "'Otherwise' — aks holda: \"Leave now, otherwise you'll miss the train.\" 'Suppose/supposing' — faraz: \"Suppose you won a million, what would you do?\"",
    ],
    formula: "provided that / as long as (shart bilan) · unless (agar ...masa) · in case (ehtiyot uchun)",
    examples: [
      { en: "You'll pass, provided that you practise daily.", uz: "Har kuni mashq qilsangiz, o'tasiz." },
      { en: "Unless the government intervenes, prices will keep rising.", uz: "Hukumat aralashmasa, narxlar oshaveradi." },
      { en: "Write down my number in case you need help.", uz: "Yordam kerak bo'lib qolsa deb, raqamimni yozib oling." },
      { en: "As long as you respect others, you are welcome here.", uz: "Boshqalarni hurmat qilar ekansiz, bu yerda sizga eshik ochiq." },
      { en: "Hurry up — otherwise we'll be late.", uz: "Shoshiling — aks holda kechikamiz." },
      { en: "Supposing you lost your job, what would you do?", uz: "Faraz qiling, ishingizdan ayrildingiz — nima qilardingiz?" },
    ],
    mistakes: [
      { wrong: "Unless you don't hurry, we'll be late.", right: "Unless you hurry, we'll be late.", note: "'Unless' allaqachon inkorni o'z ichiga oladi." },
      { wrong: "Take a coat if case it gets cold.", right: "Take a coat in case it gets cold.", note: "Ibora: 'in case'." },
      { wrong: "Provided you will study, you will pass.", right: "Provided you study, you will pass.", note: "Shart qismida 'will' ishlatilmaydi." },
    ],
    quiz: [
      { q: "___ you finish your work, you can leave early.", options: ["Unless", "Provided that", "In case", "Otherwise"], answer: 1 },
      { q: "___ it stops raining, the match will be cancelled.", options: ["Provided", "As long as", "Unless", "In case"], answer: 2 },
      { q: "Take some water ___ you get thirsty.", options: ["unless", "in case", "provided", "otherwise"], answer: 1 },
      { q: "Study hard — ___ you will fail.", options: ["otherwise", "unless", "in case", "provided"], answer: 0 },
      { q: "Qaysi gap XATO?", options: ["Unless you hurry, we'll be late.", "Unless you don't hurry, we'll be late.", "Provided you hurry, we'll make it.", "Hurry, otherwise we'll be late."], answer: 1 },
    ],
  },
  {
    slug: "reduced-relative-clauses",
    level: "IELTS",
    title: "Reduced relative clauses",
    titleUz: "Qisqartirilgan aniqlovchi gaplar",
    emoji: "🪶",
    explanation: [
      "Aniqlovchi gapni qisqartirish yozuvni zichroq va akademikroq qiladi: \"The students who are taking the exam\" → \"The students taking the exam\".",
      "Faol ma'noda who/which/that + fe'l → V-ing: \"people who live in cities\" → \"people living in cities\".",
      "Passiv ma'noda who/which + be + V3 → V3: \"the bridge which was built in 1985\" → \"the bridge built in 1985\".",
      "IELTS Task 1'da juda foydali: \"The chart showing population trends...\", \"the figures given in the table...\". Bir gapda ham qisqartirilgan, ham to'liq shaklni aralashtirish mumkin.",
    ],
    formula: "who/which + fe'l → V-ing · who/which + be + V3 → V3",
    examples: [
      { en: "The number of people working remotely has doubled.", uz: "Masofadan ishlaydigan odamlar soni ikki baravar oshdi." },
      { en: "The products sold in this shop are all local.", uz: "Bu do'konda sotiladigan mahsulotlarning bari mahalliy." },
      { en: "Anyone wishing to apply should contact HR.", uz: "Ariza topshirmoqchi bo'lgan har kim HR bilan bog'lansin." },
      { en: "The data collected last year supports this theory.", uz: "O'tgan yili yig'ilgan ma'lumotlar bu nazariyani quvvatlaydi." },
      { en: "Students preparing for IELTS should read widely.", uz: "IELTSga tayyorlanayotgan talabalar keng o'qishlari kerak." },
      { en: "The palace, restored in 2010, is open to visitors.", uz: "2010-yilda ta'mirlangan saroy tashrif uchun ochiq." },
    ],
    mistakes: [
      { wrong: "People living in cities they have more stress.", right: "People living in cities have more stress.", note: "Qisqartirilgan o'ramdan keyin qo'shimcha 'they' kerak emas." },
      { wrong: "The letter sending yesterday arrived.", right: "The letter sent yesterday arrived.", note: "Passiv ma'no — V3 (sent), V-ing emas." },
      { wrong: "The man stands there is my uncle.", right: "The man standing there is my uncle.", note: "Qisqartirishda fe'l V-ing shaklini oladi." },
    ],
    quiz: [
      { q: "The people ___ in the queue looked tired.", options: ["waited", "waiting", "who waiting", "waits"], answer: 1 },
      { q: "The novel ___ into 30 languages is a bestseller.", options: ["translating", "translated", "which translated", "translates"], answer: 1 },
      { q: "Anyone ___ a visa must apply early.", options: ["needing", "needed", "who needing", "needs"], answer: 0 },
      { q: "The figures ___ in the graph relate to 2024.", options: ["showing", "shown", "showed", "show"], answer: 1 },
      { q: "\"The students who are sitting in the hall\" qisqartmasi:", options: ["The students sat in the hall", "The students sitting in the hall", "The students are sitting in the hall", "The sitting students in the hall"], answer: 1 },
    ],
  },
  {
    slug: "noun-clauses",
    level: "IELTS",
    title: "Noun clauses: that / what / whether",
    titleUz: "Ot gaplar: that / what / whether",
    emoji: "🧩",
    highlights: ["that", "what", "whether", "the fact that", "what matters", "it is clear that"],
    explanation: [
      "Noun clause - butun bir gap ot vazifasida kelishi. Oddiy ot o'rniga fikrni qo'yasiz: \"His decision surprised me\" -> \"What he decided surprised me\". IELTS Writingda bu murakkab fikrni ixcham va akademik berishga yordam beradi.",
      "\"That\" clause da'vo, fikr, natija yoki faktni olib kiradi: \"It is clear that public transport reduces congestion.\" Bu shakl introduction va body paragraphlarda pozitsiyani aniq ochadi.",
      "\"What\" clause noma'lum yoki ta'kidlangan narsani bildiradi: \"What governments should prioritise is prevention.\" Bu cleft gapga o'xshaydi, lekin noun clause sifatida subject yoki object bo'lib turadi.",
      "\"Whether\" ikki ehtimolni bildiradi: \"The question is whether online learning can replace classrooms.\" IELTSda yes/no savolni rasmiy gapga aylantirish uchun juda kerak.",
    ],
    formula: "That + S + V · What + S + V · whether + S + V",
    keyPoints: [
      { title: "That clause", body: "Fakt yoki da'voni olib kiradi: It is evident that..., The data shows that..." },
      { title: "What clause", body: "Gapning muhim qismini otga aylantiradi: What matters is..., What this means is..." },
      { title: "Whether clause", body: "Ikki ehtimolli masalani rasmiy beradi: whether X can Y, whether X is necessary." },
    ],
    importantNotes: [
      "\"That\" ko'pincha tushib qolishi mumkin, lekin akademik yozuvda qoldirish fikrni aniqroq qiladi.",
      "\"Whether\" rasmiy uslubda \"if\"dan ko'ra yaxshi: The issue is whether..., not The issue is if...",
      "\"What\" clause subject bo'lsa, fe'l odatda birlikda keladi: What matters is quality.",
    ],
    examTips: [
      "Writing Task 2 introductionda \"It is often argued that...\" bilan topicni rasmiy oching.",
      "Conclusionda \"What this suggests is that...\" orqali asosiy fikrni kuchli umumlashtiring.",
    ],
    examples: [
      { en: "It is clear that affordable housing is becoming a major challenge.", uz: "Arzon uy-joy katta muammoga aylanayotgani aniq." },
      { en: "What many students need is more feedback, not more tests.", uz: "Ko'p talabalarga kerak bo'lgani ko'proq test emas, ko'proq fikr-mulohaza." },
      { en: "The question is whether governments should ban private cars in city centres.", uz: "Savol shuki, hukumatlar shahar markazlarida shaxsiy mashinalarni taqiqlashi kerakmi." },
      { en: "The fact that many graduates lack practical skills worries employers.", uz: "Ko'p bitiruvchilarda amaliy ko'nikma yetishmasligi ish beruvchilarni tashvishga soladi." },
      { en: "Research suggests that sleep affects memory and concentration.", uz: "Tadqiqotlar uyqu xotira va diqqatga ta'sir qilishini ko'rsatadi." },
      { en: "What this graph shows is a steady shift towards renewable energy.", uz: "Bu grafik ko'rsatayotgani qayta tiklanuvchi energiyaga barqaror siljishdir." },
    ],
    mistakes: [
      { wrong: "It is clear public transport reduces traffic.", right: "It is clear that public transport reduces traffic.", note: "Rasmiy yozuvda \"that\" fikr chegarasini aniq qiladi." },
      { wrong: "The issue is if children need homework.", right: "The issue is whether children need homework.", note: "Noun clause sifatida \"whether\" ko'proq akademik." },
      { wrong: "What people need are safety.", right: "What people need is safety.", note: "Butun \"what\" clause bitta fikr sifatida birlik fe'l oladi." },
    ],
    quiz: [
      { q: "___ concerns many parents is screen time.", options: ["That", "What", "Whether", "Which"], answer: 1 },
      { q: "It is undeniable ___ education shapes future opportunities.", options: ["what", "whether", "that", "which"], answer: 2 },
      { q: "The debate is ___ homework improves learning.", options: ["what", "whether", "that", "who"], answer: 1 },
      { q: "___ the policy succeeded remains unclear.", options: ["Whether", "That", "What", "Which"], answer: 0 },
      { q: "Eng akademik variant:", options: ["The problem is if people recycle.", "The issue is whether people recycle enough.", "People recycle? This is problem.", "If recycle is issue."], answer: 1 },
    ],
  },
  {
    slug: "modal-perfects",
    level: "IELTS",
    title: "Modal perfects",
    titleUz: "Modal perfect: should have / could have / might have",
    emoji: "🧭",
    highlights: ["should have", "could have", "might have", "must have", "cannot have", "would have"],
    explanation: [
      "Modal perfect - modal fe'l + have + V3. U o'tmishdagi ehtimol, tanqid, afsus yoki taxminni bildiradi. IELTS Speaking Part 3 da sabab va oqibatni chuqurroq tahlil qilish uchun juda foydali.",
      "\"Should have + V3\" o'tmishda qilinishi kerak bo'lgan, lekin qilinmagan ish: \"The council should have invested earlier.\" Bu tanqid yoki afsusni beradi.",
      "\"Could have + V3\" o'tmishdagi imkoniyat: \"The project could have succeeded with better planning.\" \"Might have + V3\" esa ehtimol: \"The decline might have been caused by higher prices.\"",
      "\"Must have + V3\" kuchli taxmin, \"cannot have + V3\" esa mumkin emas degan taxmin: \"Demand must have fallen\"; \"The figures cannot have been accurate.\"",
    ],
    formula: "modal + have + V3",
    keyPoints: [
      { title: "Criticism", body: "should have + V3 - o'tmishdagi noto'g'ri qaror yoki bajarilmagan mas'uliyat." },
      { title: "Possibility", body: "could have / might have + V3 - sababni ehtiyotkor taxmin qilish." },
      { title: "Deduction", body: "must have / cannot have + V3 - dalilga asoslangan kuchli xulosa." },
    ],
    importantNotes: [
      "\"Should have\"dan keyin doim V3 keladi: should have done, should have invested.",
      "\"Could have\" har doim \"qila olardi\" degani emas; ba'zan o'tmishdagi ehtimolni ham bildiradi.",
      "IELTSda ayblov ohangi juda kuchli bo'lmasin: should have o'rniga could have ba'zan yumshoqroq.",
    ],
    examTips: [
      "Task 2 bodyda policy critique uchun ishlating: The authorities should have..., This could have prevented...",
      "Task 1da sabab taxmini kerak bo'lsa \"may/might have contributed to\" aniq va ehtiyotkor chiqadi.",
    ],
    examples: [
      { en: "The government should have introduced stricter rules earlier.", uz: "Hukumat qattiqroq qoidalarni ertaroq joriy qilishi kerak edi." },
      { en: "The campaign could have reached more people with better funding.", uz: "Kampaniya yaxshiroq moliyalashtirilganda ko'proq odamga yetishi mumkin edi." },
      { en: "The rise in prices might have discouraged low-income families.", uz: "Narxlarning oshishi kam daromadli oilalarni to'xtatib qo'ygan bo'lishi mumkin." },
      { en: "The data must have been collected before the new law was passed.", uz: "Ma'lumotlar yangi qonun qabul qilinishidan oldin yig'ilgan bo'lsa kerak." },
      { en: "This result cannot have happened by chance.", uz: "Bu natija tasodifan yuz bergan bo'lishi mumkin emas." },
      { en: "Many problems would have been avoided with clearer communication.", uz: "Aniqroq kommunikatsiya bo'lganida ko'p muammolardan qochish mumkin edi." },
    ],
    mistakes: [
      { wrong: "The city should invested earlier.", right: "The city should have invested earlier.", note: "Modal perfectda \"have + V3\" tushmaydi." },
      { wrong: "It might has caused the fall.", right: "It might have caused the fall.", note: "Modaldan keyin \"has\" emas, doim \"have\"." },
      { wrong: "They must have went home.", right: "They must have gone home.", note: "\"Have\"dan keyin V3: gone, seen, done." },
    ],
    quiz: [
      { q: "The council ___ invested in buses earlier.", options: ["should have", "should has", "should", "has should"], answer: 0 },
      { q: "The decline ___ been caused by rising fees.", options: ["might has", "might have", "might had", "might"], answer: 1 },
      { q: "She ___ forgotten the deadline; she is always careful.", options: ["must have", "cannot have", "should have", "could"], answer: 1 },
      { q: "They must have ___ the report yesterday.", options: ["finish", "finished", "finishing", "finishes"], answer: 1 },
      { q: "Tanqid ma'nosini tanlang:", options: ["could have", "should have", "might have", "must have"], answer: 1 },
    ],
  },
  {
    slug: "subjunctive-recommendations",
    level: "IELTS",
    title: "Subjunctive after recommendations",
    titleUz: "Taklif va talabdan keyingi subjunctive",
    emoji: "📌",
    highlights: ["suggest that", "recommend that", "insist that", "demand that", "be", "do"],
    explanation: [
      "Subjunctive rasmiy ingliz tilida taklif, talab, muhimlik yoki zaruratdan keyin ishlatiladi. Shakl oddiy: suggest/recommend/insist/demand + that + subject + base verb.",
      "Eng muhim joyi: he/she/it bilan ham fe'lga -s qo'shilmaydi. \"The report recommends that the government invest\", \"invests\" emas.",
      "\"Be\" fe'li ham hamma shaxs bilan \"be\" bo'lib qoladi: \"It is essential that every child be protected.\" Bu formal ko'rinadi, lekin IELTS Writing uchun kuchli.",
      "Britaniya ingliz tilida ko'pincha \"should\" varianti ham ishlatiladi: \"The report recommends that the government should invest.\" Ikkalasi ham to'g'ri, lekin subjunctive ixchamroq.",
    ],
    formula: "verb/adjective + that + S + base verb",
    keyPoints: [
      { title: "Trigger words", body: "suggest, recommend, insist, demand, propose, essential, vital, important." },
      { title: "Base verb", body: "He invest, she be, everyone do - -s yoki past tense qo'shmang." },
      { title: "Writing value", body: "Policy recommendation gaplari professional chiqadi: It is vital that governments..." },
    ],
    importantNotes: [
      "\"Suggest\"dan keyin \"to\" ishlatmang: suggest that he go yoki suggest going.",
      "\"Recommend that\"dan keyin asosiy fe'l base form bo'ladi: be, do, invest.",
      "Juda ko'p ishlatmang; essayda 1-2 marta recommendation uchun yetarli.",
    ],
    examTips: [
      "Conclusionda yechim berishda ishlating: It is essential that policymakers invest in prevention.",
      "Formal letterda ham kuchli: I recommend that the deadline be extended.",
    ],
    examples: [
      { en: "Experts recommend that the government invest in early education.", uz: "Mutaxassislar hukumat erta ta'limga sarmoya kiritishini tavsiya qiladi." },
      { en: "It is essential that every applicant be treated fairly.", uz: "Har bir nomzodga adolatli munosabat qilinishi zarur." },
      { en: "The report suggests that schools provide more practical training.", uz: "Hisobot maktablar ko'proq amaliy trening berishini taklif qiladi." },
      { en: "Residents demanded that the factory reduce its emissions.", uz: "Aholi zavod chiqindilarini kamaytirishini talab qildi." },
      { en: "I propose that the meeting be postponed until Monday.", uz: "Yig'ilish dushanbagacha qoldirilishini taklif qilaman." },
      { en: "It is vital that children learn digital safety early.", uz: "Bolalar raqamli xavfsizlikni erta o'rganishi juda muhim." },
    ],
    mistakes: [
      { wrong: "Experts recommend the government to invest.", right: "Experts recommend that the government invest.", note: "\"Recommend\"dan keyin that-clause yoki gerund ishlatiladi." },
      { wrong: "It is essential that he is present.", right: "It is essential that he be present.", note: "Formal subjunctiveda \"be\" o'zgarmaydi." },
      { wrong: "The report suggests that the city invests more.", right: "The report suggests that the city invest more.", note: "Subjunctiveda he/she/it uchun -s yo'q." },
    ],
    quiz: [
      { q: "The report recommends that the council ___ more trees.", options: ["plants", "plant", "planted", "to plant"], answer: 1 },
      { q: "It is vital that every child ___ safe online.", options: ["is", "be", "are", "being"], answer: 1 },
      { q: "They demanded that the company ___ compensation.", options: ["pays", "paid", "pay", "to pay"], answer: 2 },
      { q: "To'g'ri variant:", options: ["I suggest him to apply.", "I suggest that he apply.", "I suggest that he applies.", "I suggest he to apply."], answer: 1 },
      { q: "Subjunctive trigger so'zni tanlang:", options: ["maybe", "recommend", "because", "however"], answer: 1 },
    ],
  },
  {
    slug: "advanced-comparisons",
    level: "IELTS",
    title: "Advanced comparisons",
    titleUz: "Murakkab taqqoslash shakllari",
    emoji: "⚖️",
    highlights: ["whereas", "while", "compared with", "twice as", "the more", "rather than"],
    explanation: [
      "IELTS Task 1 va Task 2 da taqqoslash grammatikasi juda muhim. Oddiy \"X is bigger than Y\"dan tashqari, contrast, ratio, degree va parallel change shakllarini bilish bandni oshiradi.",
      "\"Whereas/while\" ikki fikrni kontrast qiladi: \"Whereas car use increased, bus travel declined.\" Bu Task 1 overview va bodyda juda kuchli.",
      "\"Twice/three times as ... as\" nisbatni beradi: \"The figure was twice as high as in 2010.\" \"Compared with/to\" esa rasmiy taqqoslash: \"Compared with rural areas, cities offer more jobs.\"",
      "\"The more..., the more...\" ikki narsa birga o'zgarishini bildiradi: \"The more cities expand, the more pressure is placed on infrastructure.\"",
    ],
    formula: "whereas/while · compared with · twice as ... as · the more..., the more...",
    keyPoints: [
      { title: "Contrast", body: "whereas / while - ikki trend yoki fikr qarama-qarshi bo'lsa." },
      { title: "Ratio", body: "twice as high as, three times as many as - sonli taqqoslash uchun." },
      { title: "Parallel change", body: "the more..., the more... - sabab-oqibat yoki birga o'sish." },
    ],
    importantNotes: [
      "\"Compared to\" va \"compared with\" ikkalasi ishlaydi, lekin Task 1da \"compared with\" ko'proq neytral.",
      "\"Than\"dan keyin parallel structure saqlang: more effective than expensive campaigns emas, more effective than campaigns.",
      "\"Whereas\"dan keyin comma ishlatilishi mumkin, ayniqsa gap boshida kelsa.",
    ],
    examTips: [
      "Task 1 overviewda kamida bitta contrast sentence yozing: Whereas X rose, Y fell.",
      "Task 2da balanced argument uchun \"rather than\" va \"compared with\"ni ishlating.",
    ],
    examples: [
      { en: "Whereas the number of cyclists rose sharply, car use remained stable.", uz: "Velosipedchilar soni keskin oshgan bo'lsa, mashina ishlatish barqaror qoldi." },
      { en: "The unemployment rate was twice as high in rural areas as in cities.", uz: "Ishsizlik darajasi qishloqlarda shaharlardagidan ikki baravar yuqori edi." },
      { en: "Compared with traditional classrooms, online courses offer greater flexibility.", uz: "An'anaviy sinflar bilan solishtirganda, onlayn kurslar ko'proq moslashuvchanlik beradi." },
      { en: "The more people rely on cars, the worse congestion becomes.", uz: "Odamlar mashinalarga qanchalik ko'p tayansa, tirbandlik shunchalik yomonlashadi." },
      { en: "This approach is more practical than simply raising taxes.", uz: "Bu yondashuv shunchaki soliq oshirishdan ko'ra amaliyroq." },
      { en: "Public transport is not as convenient as private cars in many regions.", uz: "Ko'p hududlarda jamoat transporti shaxsiy mashinalardek qulay emas." },
    ],
    mistakes: [
      { wrong: "The figure was two times higher than 2010.", right: "The figure was twice as high as in 2010.", note: "Yillar bilan taqqoslaganda \"as in 2010\" tabiiyroq." },
      { wrong: "Compared cities, villages have fewer jobs.", right: "Compared with cities, villages have fewer jobs.", note: "\"Compared\"dan keyin with/to kerak." },
      { wrong: "The more you study, you get better.", right: "The more you study, the better you get.", note: "Ikkala qism ham \"the + comparative\" bilan quriladi." },
    ],
    quiz: [
      { q: "The figure was ___ high as in 2000.", options: ["twice as", "twice than", "two as", "double than"], answer: 0 },
      { q: "___ rural areas, cities offer more services.", options: ["Compared with", "Comparing", "Compare", "Compared"], answer: 0 },
      { q: "The more people drive, ___ pollution increases.", options: ["more", "the more", "than more", "as more"], answer: 1 },
      { q: "___ sales rose, profits fell.", options: ["Whereas", "Because", "So that", "Unless"], answer: 0 },
      { q: "To'g'ri variant:", options: ["not as cheap than", "not so cheap than", "not as cheap as", "not cheap as"], answer: 2 },
    ],
  },
  {
    slug: "parallelism",
    level: "IELTS",
    title: "Parallelism",
    titleUz: "Parallel qurilish",
    emoji: "🧱",
    highlights: ["not only", "but also", "both", "and", "either", "or", "parallel"],
    explanation: [
      "Parallelism - ro'yxat yoki juft fikrlarda bir xil grammatik shaklni saqlash. Bu essayni ravon, aniq va professional ko'rsatadi.",
      "Agar ro'yxat fe'l bilan boshlangan bo'lsa, hammasi fe'l bo'lsin: \"to reduce costs, improve safety and protect workers\". Bitta qism ot, boshqasi fe'l bo'lsa, gap notekis eshitiladi.",
      "\"Not only... but also\", \"both... and\", \"either... or\" kabi juft bog'lovchilarda ikkala tomondagi grammatik shakl bir xil bo'lishi kerak.",
      "IELTS Writingda parallelism coherence va grammar range ikkalasiga ham yordam beradi, chunki o'quvchi fikrni tezroq ushlaydi.",
    ],
    formula: "same form + same form + same form",
    keyPoints: [
      { title: "Lists", body: "Ro'yxatda fe'l-fe'l-fe'l yoki ot-ot-ot shaklini saqlang." },
      { title: "Paired connectors", body: "both A and B, either A or B, not only A but also B - A va B parallel bo'lsin." },
      { title: "Essay rhythm", body: "Parallel sentence xotirada qoladi va examiner uchun o'qilishi oson." },
    ],
    importantNotes: [
      "Parallelism grammar xato bo'lmasa ham style xatosini tuzatadi.",
      "\"Not only\" gap boshida kelsa inversion kerak bo'lishi mumkin: Not only does it save money...",
      "Juda uzun parallel ro'yxat yozmang; 3 qism yetarli.",
    ],
    examTips: [
      "Body paragraph topic sentence uchun parallel trio yozing: cheaper, safer and more accessible.",
      "Conclusionda policy recommendationni parallel qiling: regulate, educate and invest.",
    ],
    examples: [
      { en: "The policy aims to reduce costs, improve safety and protect workers.", uz: "Siyosat xarajatlarni kamaytirish, xavfsizlikni oshirish va ishchilarni himoya qilishni maqsad qiladi." },
      { en: "Online learning is both flexible and affordable.", uz: "Onlayn ta'lim ham moslashuvchan, ham arzon." },
      { en: "The city needs not only better roads but also cleaner buses.", uz: "Shaharga nafaqat yaxshiroq yo'llar, balki tozaroq avtobuslar ham kerak." },
      { en: "Students should learn how to analyse data, evaluate sources and present ideas.", uz: "Talabalar ma'lumotni tahlil qilish, manbalarni baholash va fikrlarni taqdim etishni o'rganishi kerak." },
      { en: "The plan is practical, affordable and easy to implement.", uz: "Reja amaliy, arzon va amalga oshirish oson." },
      { en: "Governments can either raise taxes or reduce spending.", uz: "Hukumatlar yo soliqlarni oshirishi, yo xarajatlarni kamaytirishi mumkin." },
    ],
    mistakes: [
      { wrong: "The course improves speaking, writing and how to listen.", right: "The course improves speaking, writing and listening.", note: "Ro'yxatdagi uchala qism bir xil shaklda bo'lishi kerak." },
      { wrong: "It is both cheap and saves time.", right: "It is both cheap and time-saving.", note: "\"Both\"dan keyingi ikki qism sifat shaklida parallel bo'lsin." },
      { wrong: "Students learn to read, writing and speak.", right: "Students learn to read, write and speak.", note: "\"To\" birinchi fe'lga tegishli, qolganlari base verb." },
    ],
    quiz: [
      { q: "Parallel variantni tanlang:", options: ["to read, writing and speak", "reading, writing and speaking", "reading, to write and speak", "read, writing and spoken"], answer: 1 },
      { q: "The system is both efficient and ___.", options: ["it saves money", "affordable", "saving money", "costs less"], answer: 1 },
      { q: "Governments should regulate, educate and ___.", options: ["investment", "invest", "to invest", "investing"], answer: 1 },
      { q: "Not only... juftligi:", options: ["and also", "but also", "or also", "than also"], answer: 1 },
      { q: "Xato variant:", options: ["safe, cheap and reliable", "to study, work and rest", "both useful and practical", "learn reading, to write and speak"], answer: 3 },
    ],
  },
  {
    slug: "determiners-quantifiers",
    level: "IELTS",
    title: "Determiners & quantifiers",
    titleUz: "Aniqlovchi va miqdor so'zlari",
    emoji: "🔢",
    highlights: ["many", "much", "few", "little", "a number of", "the number of", "amount of", "number of"],
    explanation: [
      "IELTSda countable/uncountable xatolari tez ko'rinadi: many people, much information, a few solutions, little evidence. Determiner noun turiga mos bo'lishi shart.",
      "\"A number of\" ko'plik ma'nosida: \"A number of students are...\". \"The number of\" esa bitta ko'rsatkich: \"The number of students is...\". Bu Task 1 uchun juda muhim.",
      "\"Amount of\" uncountable noun bilan, \"number of\" countable plural bilan ishlatiladi: amount of waste, number of cars.",
      "\"Few\" salbiy ohang (kam, yetarli emas), \"a few\" ijobiyroq (bir nechta). \"Little\" va \"a little\" ham shunday farqlanadi.",
    ],
    formula: "many + countable plural · much + uncountable · a number of + plural · the number of + singular verb",
    keyPoints: [
      { title: "Countable", body: "many, few, several, a number of + plural noun." },
      { title: "Uncountable", body: "much, little, amount of, a great deal of + uncountable noun." },
      { title: "Agreement", body: "A number of people are; the number of people is." },
    ],
    importantNotes: [
      "\"Information\", \"advice\", \"evidence\", \"research\" odatda uncountable.",
      "\"People\" plural, lekin \"the number of people\" bitta son sifatida singular verb oladi.",
      "Task 1da \"amount\" va \"number\"ni adashtirish grammar va lexical accuracyga ta'sir qiladi.",
    ],
    examTips: [
      "Task 1da countable nounlar uchun \"the number of\", uncountable uchun \"the amount of\" ishlating.",
      "Task 2da \"many people\" o'rniga ba'zan \"a significant number of people\" yozing.",
    ],
    examples: [
      { en: "A number of students are choosing vocational courses.", uz: "Bir qancha talabalar kasbiy kurslarni tanlamoqda." },
      { en: "The number of students choosing science has increased.", uz: "Ilmiy yo'nalishni tanlayotgan talabalar soni oshdi." },
      { en: "There is little evidence to support this claim.", uz: "Bu da'voni qo'llab-quvvatlaydigan dalil kam." },
      { en: "The amount of plastic waste has fallen slightly.", uz: "Plastik chiqindi miqdori biroz kamaydi." },
      { en: "Several measures could reduce traffic congestion.", uz: "Bir nechta chora tirbandlikni kamaytirishi mumkin." },
      { en: "Much of the research focuses on urban children.", uz: "Tadqiqotlarning katta qismi shahar bolalariga qaratilgan." },
    ],
    mistakes: [
      { wrong: "Many information is available online.", right: "Much information is available online.", note: "\"Information\" uncountable, shuning uchun much." },
      { wrong: "The number of cars have risen.", right: "The number of cars has risen.", note: "\"The number\" subject bo'lib, singular verb oladi." },
      { wrong: "The amount of people increased.", right: "The number of people increased.", note: "People countable plural, \"number\" kerak." },
    ],
    quiz: [
      { q: "There is ___ evidence for this view.", options: ["many", "much", "few", "several"], answer: 1 },
      { q: "A number of people ___ working remotely.", options: ["is", "are", "was", "be"], answer: 1 },
      { q: "The number of cars ___ increased.", options: ["have", "are", "has", "were"], answer: 2 },
      { q: "The ___ of waste fell.", options: ["number", "amount", "many", "few"], answer: 1 },
      { q: "\"Advice\" bilan to'g'ri miqdor:", options: ["many advice", "several advice", "much advice", "a few advice"], answer: 2 },
    ],
  },
  {
    slug: "subject-verb-agreement-advanced",
    level: "IELTS",
    title: "Advanced subject-verb agreement",
    titleUz: "Murakkab ega-fe'l moslashuvi",
    emoji: "🎯",
    highlights: ["the number of", "a number of", "neither", "either", "each", "data", "percent"],
    explanation: [
      "IELTS Writingda murakkab subject uzun bo'lsa, verb agreement xatosi ko'p chiqadi. Asosiy qoida: fe'l eng yaqin otga emas, haqiqiy subjectga moslashadi.",
      "\"The number of students is\" lekin \"A number of students are\". Birinchisi bitta raqam, ikkinchisi bir qancha odamlar.",
      "\"Each/every/neither/either\" odatda singular verb oladi: \"Each of the options has advantages.\" \"None\" esa kontekstga qarab singular yoki plural bo'lishi mumkin.",
      "Foizlarda fe'l keyingi noun turiga moslashadi: \"50% of the water is wasted\" lekin \"50% of the students are absent.\"",
    ],
    formula: "real subject + matching verb · not nearest noun",
    keyPoints: [
      { title: "Long subjects", body: "Subjectni toping, keyin verbni tekshiring: The list of problems is..." },
      { title: "Quantity phrases", body: "the number is; a number are; percentage noun turiga qaraydi." },
      { title: "Indefinite words", body: "each/every/either/neither ko'pincha singular verb oladi." },
    ],
    importantNotes: [
      "Prepositional phrase ichidagi noun verbni boshqarmaydi: The quality of services is...",
      "Data akademik yozuvda ko'pincha plural ham bo'lishi mumkin, lekin IELTSda \"the data shows\" ham qabul qilinadi.",
      "Long sentence yozganda avval subjectni underline qiling, keyin verbni tanlang.",
    ],
    examTips: [
      "Task 1da \"the percentage of people who...\" singular: The percentage ... was.",
      "Task 2da long noun phrase ishlatsangiz, verb agreementni alohida tekshiring.",
    ],
    examples: [
      { en: "The quality of public services has improved.", uz: "Jamoat xizmatlari sifati yaxshilandi." },
      { en: "A number of residents are concerned about noise.", uz: "Bir qancha aholi shovqindan xavotirda." },
      { en: "The number of residents is expected to rise.", uz: "Aholi soni oshishi kutilmoqda." },
      { en: "Each of these solutions has clear benefits.", uz: "Bu yechimlarning har biri aniq foydaga ega." },
      { en: "Fifty percent of the water is wasted during production.", uz: "Suvning 50 foizi ishlab chiqarish jarayonida isrof qilinadi." },
      { en: "Fifty percent of the workers are employed part-time.", uz: "Ishchilarning 50 foizi yarim stavkada ishlaydi." },
    ],
    mistakes: [
      { wrong: "The quality of schools are improving.", right: "The quality of schools is improving.", note: "Subject \"quality\" - singular." },
      { wrong: "Each of the methods have drawbacks.", right: "Each of the methods has drawbacks.", note: "\"Each\" singular verb oladi." },
      { wrong: "A number of people is unhappy.", right: "A number of people are unhappy.", note: "\"A number of\" plural ma'noda." },
    ],
    quiz: [
      { q: "The quality of roads ___ improved.", options: ["have", "has", "are", "were"], answer: 1 },
      { q: "A number of students ___ absent.", options: ["is", "are", "has", "be"], answer: 1 },
      { q: "Each of the proposals ___ expensive.", options: ["is", "are", "were", "be"], answer: 0 },
      { q: "The percentage of people working from home ___ risen.", options: ["have", "are", "has", "were"], answer: 2 },
      { q: "50% of the children ___ under ten.", options: ["is", "are", "has", "be"], answer: 1 },
    ],
  },
  {
    slug: "discourse-markers-cohesion",
    level: "IELTS",
    title: "Discourse markers for cohesion",
    titleUz: "Bog'lovchi iboralar va cohesion",
    emoji: "🔗",
    highlights: ["however", "therefore", "nevertheless", "moreover", "in contrast", "as a result"],
    explanation: [
      "Discourse marker - gaplar orasidagi mantiqiy aloqani ko'rsatadigan signal. IELTS Coherence and Cohesion mezonida ular muhim, lekin haddan tashqari ko'p bo'lsa mechanical ko'rinadi.",
      "Contrast: however, nevertheless, in contrast, whereas. Addition: moreover, furthermore, in addition. Result: therefore, consequently, as a result. Example: for instance, such as.",
      "Punctuation muhim: \"However,\" gap boshida comma bilan keladi; ikki mustaqil gapni comma bilan ulab yubormang. \"This is costly. However, it is necessary.\"",
      "Eng yaxshi cohesion faqat marker emas; pronoun reference, repeated key nouns va paragraph logic ham kerak. Marker fikrni yopishtirmaydi, faqat mavjud aloqani ko'rsatadi.",
    ],
    formula: "idea A. However, idea B. · idea A; therefore, idea B",
    keyPoints: [
      { title: "Choose meaning", body: "Har markerning mantiqiy vazifasi bor: contrast, addition, result, example." },
      { title: "Punctuation", body: "However/therefore gap boshida comma oladi; semicolon advanced uslub beradi." },
      { title: "Do not overuse", body: "Har gapni marker bilan boshlamang; natural flow ham muhim." },
    ],
    importantNotes: [
      "\"However\" va \"although\" bir xil grammatikada ishlamaydi: Although X, Y. X. However, Y.",
      "\"Moreover\" faqat qo'shimcha kuchli dalil uchun; oddiy ro'yxat uchun har safar ishlatmang.",
      "\"As a result\" sababdan keyin keladi, misol uchun emas.",
    ],
    examTips: [
      "Har body paragraphda 2-3 ta marker yetarli; fikrlar o'zi mantiqan ulangan bo'lsin.",
      "Task 1da overviewdan keyin \"In contrast\" bilan qarama-qarshi trendni ko'rsatish juda foydali.",
    ],
    examples: [
      { en: "The policy is expensive. However, it may save money in the long term.", uz: "Siyosat qimmat. Biroq uzoq muddatda pul tejashi mumkin." },
      { en: "Many people work longer hours; therefore, stress levels have increased.", uz: "Ko'p odamlar uzoqroq ishlaydi; shuning uchun stress darajasi oshdi." },
      { en: "Moreover, public transport reduces the need for parking spaces.", uz: "Bundan tashqari, jamoat transporti parking joylariga ehtiyojni kamaytiradi." },
      { en: "In contrast, rural areas experienced a gradual decline.", uz: "Aksincha, qishloq hududlarida bosqichma-bosqich pasayish kuzatildi." },
      { en: "For instance, many schools now use tablets instead of textbooks.", uz: "Masalan, ko'p maktablar endi darsliklar o'rniga planshetlardan foydalanadi." },
      { en: "Nevertheless, the benefits should not be ignored.", uz: "Shunga qaramay, foydalarni e'tibordan chetda qoldirmaslik kerak." },
    ],
    mistakes: [
      { wrong: "Although it is expensive. It is useful.", right: "Although it is expensive, it is useful.", note: "\"Although\" clause bosh gapga ulanadi." },
      { wrong: "It is expensive, however it is useful.", right: "It is expensive; however, it is useful.", note: "Ikki mustaqil gapda semicolon yoki full stop kerak." },
      { wrong: "Moreover, pollution fell because fewer cars were used. (natija uchun)", right: "As a result, pollution fell because fewer cars were used.", note: "Natija uchun \"as a result/therefore\" ishlating." },
    ],
    quiz: [
      { q: "Contrast marker:", options: ["moreover", "however", "for example", "therefore"], answer: 1 },
      { q: "Result marker:", options: ["as a result", "in addition", "whereas", "for instance"], answer: 0 },
      { q: "To'g'ri punctuation:", options: ["It is costly, however it works.", "It is costly. However, it works.", "It is costly however, it works.", "It is costly however it works."], answer: 1 },
      { q: "Addition marker:", options: ["nevertheless", "therefore", "moreover", "in contrast"], answer: 2 },
      { q: "Although gapini to'g'ri tugating:", options: ["Although it rained. We went out.", "Although it rained, we went out.", "Although it rained however we went out.", "Although, it rained we went out."], answer: 1 },
    ],
  },
  {
    slug: "fronting-emphasis",
    level: "IELTS",
    title: "Fronting for emphasis",
    titleUz: "Urg'u uchun gap boshiga chiqarish",
    emoji: "🚦",
    highlights: ["fronting", "as for", "regarding", "what matters", "the problem is", "more important"],
    explanation: [
      "Fronting - odatda keyin keladigan bo'lakni gap boshiga chiqarib, urg'u berish. Bu speakingda tabiiy, writingda esa ehtiyotkor ishlatilsa professional ko'rinadi.",
      "Topic fronting: \"This problem, governments cannot ignore.\" Formal essayda buni ko'p ishlatmang, lekin \"As for funding\" yoki \"Regarding safety\" kabi shakllar foydali.",
      "Adjective/adverb fronting: \"More important is the need to protect children.\" Bu inversionga yaqin, lekin har doim yordamchi fe'l talab qilmaydi.",
      "IELTS Speakingda fronting fikrni tartiblaydi: \"As for public transport, I think it needs serious investment.\"",
    ],
    formula: "fronted phrase + comma + main clause",
    keyPoints: [
      { title: "Topic shift", body: "As for / Regarding / In terms of - yangi aspektga o'tish." },
      { title: "Emphasis", body: "More important is..., Equally serious is... kabi shakllar urg'u beradi." },
      { title: "Control", body: "Writingda haddan tashqari colloquial frontingdan qoching." },
    ],
    importantNotes: [
      "\"Regarding\"dan keyin noun yoki gerund keladi: regarding safety, regarding reducing costs.",
      "Fronting comma talab qiladi, ayniqsa gap boshidagi uzun phrase bo'lsa.",
      "Har gapni fronting bilan boshlamang; u faqat urg'u kerak joyda ishlasin.",
    ],
    examTips: [
      "Speaking Part 3da yangi nuqtani boshlash uchun: As for the long-term effects, ...",
      "Writingda body paragraphning ikkinchi dalilini ajratish uchun: More important is the impact on children.",
    ],
    examples: [
      { en: "As for public transport, it needs more reliable funding.", uz: "Jamoat transportiga kelsak, unga barqarorroq moliya kerak." },
      { en: "Regarding online safety, parents should receive clearer guidance.", uz: "Onlayn xavfsizlik borasida ota-onalar aniqroq yo'riqnoma olishi kerak." },
      { en: "More important is the effect on children's mental health.", uz: "Muhimrog'i - bolalarning ruhiy salomatligiga ta'siri." },
      { en: "In terms of cost, prevention is often cheaper than treatment.", uz: "Xarajat nuqtayi nazaridan profilaktika ko'pincha davolashdan arzonroq." },
      { en: "Equally serious is the lack of trained teachers.", uz: "Teng darajada jiddiy narsa - malakali o'qituvchilar yetishmasligi." },
      { en: "This issue, policymakers can no longer ignore.", uz: "Bu masalani siyosatchilar endi e'tiborsiz qoldira olmaydi." },
    ],
    mistakes: [
      { wrong: "Regarding to safety, schools need rules.", right: "Regarding safety, schools need rules.", note: "\"Regarding\"dan keyin \"to\" kelmaydi." },
      { wrong: "As for the cost it is high.", right: "As for the cost, it is high.", note: "Fronted phrase dan keyin comma qo'ying." },
      { wrong: "More important are the need for safety.", right: "More important is the need for safety.", note: "Subject \"the need\" singular." },
    ],
    quiz: [
      { q: "___ public health, prevention is cheaper.", options: ["Regarding to", "Regarding", "Regarded", "Regards"], answer: 1 },
      { q: "As for the budget, ___", options: ["it is limited.", "is limited it.", "limited it is.", "it limited."], answer: 0 },
      { q: "___ important is the effect on children.", options: ["More", "Most", "Many", "Much"], answer: 0 },
      { q: "Fronting punctuation:", options: ["In terms of cost prevention is cheaper.", "In terms of cost, prevention is cheaper.", "In terms, of cost prevention is cheaper.", "In terms of, cost prevention is cheaper."], answer: 1 },
      { q: "Speaking uchun tabiiy opener:", options: ["As for transport, I think...", "Regarding to transport...", "Transport as for think...", "For as transport..."], answer: 0 },
    ],
  },
  {
    slug: "ellipsis-substitution",
    level: "IELTS",
    title: "Ellipsis & substitution",
    titleUz: "Qisqartirish va almashtirish",
    emoji: "🪄",
    highlights: ["ellipsis", "substitution", "do so", "ones", "so", "not"],
    explanation: [
      "Ellipsis - takroriy so'zni tushirib qoldirish. Substitution - takrorni boshqa so'z bilan almashtirish. Bu natural fluency beradi va repetitionni kamaytiradi.",
      "Substitution: \"Some people support the policy, but others do not.\" Bu yerda \"do not\" = do not support the policy. \"This one/these ones\" noun takrorini kamaytiradi.",
      "\"Do so\" rasmiy replacement: \"Governments should invest in railways, and they should do so quickly.\" \"So/not\" butun fikrni almashtiradi: \"I hope so\", \"I think not\".",
      "IELTSda repetitionni kamaytirish lexical resourcega yordam beradi, lekin meaning noaniq qolmasin. Har doim o'quvchi nimani almashtirayotganingizni bilishi kerak.",
    ],
    formula: "repeat idea -> do so / so / not / one(s)",
    keyPoints: [
      { title: "Avoid repetition", body: "Bir xil noun yoki verb phrase takrorlansa, substitution ishlating." },
      { title: "Keep clarity", body: "Almashtirilayotgan fikr oldingi gapda aniq bo'lishi shart." },
      { title: "Formal option", body: "\"Do so\" essay uchun natural va rasmiy." },
    ],
    importantNotes: [
      "\"Ones\" countable plural noun o'rnini bosadi, uncountable uchun ishlamaydi.",
      "\"Do so\" odatda action verb o'rniga ishlaydi, state verb bilan g'alati chiqishi mumkin.",
      "Too much ellipsis writingni noaniq qiladi; clarity birinchi o'rinda.",
    ],
    examTips: [
      "Task 2da \"governments should do so\" bilan oldingi actionni takrorlamasdan bog'lang.",
      "Speakingda qisqa javoblar uchun: I think so, I hope not, Some do, others don't.",
    ],
    examples: [
      { en: "Some parents limit screen time, while others do not.", uz: "Ba'zi ota-onalar ekran vaqtini cheklaydi, boshqalari esa bunday qilmaydi." },
      { en: "If governments can reduce waste, they should do so immediately.", uz: "Hukumatlar chiqindini kamaytira olsa, buni darhol qilishi kerak." },
      { en: "Private schools often have more resources than public ones.", uz: "Xususiy maktablarda ko'pincha davlat maktablariga qaraganda ko'proq resurs bor." },
      { en: "The first solution is costly; the second one is more realistic.", uz: "Birinchi yechim qimmat; ikkinchisi realroq." },
      { en: "Many experts predicted a decline, but this did not happen.", uz: "Ko'p mutaxassislar pasayishni taxmin qilgan, ammo bu yuz bermadi." },
      { en: "Will this trend continue? The data suggests so.", uz: "Bu trend davom etadimi? Ma'lumotlar shuni ko'rsatadi." },
    ],
    mistakes: [
      { wrong: "This information is more reliable than the online ones.", right: "This information is more reliable than online information.", note: "\"Information\" uncountable, \"ones\" ishlatilmaydi." },
      { wrong: "Governments should reduce waste and do it quickly. (formal)", right: "Governments should reduce waste and do so quickly.", note: "Essayda actionni almashtirish uchun \"do so\" yaxshiroq." },
      { wrong: "Some people agree, others.", right: "Some people agree, while others do not.", note: "Ellipsis meaningni tushunarli qoldirishi kerak." },
    ],
    quiz: [
      { q: "Private cars are faster than public ___.", options: ["one", "ones", "so", "do"], answer: 1 },
      { q: "They should invest in buses and should ___ quickly.", options: ["do so", "do ones", "so do", "do"], answer: 0 },
      { q: "Will prices rise? The evidence suggests ___.", options: ["ones", "do", "so", "not do"], answer: 2 },
      { q: "\"Information\" bilan qaysi substitution noto'g'ri?", options: ["this information", "such information", "the online ones", "it"], answer: 2 },
      { q: "Some support the ban, while others ___.", options: ["not", "do not", "ones", "so"], answer: 1 },
    ],
  },
  {
    slug: "noun-phrase-compression",
    level: "IELTS",
    title: "Noun phrase compression",
    titleUz: "Ot birikmalarini zichlashtirish",
    emoji: "📦",
    highlights: ["noun phrase", "of", "in", "with", "rapid growth", "a lack of", "the impact of"],
    explanation: [
      "Academic English ko'pincha uzun fikrni noun phrase ichiga joylaydi: \"cities are growing quickly\" -> \"rapid urban growth\". Bu writingni zich, rasmiy va aniq qiladi.",
      "Asosiy patternlar: adjective + noun (rapid growth), noun + of + noun (the impact of tourism), noun + in + noun (an increase in demand), noun + with + noun (families with low incomes).",
      "Compression fikrni qisqartiradi, lekin haddan tashqari zich noun phrase o'qishni qiyinlashtiradi. Har bir phrase aniq va tabiiy bo'lishi kerak.",
      "Task 1da trendlar uchun juda zarur: \"a slight decrease in sales\", \"a dramatic rise in energy consumption\", \"the proportion of people aged over 65\".",
    ],
    formula: "adjective + noun · noun + of/in/with + noun",
    keyPoints: [
      { title: "Trend language", body: "a rise in, a fall in, an increase in, a decline in + noun." },
      { title: "Academic density", body: "Verb phrase ni noun phrase ga aylantirib, fikrni ixcham qiling." },
      { title: "Clarity limit", body: "Bir noun phrase ichida 3-4 dan ortiq modifier yig'mang." },
    ],
    importantNotes: [
      "\"Increase of prices\" emas, odatda \"increase in prices\".",
      "\"Lack of\"dan keyin noun/gerund keladi: lack of funding, lack of training.",
      "Uzun noun phrase subject bo'lsa, verb agreementni tekshiring.",
    ],
    examTips: [
      "Task 1da har paragraphda kamida 2 ta trend noun phrase ishlating.",
      "Task 2da argumentni kuchaytirish uchun: the long-term impact of..., the lack of access to...",
    ],
    examples: [
      { en: "Rapid urban growth has increased pressure on public services.", uz: "Shaharlarning tez o'sishi jamoat xizmatlariga bosimni oshirdi." },
      { en: "The lack of affordable housing affects young families.", uz: "Arzon uy-joy yetishmasligi yosh oilalarga ta'sir qiladi." },
      { en: "A gradual decline in birth rates can be seen after 2015.", uz: "2015-yildan keyin tug'ilish darajasida bosqichma-bosqich pasayish ko'rinadi." },
      { en: "The impact of tourism on local culture is complex.", uz: "Turizmning mahalliy madaniyatga ta'siri murakkab." },
      { en: "Families with low incomes need targeted support.", uz: "Kam daromadli oilalar maqsadli yordamga muhtoj." },
      { en: "A sharp rise in energy consumption occurred during winter.", uz: "Qishda energiya iste'molida keskin o'sish yuz berdi." },
    ],
    mistakes: [
      { wrong: "A rise of demand", right: "A rise in demand", note: "Trend nounlari odatda \"in\" bilan ishlatiladi." },
      { wrong: "The lack funding is serious.", right: "The lack of funding is serious.", note: "\"Lack\"dan keyin \"of\" kerak." },
      { wrong: "The rapid growth cities causes problems.", right: "The rapid growth of cities causes problems.", note: "Noun + of + noun aloqasini qo'shing." },
    ],
    quiz: [
      { q: "A sharp rise ___ prices was recorded.", options: ["of", "in", "on", "at"], answer: 1 },
      { q: "The lack ___ training is a major problem.", options: ["in", "for", "of", "with"], answer: 2 },
      { q: "\"Cities are growing rapidly\" akademik phrase:", options: ["rapid urban growth", "rapidly city grow", "growth rapid cities", "urban grow rapid"], answer: 0 },
      { q: "Families ___ low incomes need help.", options: ["of", "with", "in", "for"], answer: 1 },
      { q: "The impact ___ tourism is debated.", options: ["of", "in", "with", "at"], answer: 0 },
    ],
  },
  {
    slug: "punctuation-for-complex-sentences",
    level: "IELTS",
    title: "Punctuation for complex sentences",
    titleUz: "Murakkab gaplarda tinish belgilari",
    emoji: "✒️",
    highlights: ["comma", "semicolon", "colon", "although", "however", "which"],
    explanation: [
      "IELTS Writingda punctuation grammar scorega bevosita ta'sir qiladi. Ko'p o'quvchilar grammarni biladi, lekin comma splice yoki fragment sabab band yo'qotadi.",
      "Dependent clause gap boshida kelsa comma qo'ying: \"Although the policy is costly, it is necessary.\" Agar dependent clause keyin kelsa comma har doim ham kerak emas: \"It is necessary because it protects children.\"",
      "Semicolon ikki yaqin mustaqil gapni bog'laydi: \"The policy is costly; however, it is necessary.\" Colon esa izoh yoki ro'yxatni ochadi: \"The reason is simple: prevention is cheaper.\"",
      "Relative clause punctuation ma'noni o'zgartiradi: \"Students who study daily improve\" (faqat har kuni o'qiydiganlar). \"Students, who often study under pressure, need support\" (barcha talabalar haqida qo'shimcha izoh).",
    ],
    formula: "Dependent clause, main clause · sentence; however, sentence · sentence: explanation",
    keyPoints: [
      { title: "Comma", body: "Gap boshidagi although/because/if clause dan keyin comma qo'ying." },
      { title: "Semicolon", body: "Ikki mustaqil gapni professional bog'laydi, ayniqsa however/therefore bilan." },
      { title: "Relative clauses", body: "Defining clause comma olmaydi; non-defining clause comma oladi." },
    ],
    importantNotes: [
      "Comma splice xato: ikki mustaqil gapni faqat comma bilan ulamang.",
      "\"However\" oddiy bog'lovchi emas; undan oldin full stop yoki semicolon kerak.",
      "Colon oldidan mustaqil gap bo'lishi kerak: The reason is simple: ...",
    ],
    examTips: [
      "Essayni tekshirganda har bir comma oldi-ortidagi gap mustaqilmi yoki dependentmi, shuni ko'ring.",
      "Semicolonni 1-2 marta to'g'ri ishlatish writingni professional ko'rsatadi.",
    ],
    examples: [
      { en: "Although the policy is expensive, it protects vulnerable families.", uz: "Siyosat qimmat bo'lsa-da, himoyaga muhtoj oilalarni himoya qiladi." },
      { en: "The policy is expensive; however, it protects vulnerable families.", uz: "Siyosat qimmat; biroq u himoyaga muhtoj oilalarni himoya qiladi." },
      { en: "The reason is simple: prevention costs less than treatment.", uz: "Sabab oddiy: profilaktika davolashdan arzonroq." },
      { en: "Students who receive feedback usually improve faster.", uz: "Fikr-mulohaza oladigan talabalar odatda tezroq yaxshilanadi." },
      { en: "Online courses, which are often cheaper, can widen access.", uz: "Ko'pincha arzonroq bo'lgan onlayn kurslar imkoniyatni kengaytirishi mumkin." },
      { en: "If cities invest in buses, congestion may fall.", uz: "Shaharlar avtobuslarga sarmoya kiritsa, tirbandlik kamayishi mumkin." },
    ],
    mistakes: [
      { wrong: "The policy is costly, however it is useful.", right: "The policy is costly; however, it is useful.", note: "\"However\"dan oldin semicolon yoki full stop kerak." },
      { wrong: "Although it is difficult. It is necessary.", right: "Although it is difficult, it is necessary.", note: "\"Although\" clause yolg'iz sentence bo'lib qolmasin." },
      { wrong: "The reason is: prevention is cheaper.", right: "The reason is simple: prevention is cheaper.", note: "Colon oldidan to'liq mustaqil gap bo'lsin." },
    ],
    quiz: [
      { q: "To'g'ri punctuation:", options: ["Although it is costly. It works.", "Although it is costly, it works.", "Although, it is costly it works.", "Although it is costly it works."], answer: 1 },
      { q: "The policy is costly ___ however, it works.", options: [",", ";", ":", "and"], answer: 1 },
      { q: "Colon oldidan nima kerak?", options: ["dependent phrase", "mustaqil gap", "faqat noun", "comma"], answer: 1 },
      { q: "Defining relative clause:", options: ["Students, who study daily, improve. (hamma student)", "Students who study daily improve.", "Students, study daily improve.", "Students which study daily improve."], answer: 1 },
      { q: "Comma splice qaysi biri?", options: ["It is costly, it is useful.", "It is costly; it is useful.", "It is costly, but useful.", "Although costly, it is useful."], answer: 0 },
    ],
  },
];
