import type { GrammarLesson } from "./types";

/** A2 — the past, the future, comparisons and quantities. */
export const A2_LESSONS: GrammarLesson[] = [
  {
    slug: "past-simple",
    level: "A2",
    title: "Past Simple",
    titleUz: "Oddiy o'tgan zamon",
    emoji: "⏪",
    explanation: [
      "Past Simple — tugagan, aniq vaqtdagi o'tmish voqealari: kecha, o'tgan yili, 2020-yilda. \"Men kecha kino ko'rdim\" — I watched a film yesterday.",
      "To'g'ri fe'llarga -ed qo'shiladi: work → worked, play → played. Lekin eng ko'p ishlatiladigan fe'llar NOTO'G'RI: go → went, have → had, see → saw, come → came, take → took, get → got, make → made, say → said. Bularni jadval bilan yodlash shart — yo'li yo'q.",
      "Inkor va savolda 'did' keladi va asosiy fe'l ASL SHAKLGA qaytadi: I didn't go (didn't went emas!), Did you see? (Did you saw emas!). 'Did'ning o'zi o'tgan zamonni ko'rsatadi, fe'lga ikkinchi marta kerak emas.",
      "Vaqt belgilari: yesterday, last week/year, two days ago, in 2019, when I was a child.",
    ],
    formula: "V-ed / V2 · inkor: didn't + V · savol: Did + ega + V?",
    examples: [
      { en: "I visited my grandparents last weekend.", uz: "O'tgan dam olishda buvim-bobomnikiga bordim." },
      { en: "She went to London in 2023.", uz: "U 2023-yilda Londonga bordi." },
      { en: "We didn't watch the match.", uz: "Biz o'yinni ko'rmadik." },
      { en: "Did you finish your homework?", uz: "Uy vazifangizni tugatdingizmi?" },
      { en: "He bought a new car two months ago.", uz: "U ikki oy oldin yangi mashina sotib oldi." },
      { en: "They came home late last night.", uz: "Ular kecha uyga kech kelishdi." },
    ],
    mistakes: [
      { wrong: "I didn't went to school.", right: "I didn't go to school.", note: "'Did' bo'lganda fe'l asl shaklga qaytadi." },
      { wrong: "Did she called you?", right: "Did she call you?", note: "Savolda ham fe'l asl shaklda qoladi." },
      { wrong: "I have seen him yesterday.", right: "I saw him yesterday.", note: "'Yesterday' kabi aniq o'tgan vaqt bilan Past Simple ishlatiladi." },
    ],
    quiz: [
      { q: "She ___ to Samarkand last month.", options: ["go", "goed", "went", "gone"], answer: 2 },
      { q: "___ you see the news yesterday?", options: ["Do", "Did", "Have", "Were"], answer: 1 },
      { q: "We ___ play football because of the rain.", options: ["didn't", "don't", "weren't", "no"], answer: 0 },
      { q: "'Take' fe'lining o'tgan zamoni:", options: ["taked", "tooked", "took", "taken"], answer: 2 },
      { q: "He ___ his keys at home this morning.", options: ["leave", "left", "leaved", "leaves"], answer: 1 },
    ],
  },
  {
    slug: "comparatives-superlatives",
    level: "A2",
    title: "Comparatives & superlatives",
    titleUz: "Qiyosiy va orttirma daraja",
    emoji: "📈",
    explanation: [
      "Taqqoslash uchun: qisqa sifatlarga -er (+ than), uzunlariga more: cheaper than, more expensive than. Orttirma daraja: the -est / the most: the cheapest, the most expensive. 'The' unutilmasin!",
      "Qisqa sifat = 1 bo'g'in (yoki -y bilan tugagan 2 bo'g'in): big → bigger → the biggest (undosh ikkilanadi), happy → happier → the happiest (-y → -i).",
      "Noto'g'ri shakllar yodlanadi: good → better → the best, bad → worse → the worst, far → further → the furthest.",
      "Tenglik: as ... as — \"kabi/dek\": She is as tall as her mother. Inkori: not as ... as.",
    ],
    formula: "qisqa: -er than / the -est · uzun: more ... than / the most ...",
    examples: [
      { en: "Tashkent is bigger than Khiva.", uz: "Toshkent Xivadan kattaroq." },
      { en: "This phone is more expensive than that one.", uz: "Bu telefon anavisidan qimmatroq." },
      { en: "Aral was once the fourth largest lake in the world.", uz: "Orol bir paytlar dunyodagi to'rtinchi eng katta ko'l edi." },
      { en: "Today is the happiest day of my life.", uz: "Bugun hayotimdagi eng baxtli kun." },
      { en: "My English is getting better.", uz: "Ingliz tilim yaxshilanyapti." },
      { en: "The test was not as difficult as I expected.", uz: "Test men kutgandek qiyin emas edi." },
    ],
    mistakes: [
      { wrong: "This book is more cheaper.", right: "This book is cheaper.", note: "'More' va '-er' birga ishlatilmaydi — bittasi yetarli." },
      { wrong: "She is taller from me.", right: "She is taller than me.", note: "Taqqoslashda 'than' ishlatiladi ('from' emas)." },
      { wrong: "He is the goodest player.", right: "He is the best player.", note: "'Good'ning orttirma darajasi — the best." },
    ],
    quiz: [
      { q: "Winter in Moscow is ___ than in Tashkent.", options: ["cold", "colder", "more cold", "coldest"], answer: 1 },
      { q: "This is ___ restaurant in the city.", options: ["better", "the best", "goodest", "most good"], answer: 1 },
      { q: "Math is ___ than history for me.", options: ["difficulter", "more difficult", "most difficult", "difficult"], answer: 1 },
      { q: "'Bad'ning qiyosiy darajasi:", options: ["badder", "more bad", "worse", "worst"], answer: 2 },
      { q: "She sings as ___ as a professional.", options: ["good", "better", "well", "best"], answer: 2 },
    ],
  },
  {
    slug: "future-will-going-to",
    level: "A2",
    title: "Future: will & going to",
    titleUz: "Kelasi zamon: will va going to",
    emoji: "🔮",
    explanation: [
      "Ingliz tilida kelasi zamonning ikki asosiy yo'li bor va ular BIR XIL EMAS.",
      "'Will + fe'l' — gapirish paytida qabul qilingan qaror, va'da yoki taxmin: \"It's cold — I will close the window\" (hozir qaror qildim). \"I think it will rain\" (taxmin).",
      "'Going to + fe'l' — OLDINDAN qilingan reja yoki dalilga asoslangan bashorat: \"I am going to study in Korea next year\" (allaqachon rejalashtirilgan). \"Look at the clouds — it's going to rain\" (dalil ko'rinib turibdi).",
      "Aniq kelishilgan yaqin rejalar uchun Present Continuous ham ishlatiladi: \"I am meeting the dentist at 5\".",
    ],
    formula: "will + V (hozirgi qaror/va'da) · am/is/are going to + V (oldingi reja)",
    examples: [
      { en: "I'll help you with those bags.", uz: "Sumkalaringizga yordam beraman. (hozir qaror qildim)" },
      { en: "We are going to open a shop next spring.", uz: "Kelasi bahorda do'kon ochmoqchimiz. (reja)" },
      { en: "She will probably win the competition.", uz: "U ehtimol musobaqada g'olib chiqadi." },
      { en: "Watch out! You are going to fall!", uz: "Ehtiyot bo'ling! Yiqilasiz! (dalil ko'rinyapti)" },
      { en: "I promise I won't be late.", uz: "Va'da beraman, kechikmayman." },
      { en: "They are going to get married in June.", uz: "Ular iyunda turmush qurishmoqchi." },
    ],
    mistakes: [
      { wrong: "I will to call you.", right: "I will call you.", note: "'Will'dan keyin 'to' ishlatilmaydi." },
      { wrong: "He will goes home.", right: "He will go home.", note: "'Will'dan keyin fe'l asl shaklda — -s yo'q." },
      { wrong: "I go to visit them tomorrow. (reja)", right: "I am going to visit them tomorrow.", note: "Reja uchun 'going to' to'liq shaklda kerak." },
    ],
    quiz: [
      { q: "The phone is ringing. — I ___ answer it!", options: ["am going to", "will", "going to", "would"], answer: 1 },
      { q: "We ___ move to a new flat next month. (reja)", options: ["will", "are going to", "go to", "moving"], answer: 1 },
      { q: "I think our team ___ win.", options: ["will", "is going", "wins", "won"], answer: 0 },
      { q: "She will ___ you tomorrow.", options: ["calls", "called", "call", "calling"], answer: 2 },
      { q: "Look at the sky! It ___ snow.", options: ["will to", "is going to", "goes to", "is go to"], answer: 1 },
    ],
  },
  {
    slug: "countable-uncountable",
    level: "A2",
    title: "Countable & uncountable",
    titleUz: "Sanaladigan va sanalmaydigan otlar",
    emoji: "🧮",
    explanation: [
      "Ingliz tilida otlar ikkiga bo'linadi: sanaladigan (apple — one apple, two apples) va sanalmaydigan (water, money, information — ko'plik yo'q, 'a' yo'q).",
      "Eng xavfli sanalmaydiganlar (o'zbekchada sanaladigandek tuyuladi!): money (pul), information (ma'lumot), advice (maslahat), news, furniture, homework, bread, hair. \"Informations\" yoki \"advices\" deyish mumkin emas.",
      "Miqdor so'zlari: much + sanalmaydigan (how much money), many + sanaladigan (how many books), a lot of — ikkalasi bilan. Some (bor gapda), any (inkor va savolda).",
      "Sanalmaydigan narsani \"donalash\" uchun: a piece of advice, a glass of water, a loaf of bread.",
    ],
    formula: "many + sanaladigan · much + sanalmaydigan · a lot of + ikkalasi",
    examples: [
      { en: "How much money do you need?", uz: "Qancha pul kerak sizga?" },
      { en: "How many students are in your group?", uz: "Guruhingizda nechta talaba bor?" },
      { en: "Can you give me some advice?", uz: "Menga maslahat bera olasizmi?" },
      { en: "There isn't any bread at home.", uz: "Uyda non yo'q." },
      { en: "I don't have much free time.", uz: "Bo'sh vaqtim ko'p emas." },
      { en: "She bought a lot of furniture for the new house.", uz: "U yangi uy uchun ko'p mebel sotib oldi." },
    ],
    mistakes: [
      { wrong: "He gave me many informations.", right: "He gave me a lot of information.", note: "'Information' sanalmaydi — ko'plik shakli yo'q." },
      { wrong: "How many money do you have?", right: "How much money do you have?", note: "'Money' sanalmaydigan ot — 'much' ishlatiladi." },
      { wrong: "I have a homework.", right: "I have homework.", note: "'Homework' sanalmaydi — 'a' ishlatilmaydi." },
    ],
    quiz: [
      { q: "How ___ sugar do you want in your tea?", options: ["many", "much", "a lot", "some"], answer: 1 },
      { q: "There are ___ apples in the basket.", options: ["much", "a little", "many", "any"], answer: 2 },
      { q: "Qaysi so'z SANALMAYDI?", options: ["book", "advice", "car", "apple"], answer: 1 },
      { q: "Do you have ___ questions?", options: ["some", "any", "much", "a"], answer: 1 },
      { q: "To'g'ri gapni tanlang:", options: ["I need an information.", "I need informations.", "I need some information.", "I need many information."], answer: 2 },
    ],
  },
  {
    slug: "adverbs-frequency",
    level: "A2",
    title: "Adverbs of frequency & manner",
    titleUz: "Takrorlanish va holat ravishlari",
    emoji: "🔁",
    explanation: [
      "Takrorlanish ravishlari qanchalik tez-tez bo'lishini aytadi: always (100%), usually, often, sometimes, rarely, never (0%).",
      "O'RNI muhim: oddiy fe'ldan OLDIN (I always drink tea), lekin 'to be'dan KEYIN (She is always late). Bu qoida imtihonlarda tez-tez tekshiriladi.",
      "Holat ravishlari (qanday?) sifatdan -ly bilan yasaladi: slow → slowly, careful → carefully. Ular odatda gap oxirida keladi: He drives carefully.",
      "Istisnolar: fast → fast (fastly yo'q!), hard → hard ('hardly' = deyarli yo'q — boshqa ma'no!), good → well.",
    ],
    formula: "ravish + oddiy fe'l · to be + ravish · sifat + -ly = holat ravishi",
    examples: [
      { en: "I usually get up at six.", uz: "Men odatda oltida turaman." },
      { en: "She is never angry with the children.", uz: "U bolalarga hech qachon jahl qilmaydi." },
      { en: "They sometimes visit us on Fridays.", uz: "Ular ba'zan juma kunlari biznikiga kelishadi." },
      { en: "Please speak slowly.", uz: "Iltimos, sekin gapiring." },
      { en: "He plays chess very well.", uz: "U shaxmatni juda yaxshi o'ynaydi." },
      { en: "She works hard every day.", uz: "U har kuni qattiq mehnat qiladi." },
    ],
    mistakes: [
      { wrong: "I go always to the gym.", right: "I always go to the gym.", note: "Ravish oddiy fe'ldan OLDIN keladi." },
      { wrong: "She always is happy.", right: "She is always happy.", note: "'To be' bilan ravish undan KEYIN keladi." },
      { wrong: "He drives very fastly.", right: "He drives very fast.", note: "'Fast' ravish sifatida ham 'fast' — 'fastly' mavjud emas." },
    ],
    quiz: [
      { q: "He ___ late for work. (always)", options: ["always is", "is always", "always be", "be always"], answer: 1 },
      { q: "We ___ eat fast food. (never)", options: ["never eat", "eat never", "never eats", "are never eat"], answer: 0 },
      { q: "'Good' so'zining ravish shakli:", options: ["goodly", "well", "good", "better"], answer: 1 },
      { q: "She sings ___.", options: ["beautiful", "beautifully", "beauty", "more beautiful"], answer: 1 },
      { q: "He works very ___.", options: ["hardly", "hard", "harder", "hardest"], answer: 1 },
    ],
  },
  {
    slug: "modals-obligation",
    level: "A2",
    title: "Must / have to / should",
    titleUz: "Majburiyat: must / have to / should",
    emoji: "📏",
    explanation: [
      "'Must' — kuchli majburiyat, ko'pincha gapiruvchining o'z talabi: You must wear a seatbelt. Inkori 'mustn't' — TAQIQ: You mustn't smoke here (mumkin emas!).",
      "'Have to' — tashqi qoidadan kelgan majburiyat: I have to work on Saturdays (ish talabi). Inkori 'don't have to' — KERAK EMAS (lekin mumkin): You don't have to come (kelishing shart emas). Diqqat: mustn't ≠ don't have to!",
      "'Should' — maslahat: You should see a doctor (borsangiz yaxshi bo'lardi). Inkori shouldn't: You shouldn't eat so much sugar.",
      "Barcha modallardan keyin fe'l asl shaklda: must go, have to work (he has to work), should see.",
    ],
    formula: "must (kuchli) · have to (qoida) · should (maslahat) — hammasi + V",
    examples: [
      { en: "Students must switch off their phones during the exam.", uz: "Imtihon paytida talabalar telefonlarini o'chirishlari shart." },
      { en: "I have to get up early tomorrow.", uz: "Ertaga erta turishim kerak." },
      { en: "You mustn't park here — it's forbidden.", uz: "Bu yerga mashina qo'yish mumkin emas — taqiqlangan." },
      { en: "You don't have to pay — it's free.", uz: "To'lashingiz shart emas — bepul." },
      { en: "You should drink more water.", uz: "Ko'proq suv ichishingiz kerak (maslahat)." },
      { en: "He has to renew his visa every year.", uz: "U har yili vizasini yangilashi kerak." },
    ],
    mistakes: [
      { wrong: "You mustn't pay, it's free.", right: "You don't have to pay, it's free.", note: "'Mustn't' = taqiq; \"shart emas\" = don't have to." },
      { wrong: "He must to go now.", right: "He must go now.", note: "'Must'dan keyin 'to' ishlatilmaydi." },
      { wrong: "She have to study.", right: "She has to study.", note: "He/she/it bilan 'has to' bo'ladi." },
    ],
    quiz: [
      { q: "You ___ smoke in the hospital. (taqiq)", options: ["don't have to", "mustn't", "shouldn't", "may not"], answer: 1 },
      { q: "It's Sunday — I ___ go to work.", options: ["mustn't", "don't have to", "can't", "shouldn't"], answer: 1 },
      { q: "You look tired. You ___ rest.", options: ["must to", "should", "have", "should to"], answer: 1 },
      { q: "He ___ wear a uniform at work. (qoida)", options: ["has to", "have to", "should", "musts"], answer: 0 },
      { q: "Students must ___ on time.", options: ["arriving", "to arrive", "arrive", "arrives"], answer: 2 },
    ],
  },
  {
    slug: "present-perfect-intro",
    level: "A2",
    title: "Present Perfect (introduction)",
    titleUz: "Present Perfect (tanishuv)",
    emoji: "🔗",
    explanation: [
      "Present Perfect — o'tmish bilan hozirni BOG'LAYDIGAN zamon: have/has + V3. Ish qachondir bo'lgan, lekin natijasi/ahamiyati HOZIR muhim: \"I have lost my keys\" (kalitlar hozir ham yo'q).",
      "Uch asosiy holat: 1) hayotiy tajriba — \"Have you ever been to Dubai?\"; 2) hozirgacha davom etuvchi natija — \"She has finished the report\" (hisobot hozir tayyor); 3) yaqinda — just/already/yet bilan.",
      "OLTIN FARQ: aniq o'tgan vaqt (yesterday, in 2020, ago) aytilsa — Past Simple; vaqt aytilmasa yoki hozir bilan bog'liq bo'lsa — Present Perfect. \"I have seen him yesterday\" — XATO.",
      "Belgilar: ever, never, just, already, yet, recently, since, for.",
    ],
    formula: "have/has + V3 (gone, seen, done...)",
    examples: [
      { en: "I have been to Turkey twice.", uz: "Men Turkiyada ikki marta bo'lganman." },
      { en: "She has just finished her homework.", uz: "U hozirgina uy vazifasini tugatdi." },
      { en: "Have you ever tried sushi?", uz: "Hech sushi tatib ko'rganmisiz?" },
      { en: "We haven't seen this film yet.", uz: "Biz bu filmni hali ko'rmadik." },
      { en: "He has lost his wallet.", uz: "U hamyonini yo'qotib qo'ydi. (hozir ham yo'q)" },
      { en: "They have already left.", uz: "Ular allaqachon ketib bo'lishgan." },
    ],
    mistakes: [
      { wrong: "I have visited Khiva last year.", right: "I visited Khiva last year.", note: "Aniq o'tgan vaqt (last year) bilan Past Simple ishlatiladi." },
      { wrong: "She has went home.", right: "She has gone home.", note: "Present Perfect'da fe'lning 3-shakli (V3) ishlatiladi." },
      { wrong: "Did you ever eat plov?", right: "Have you ever eaten plov?", note: "Hayotiy tajriba 'ever' bilan — Present Perfect." },
    ],
    quiz: [
      { q: "I ___ never ___ to Japan.", options: ["did / go", "have / been", "has / been", "am / been"], answer: 1 },
      { q: "She ___ just ___ lunch.", options: ["has / finished", "have / finished", "did / finish", "is / finished"], answer: 0 },
      { q: "___ you ever ___ a camel?", options: ["Did / ride", "Have / rode", "Have / ridden", "Do / ride"], answer: 2 },
      { q: "We ___ the tickets yet.", options: ["didn't buy", "haven't bought", "don't buy", "hasn't bought"], answer: 1 },
      { q: "Qaysi gap XATO?", options: ["I have seen that film.", "I saw him yesterday.", "I have seen him yesterday.", "Have you eaten?"], answer: 2 },
    ],
  },
  {
    slug: "conditionals-0-1",
    level: "A2",
    title: "Zero & First Conditional",
    titleUz: "0- va 1-shart gaplari",
    emoji: "🌦️",
    explanation: [
      "Shart gaplari 'if' (agar) bilan yasaladi. Zero Conditional — umumiy haqiqatlar: If + Present, Present. \"If you heat ice, it melts\" (muz doim eriydi).",
      "First Conditional — real kelajak sharti: If + Present Simple, will + fe'l. \"If it rains tomorrow, we will stay home\". MUHIM: 'if' qismida will ISHLATILMAYDI — \"If it will rain\" qo'pol xato!",
      "'If' o'rnida: unless (= if not), when, as soon as ham xuddi shu qoidaga bo'ysunadi: \"I'll call you when I arrive\" (when I will arrive — emas).",
      "Gap tartibini almashtirish mumkin: We will stay home if it rains — vergul kerak emas.",
    ],
    formula: "0: If + Present, Present · 1: If + Present, will + V",
    examples: [
      { en: "If you don't water plants, they die.", uz: "O'simliklarni sug'ormasangiz, ular quriydi. (doim)" },
      { en: "If it snows, we will make a snowman.", uz: "Qor yog'sa, qorbobo yasaymiz." },
      { en: "If you study hard, you will pass IELTS.", uz: "Qattiq o'qisangiz, IELTS'dan o'tasiz." },
      { en: "I will call you as soon as I get home.", uz: "Uyga yetishim bilan sizga qo'ng'iroq qilaman." },
      { en: "Unless you hurry, you will miss the train.", uz: "Shoshilmasangiz, poyezdga kechikasiz." },
      { en: "What will you do if the shop is closed?", uz: "Do'kon yopiq bo'lsa, nima qilasiz?" },
    ],
    mistakes: [
      { wrong: "If it will rain, we will stay home.", right: "If it rains, we will stay home.", note: "'If' qismida 'will' ishlatilmaydi — Present Simple kifoya." },
      { wrong: "If you heat water to 100°C, it will boils.", right: "...it boils.", note: "Umumiy haqiqat (Zero) — ikkala qism ham Present." },
      { wrong: "I call you when I will arrive.", right: "I will call you when I arrive.", note: "'When' qismi ham 'will'siz — asosiy qismda 'will'." },
    ],
    quiz: [
      { q: "If you ___ ice, it melts.", options: ["will heat", "heat", "heated", "heats"], answer: 1 },
      { q: "If she ___ early, she will catch the bus.", options: ["will leave", "leave", "leaves", "left"], answer: 2 },
      { q: "We ___ the picnic if the weather is good.", options: ["have", "will have", "had", "would have"], answer: 1 },
      { q: "I'll text you when I ___ there.", options: ["will get", "get", "got", "getting"], answer: 1 },
      { q: "___ you run, you will miss the bus. (agar yugurmasangiz)", options: ["If", "When", "Unless", "Until"], answer: 2 },
    ],
  },
  {
    slug: "too-enough",
    level: "A2",
    title: "Too / enough",
    titleUz: "Too va enough (juda / yetarli)",
    emoji: "⚖️",
    explanation: [
      "'Too' = kerak bo'lganidan ORTIQ (salbiy ma'noda): too expensive — juda qimmat (sotib ololmayman). 'Very' bilan adashtirmang: 'very big' shunchaki katta, 'too big' — sig'maydigan darajada katta.",
      "'Enough' = yetarli. O'RNI muhim: sifatdan KEYIN (warm enough), lekin otdan OLDIN (enough money). Bu teskari tartib ko'p xatoga sabab bo'ladi.",
      "Ko'pincha 'to + fe'l' bilan davom etadi: too tired to work (ishlash uchun juda charchagan), old enough to vote (ovoz berish uchun yetarlicha katta).",
    ],
    formula: "too + sifat · sifat + enough · enough + ot",
    examples: [
      { en: "This tea is too hot to drink.", uz: "Bu choy ichish uchun juda issiq." },
      { en: "The room isn't big enough for all of us.", uz: "Xona hammamiz uchun yetarlicha katta emas." },
      { en: "I don't have enough time today.", uz: "Bugun vaqtim yetarli emas." },
      { en: "He is too young to drive.", uz: "U mashina haydash uchun juda yosh." },
      { en: "Is the water warm enough?", uz: "Suv yetarlicha iliqmi?" },
      { en: "She earns enough money to travel every year.", uz: "U har yili sayohat qilishga yetarli pul topadi." },
    ],
    mistakes: [
      { wrong: "The box is enough big.", right: "The box is big enough.", note: "'Enough' sifatdan KEYIN keladi." },
      { wrong: "I have money enough.", right: "I have enough money.", note: "'Enough' otdan OLDIN keladi." },
      { wrong: "The film was too much long.", right: "The film was too long.", note: "Sifat bilan faqat 'too' — 'too much' emas." },
    ],
    quiz: [
      { q: "This coffee is ___ sweet for me.", options: ["enough", "too", "very much", "as"], answer: 1 },
      { q: "He isn't tall ___ to reach the shelf.", options: ["too", "very", "enough", "so"], answer: 2 },
      { q: "We don't have ___ chairs for the guests.", options: ["too", "enough", "many enough", "too much"], answer: 1 },
      { q: "To'g'ri tartibni tanlang:", options: ["enough warm", "warm enough", "too warm enough", "enough too warm"], answer: 1 },
      { q: "I'm ___ tired ___ cook tonight.", options: ["too / to", "very / to", "too / for", "enough / to"], answer: 0 },
    ],
  },
];
