import type { GrammarLesson } from "./types";

/** Expert structures that make IELTS recommendations and comparisons precise. */
export const IELTS_EXPERT_LESSONS: GrammarLesson[] = [
  {
    slug: "mandative-subjunctive",
    level: "IELTS",
    title: "Mandative subjunctive",
    titleUz: "Rasmiy talab va tavsiya gaplari",
    emoji: "📜",
    highlights: ["recommend that", "suggest that", "insist that", "base verb"],
    explanation: [
      "Recommend, suggest, insist, demand va propose kabi fe'llardan keyin formal Englishda that clause kelishi mumkin. Bu clause ichida subjectdan keyin fe'lning oddiy shakli ishlatiladi.",
      "Masalan: Experts recommend that governments invest in public transport. Bu yerda governments plural bo'lsa ham, bitta shaxs bo'lsa ham invest o'zgarmaydi.",
      "British Englishda should ham keng ishlatiladi: They suggested that the council should act. IELTS Writingda ikkala shakl to'g'ri, lekin bitta uslubni izchil tanlang.",
      "Bu qurilma Task 2 conclusion va recommendation paragraphlarida juda foydali, chunki tavsiyani aniq va rasmiy qiladi.",
    ],
    formula: "recommend/suggest/insist + that + subject + base verb · British variant: should + base verb",
    keyPoints: [
      { title: "Base verb", body: "He, she, it bilan ham invests emas, invest ishlatiladi." },
      { title: "Taklif", body: "Suggest that patterni taklif yoki talab uchun ishlatiladi." },
      { title: "Ikki variant", body: "That schools provide va that schools should provide ikkalasi ham formal uslubda mumkin." },
    ],
    importantNotes: ["Suggest someone to do xato; suggest that someone do yoki suggest doing ishlating.", "Demand va insist kuchli so'zlar; faqat haqiqatan kuchli talab bo'lsa ishlating."],
    examTips: ["Conclusionda bitta aniq recommendation yozing: I recommend that local authorities...", "Speakingda bu formani majburan ishlatish shart emas; tabiiy gap muhimroq."],
    examples: [
      { en: "Doctors recommend that adults exercise regularly.", uz: "Shifokorlar kattalarga muntazam mashq qilishni tavsiya etadi." },
      { en: "The report suggests that the government increase funding.", uz: "Hisobot hukumat mablag'ni oshirishini taklif qiladi." },
      { en: "Parents insisted that the school improve safety.", uz: "Ota-onalar maktab xavfsizlikni yaxshilashini talab qildi." },
      { en: "It is essential that every applicant submit the form on time.", uz: "Har bir arizachi formani vaqtida topshirishi muhim." },
      { en: "The committee proposed that the city should create more parks.", uz: "Qo'mita shahar ko'proq park yaratishini taklif qildi." },
      { en: "I urge students to practise these structures before the exam.", uz: "Talabalarni imtihondan oldin bu strukturalarni mashq qilishga chaqiraman." },
    ],
    mistakes: [
      { wrong: "They recommend that he studies more.", right: "They recommend that he study more.", note: "That clause ichida base verb ishlatiladi." },
      { wrong: "She suggested me to apply.", right: "She suggested that I apply.", note: "Suggest + object + to-infinitive ishlatilmaydi." },
      { wrong: "It is vital that she attends.", right: "It is vital that she attend.", note: "Formal mandative clause ichida attends emas, attend." },
    ],
    quiz: [
      { q: "Experts recommend that the city ___ more trees.", options: ["plants", "plant", "planted", "planting"], answer: 1 },
      { q: "It is important that every student ___ prepared.", options: ["be", "is", "was", "being"], answer: 0 },
      { q: "Qaysi variant to'g'ri?", options: ["She suggested me to rest.", "She suggested that I rest.", "She suggested that I rested.", "She suggested I to rest."], answer: 1 },
      { q: "The manager insisted that he ___ the report today.", options: ["finishes", "finish", "finished", "finishing"], answer: 1 },
      { q: "British English variantini tanlang:", options: ["They proposed that she should apply.", "They proposed she to apply.", "They proposed that she applies.", "They proposed her apply."], answer: 0 },
    ],
  },
  {
    slug: "advanced-comparison",
    level: "IELTS",
    title: "Advanced comparison structures",
    titleUz: "Murakkab taqqoslash qurilmalari",
    emoji: "📊",
    highlights: ["the more", "the less", "far more", "twice as", "compared with"],
    explanation: [
      "IELTS Task 1 va Task 2da simple comparative yetarli bo'lmay qoladi. The more..., the more... ikki o'zgarishning birga kuchayishini ko'rsatadi.",
      "As ... as tenglik uchun ishlatiladi: twice as high as, not nearly as effective as. Twice as many bilan countable noun, twice as much bilan uncountable noun keladi.",
      "Far, considerably, significantly va marginally comparative'ni aniqroq qiladi: far more expensive, slightly lower, considerably higher.",
      "Compared with/to va in comparison with yordamida ikki ma'lumotni bir grammatik birlikda bog'laysiz. Task 1da ayniqsa foydali.",
    ],
    formula: "the + comparative, the + comparative · twice as + adjective + as · far/slightly + comparative",
    keyPoints: [
      { title: "Bog'liq trend", body: "The more people travel, the more emissions increase kabi pattern ikki bog'liq change'ni beradi." },
      { title: "Countability", body: "Many cars, much traffic: twice as many cars va twice as much traffic." },
      { title: "Aniqlik", body: "Far va considerably katta farq, slightly va marginally kichik farq uchun." },
    ],
    importantNotes: ["More easier xato; faqat easier yoki more useful.", "Compared with data comparison uchun aniqroq variant."],
    examTips: ["Task 1da har paragraphda bir necha raqamni takrorlash o'rniga comparative structure ishlating.", "The more patternini sabab aniq bo'lgandagina ishlating."],
    examples: [
      { en: "The more people use public transport, the lower traffic levels become.", uz: "Odamlar jamoat transportidan qancha ko'p foydalansa, tirbandlik shuncha kamayadi." },
      { en: "Online sales were twice as high as store sales in 2024.", uz: "2024-yilda onlayn savdo do'kon savdosidan ikki baravar yuqori edi." },
      { en: "The northern region recorded significantly fewer visitors.", uz: "Shimoliy hudud sezilarli darajada kamroq mehmon qayd etdi." },
      { en: "This method is far more effective than memorising isolated lists.", uz: "Bu usul alohida ro'yxatlarni yodlashdan ancha samaraliroq." },
      { en: "Compared with 2010, household spending rose sharply.", uz: "2010-yil bilan solishtirganda, uy xo'jaligi xarajatlari keskin oshdi." },
      { en: "Rural homes used almost as much electricity as urban homes.", uz: "Qishloq uylari shahar uylaridek deyarli shuncha elektr ishlatdi." },
    ],
    mistakes: [
      { wrong: "The more people use cars, the traffic becomes worse.", right: "The more people use cars, the worse traffic becomes.", note: "The more patternining ikkala qismida comparative kerak." },
      { wrong: "Sales were twice higher than last year.", right: "Sales were twice as high as last year.", note: "Twice bilan as ... as structure ishlating." },
      { wrong: "This solution is more easier.", right: "This solution is easier.", note: "Easier allaqachon comparative." },
    ],
    quiz: [
      { q: "The ___ you practise, the more confident you become.", options: ["much", "more", "most", "many"], answer: 1 },
      { q: "The figure was three times as ___ as expected.", options: ["high", "higher", "highest", "highly"], answer: 0 },
      { q: "This route is ___ shorter than the old one.", options: ["far", "very", "muchly", "more"], answer: 0 },
      { q: "There were twice as ___ students in June.", options: ["much", "many", "more", "most"], answer: 1 },
      { q: "Qaysi gap to'g'ri?", options: ["The more it rains, the more wet roads become.", "The more it rains, the wetter the roads become.", "More it rains, wetter roads.", "The most it rains, the wettest."], answer: 1 },
    ],
  },
  {
    slug: "academic-noun-phrases",
    level: "IELTS",
    title: "Academic noun phrases",
    titleUz: "Akademik noun phrase'lar",
    emoji: "✂️",
    highlights: ["students living", "data collected", "the first to", "which was"],
    explanation: [
      "Academic noun phrase asosiy otga aniqlovchi so'zlarni tartibli qo'shadi: the rapid growth of online shopping, a lack of affordable housing. Bu Task 1 va Task 2ni aniqroq qiladi.",
      "Participle modifier otni ixcham tasvirlaydi: people living in cities, data collected in 2024. V-ing faol ma'no, V3 esa passiv yoki tugallangan ma'no beradi.",
      "Preposition phrase ham noun phrase'ni boyitadi: the proportion of students in higher education, the impact of pollution on public health.",
      "Uzun phrase foydali, lekin bosh otni yo'qotmang. Bir gapda bittadan aniq academic noun phrase ko'pincha yetarli bo'ladi.",
    ],
    formula: "determiner + modifier + head noun + of/in/on phrase · noun + V-ing/V3 modifier",
    keyPoints: [
      { title: "Head noun", body: "Har phrase'da asosiy ot bo'ladi: growth, impact, proportion, lack." },
      { title: "Active va passive", body: "People working active; data collected passive ma'no beradi." },
      { title: "Preposition", body: "Growth of sales, impact on health, access to education kabi birikmalarni to'g'ri tanlang." },
    ],
    importantNotes: ["V-ing clause subjectiga e'tibor bering: a book written by her, not writing by her.", "Juda ko'p modifier bilan phrase'ni o'qib bo'lmaydigan qilmang."],
    examTips: ["Task 1da 'the proportion of people living in...' tabiiy va ixcham.", "Writingda har paragraphga 1-2 kuchli noun phrase yetarli."],
    examples: [
      { en: "People living near the airport often complain about noise.", uz: "Aeroport yaqinida yashaydigan odamlar ko'pincha shovqindan shikoyat qiladi." },
      { en: "The data collected in 2024 shows a clear pattern.", uz: "2024-yilda to'plangan ma'lumotlar aniq patternni ko'rsatadi." },
      { en: "Students applying for the course must submit a portfolio.", uz: "Kursga ariza berayotgan talabalar portfolio topshirishi kerak." },
      { en: "The books borrowed from the library must be returned tomorrow.", uz: "Kutubxonadan olingan kitoblar ertaga qaytarilishi kerak." },
      { en: "The rapid growth of online shopping has changed retail.", uz: "Onlayn xaridlarning tez o'sishi chakana savdoni o'zgartirdi." },
      { en: "There are several factors affecting public health.", uz: "Jamoat salomatligiga ta'sir qiladigan bir nechta omil bor." },
    ],
    mistakes: [
      { wrong: "The data collecting in 2024 is useful.", right: "The data collected in 2024 is useful.", note: "Data yig'ilmaydi; u yig'iladi, shuning uchun V3." },
      { wrong: "People lived near the airport complain.", right: "People living near the airport complain.", note: "Hozir davom etayotgan active ma'no uchun V-ing." },
      { wrong: "The growth in online shopping", right: "The growth of online shopping", note: "Growth of + activity/noun birikmasi tabiiyroq." },
    ],
    quiz: [
      { q: "The cars ___ in Japan are popular worldwide.", options: ["making", "made", "make", "to make"], answer: 1 },
      { q: "People ___ from home may save time.", options: ["work", "worked", "working", "to working"], answer: 2 },
      { q: "The impact ___ tourism on nature can be serious.", options: ["in", "of", "at", "by"], answer: 1 },
      { q: "The issues ___ by the report need attention.", options: ["raise", "raising", "raised", "to raising"], answer: 2 },
      { q: "Qaysi noun phrase to'g'ri?", options: ["the growth of sales", "the growth sales", "the growth at sales", "the grow of sales"], answer: 0 },
    ],
  },
  {
    slug: "wishes-regrets-and-preferences",
    level: "IELTS",
    title: "Wishes, regrets and preferences",
    titleUz: "Wish, afsus va istak strukturalari",
    emoji: "🌱",
    highlights: ["wish + past", "wish + had + V3", "would rather", "if only"],
    explanation: [
      "Wish hozirgi haqiqatdan farqli istak uchun past simple bilan keladi: I wish I had more time. Bu yerda had o'tmish emas, hozirgi istakni bildiradi.",
      "O'tmishdagi afsus uchun wish + had + V3 ishlatiladi: I wish I had started earlier. If only kuchliroq emotsional variantdir.",
      "Boshqa odam yoki bezovta qilayotgan holat o'zgarishini istasak wish + would: I wish the bus would arrive. O'zimizning odatimiz uchun odatda would emas, could yoki past simple ishlatiladi.",
      "Would rather preference ko'rsatadi: I would rather study at home. Ikki subject bo'lsa, ikkinchi gap past simple oladi: I would rather you stayed.",
    ],
    formula: "wish + past simple (now) · wish + had + V3 (past regret) · would rather + base verb",
    keyPoints: [
      { title: "Present unreal", body: "I wish I were more confident = hozir ishonchliroq bo'lishni xohlayman." },
      { title: "Past regret", body: "I wish I had revised = oldinroq takrorlaganimni istardim." },
      { title: "Preference", body: "Would rather dan keyin to ishlatilmaydi: would rather stay." },
    ],
    importantNotes: ["Wish bilan want bir xil emas: I wish I had vaqtga mos bo'lmagan orzuni aytadi.", "If only odatda real afsus yoki kuchli istakda ishlatiladi."],
    examTips: ["Speakingda regret savollarida wish + had V3 tabiiy ko'rinadi.", "Would rather ni faqat preference savollarida ishlating; ortiqcha formal qilmang."],
    examples: [
      { en: "I wish I had more time to read every day.", uz: "Har kuni o'qish uchun ko'proq vaqtim bo'lishini istardim." },
      { en: "She wishes she were more confident in interviews.", uz: "U suhbatlarda o'ziga ko'proq ishonishini istaydi." },
      { en: "I wish I had learned English earlier.", uz: "Ingliz tilini oldinroq o'rganganimni istardim." },
      { en: "If only the weather would improve this weekend.", uz: "Qaniydi bu dam olish kunlari ob-havo yaxshilansa." },
      { en: "I would rather take the train than drive in traffic.", uz: "Tirbandlikda mashina haydashdan ko'ra poyezdga chiqishni afzal ko'raman." },
      { en: "My parents would rather I studied closer to home.", uz: "Ota-onam uyga yaqinroq joyda o'qishimni afzal ko'radi." },
    ],
    mistakes: [
      { wrong: "I wish I have more time.", right: "I wish I had more time.", note: "Hozirgi unreal istak uchun past simple." },
      { wrong: "I wish I would study harder last year.", right: "I wish I had studied harder last year.", note: "O'tmish afsus uchun had + V3." },
      { wrong: "I would rather to stay home.", right: "I would rather stay home.", note: "Would rather dan keyin to yo'q." },
    ],
    quiz: [
      { q: "I wish I ___ speak French fluently.", options: ["can", "could", "will", "have"], answer: 1 },
      { q: "She wishes she ___ the opportunity last year.", options: ["takes", "took", "had taken", "would take"], answer: 2 },
      { q: "I would rather ___ at home tonight.", options: ["stay", "to stay", "staying", "stayed"], answer: 0 },
      { q: "I wish the neighbours ___ making so much noise.", options: ["stop", "would stop", "had stopped yesterday", "to stop"], answer: 1 },
      { q: "My teacher would rather I ___ earlier.", options: ["arrive", "arrived", "will arrive", "have arrived"], answer: 1 },
    ],
  },
];
