import type { GrammarLesson } from "./types";

/** IELTS/C1 — the structures that separate band 6 from band 8 writing. */
export const IELTS_LESSONS: GrammarLesson[] = [
  {
    slug: "complex-sentences",
    level: "IELTS",
    title: "Complex sentences for Writing",
    titleUz: "Murakkab gaplar (Writing uchun)",
    emoji: "🏛️",
    explanation: [
      "IELTS baholash mezonida \"a mix of simple and complex sentences\" talab qilinadi. Murakkab gap = bosh gap + ergash gap (because, although, while, if, when, which bilan).",
      "Band 6 yozuvchi sodda gaplarni ketma-ket teradi: \"Cars cause pollution. Governments should act.\" Band 8: \"Since private cars remain a major source of urban pollution, governments should invest in public transport.\"",
      "Formulalar to'plami: sabab (since/as/because), qarama-qarshilik (although/while/whereas), shart (provided that/unless), maqsad (so that/in order to), natija (so ... that/such ... that).",
      "MUHIM: har gapni murakkab qilmaslik kerak — aralashtirish (2 sodda + 1 murakkab) eng tabiiy o'qiladi. Juda uzun gap band tushiradi, ko'tarmasin.",
    ],
    formula: "bosh gap + bog'lovchi + ergash gap · aralash uslub = band 7+",
    examples: [
      { en: "While technology connects people, it can also isolate them.", uz: "Texnologiya odamlarni bog'lasa-da, ularni yakkalab ham qo'yishi mumkin." },
      { en: "Since housing costs keep rising, many young people rent for longer.", uz: "Uy-joy narxlari oshib borayotgani sabab, ko'p yoshlar uzoqroq ijarada yashaydi." },
      { en: "Governments should fund education so that everyone has equal opportunities.", uz: "Hamma teng imkoniyatga ega bo'lishi uchun davlat ta'limni moliyalashtirishi kerak." },
      { en: "The problem is so serious that immediate action is required.", uz: "Muammo shu qadar jiddiyki, zudlik bilan chora talab qilinadi." },
      { en: "Whereas older people prefer print media, the young rely on social networks.", uz: "Keksalar bosma nashrni afzal ko'rsa, yoshlar ijtimoiy tarmoqlarga tayanadi." },
      { en: "Unless stricter laws are introduced, the situation will deteriorate.", uz: "Qattiqroq qonunlar kiritilmasa, vaziyat yomonlashadi." },
    ],
    mistakes: [
      { wrong: "Although it was expensive, but we bought it.", right: "Although it was expensive, we bought it.", note: "'Although' va 'but' birga ishlatilmaydi — bittasi yetarli." },
      { wrong: "Because pollution is increasing. Governments must act.", right: "Because pollution is increasing, governments must act.", note: "'Because'li ergash gap yolg'iz tura olmaydi — bosh gapga ulanadi." },
      { wrong: "The weather was so cold that's why we stayed home.", right: "The weather was so cold that we stayed home.", note: "'So ... that' qurilmasida 'that's why' emas, 'that' keladi." },
    ],
    quiz: [
      { q: "___ the price was high, the product sold well.", options: ["Despite", "Although", "Because", "However"], answer: 1 },
      { q: "Save your work regularly ___ you don't lose it.", options: ["so that", "because", "although", "unless"], answer: 0 },
      { q: "The lecture was ___ boring that half the students left.", options: ["such", "very", "so", "too"], answer: 2 },
      { q: "___ demand increases, prices will remain stable.", options: ["Because", "Unless", "So that", "Despite"], answer: 1 },
      { q: "Qaysi gap band 8 uslubiga eng yaqin?", options: ["Pollution is bad. We must act.", "Pollution is bad and we must act and it is important.", "Since pollution threatens public health, urgent measures are essential.", "Pollution!"], answer: 2 },
    ],
  },
  {
    slug: "participle-clauses",
    level: "IELTS",
    title: "Participle clauses",
    titleUz: "Sifatdosh o'ramlar",
    emoji: "✂️",
    explanation: [
      "Participle clause — gapni qisqartirib, akademik uslub beruvchi qurilma: \"Because she felt tired, she went home\" → \"Feeling tired, she went home\".",
      "V-ing — faol ma'no va bir vaqtdalik: \"Walking home, I met an old friend\" (uyga ketayotib...). Having + V3 — oldinroq tugagan ish: \"Having finished the report, he left\" (hisobotni tugatib bo'lib...).",
      "V3 — passiv ma'no: \"Built in the 15th century, the mosque attracts thousands of visitors\" (15-asrda qurilgan bo'lib...).",
      "XAVF: o'ram egasi bosh gap egasi bilan BIR XIL bo'lishi shart. \"Walking home, the rain started\" — xato: yomg'ir yurmaydi! Bu 'dangling participle' deyiladi.",
    ],
    formula: "V-ing (faol) · Having V3 (oldin tugagan) · V3 (passiv)",
    examples: [
      { en: "Feeling exhausted, she cancelled the meeting.", uz: "O'zini holsiz sezib, u yig'ilishni bekor qildi." },
      { en: "Having lived abroad, he understands cultural differences well.", uz: "Chet elda yashagani uchun u madaniy farqlarni yaxshi tushunadi." },
      { en: "Founded in 1918, the university is among the oldest in the region.", uz: "1918-yilda asos solingan bu universitet mintaqadagi eng qadimiylardan." },
      { en: "Looking at the data, we can see a clear upward trend.", uz: "Ma'lumotlarga qarab, aniq o'sish tendensiyasini ko'ramiz." },
      { en: "Not knowing the answer, I stayed silent.", uz: "Javobni bilmaganim uchun jim qoldim." },
      { en: "Having been warned twice, the driver lost his licence.", uz: "Ikki marta ogohlantirilgach, haydovchi guvohnomasidan ayrildi." },
    ],
    mistakes: [
      { wrong: "Walking to work, the rain started.", right: "Walking to work, I got caught in the rain.", note: "O'ram egasi bosh gap egasi bilan bir xil bo'lishi kerak." },
      { wrong: "After finished the task, we rested.", right: "After finishing the task, we rested.", note: "Predlogdan keyin V-ing keladi." },
      { wrong: "Having eat dinner, they left.", right: "Having eaten dinner, they left.", note: "'Having'dan keyin V3." },
    ],
    quiz: [
      { q: "___ the exam, she celebrated with friends.", options: ["Passing", "Having passed", "Passed", "To pass"], answer: 1 },
      { q: "___ in 2005, the bridge needs repairs already.", options: ["Building", "Having built", "Built", "To build"], answer: 2 },
      { q: "___ what to say, he remained silent.", options: ["Not knowing", "Not known", "Don't knowing", "Not to know"], answer: 0 },
      { q: "Qaysi gap XATO (dangling)?", options: ["Feeling ill, she left early.", "Driving home, my phone rang.", "Having won, the team celebrated.", "Written in English, the book sold worldwide."], answer: 1 },
      { q: "___ the results, the scientists drew conclusions.", options: ["Analysed", "Having analysed", "Being analysed", "To analyse"], answer: 1 },
    ],
  },
  {
    slug: "inversion",
    level: "IELTS",
    title: "Inversion",
    titleUz: "Inversiya (teskari tartib)",
    emoji: "🔄",
    explanation: [
      "Inversiya — ta'kid uchun gapni savol tartibida qurish. Band 8-9 yozuv va nutqning \"mo'jizaviy quroli\": \"Never have I seen such dedication\" (oddiy: I have never seen...).",
      "Inkor ravishlardan keyin: Never, Rarely, Seldom, Little, Under no circumstances, Not only... — dan keyin yordamchi fe'l EGADAN OLDIN keladi: \"Not only does exercise improve health, but it also boosts mood.\"",
      "'Only' qurilmalari: \"Only when we lose something do we appreciate it\" (faqat yo'qotgandagina qadrlaymiz).",
      "Shartda 'if'siz inversiya: \"Had I known, I would have come\" (= If I had known). \"Should you need help, contact us\" (= If you need). Rasmiy xatlarda juda chiroyli.",
    ],
    formula: "Inkor ravish + yordamchi + ega + fe'l · Had/Should + ega (= if)",
    examples: [
      { en: "Never have I heard such a beautiful voice.", uz: "Bunday go'zal ovozni hech qachon eshitmaganman." },
      { en: "Not only did prices rise, but quality also fell.", uz: "Narxlar oshibgina qolmay, sifat ham tushdi." },
      { en: "Rarely do we consider the long-term effects.", uz: "Uzoq muddatli oqibatlarni kamdan-kam o'ylaymiz." },
      { en: "Only after the accident did the city install traffic lights.", uz: "Faqat avariyadan keyingina shahar svetofor o'rnatdi." },
      { en: "Had I known about the meeting, I would have attended.", uz: "Yig'ilish haqida bilganimda, qatnashgan bo'lardim." },
      { en: "Under no circumstances should children be left alone in cars.", uz: "Hech qanday holatda bolalarni mashinada yolg'iz qoldirib bo'lmaydi." },
    ],
    mistakes: [
      { wrong: "Never I have seen this.", right: "Never have I seen this.", note: "Inkor ravishdan keyin yordamchi fe'l egadan oldin keladi." },
      { wrong: "Not only prices rose, but...", right: "Not only did prices rise, but...", note: "'Not only'dan keyin yordamchi (did) kerak." },
      { wrong: "Had I known it, I would come.", right: "Had I known it, I would have come.", note: "O'tmish sharti — natija 'would have + V3'." },
    ],
    quiz: [
      { q: "Never ___ such heavy rain.", options: ["I saw", "have I seen", "I have seen", "saw I"], answer: 1 },
      { q: "Not only ___ late, but he also forgot the documents.", options: ["he was", "was he", "he is", "is he"], answer: 1 },
      { q: "Only then ___ the truth.", options: ["I understood", "did I understand", "I did understand", "understood I"], answer: 1 },
      { q: "___ you require assistance, please call reception.", options: ["If should", "Should", "Would", "Had"], answer: 1 },
      { q: "Seldom ___ so moved by a performance.", options: ["the audience was", "was the audience", "the audience is", "audience was"], answer: 1 },
    ],
  },
  {
    slug: "cleft-sentences",
    level: "IELTS",
    title: "Cleft sentences",
    titleUz: "Ajratilgan (cleft) gaplar",
    emoji: "💎",
    explanation: [
      "Cleft gaplar fikrning BIR qismini yoritqichga oladi. Oddiy: \"I need more time.\" Cleft: \"What I need is more time\" (menga kerak bo'lgani — vaqt).",
      "'What' clefti: What matters most is honesty. What surprised me was his calmness. Speaking'da fikrlashga vaqt yutish va urg'u berishning a'lo usuli.",
      "'It' clefti: It was the manager who made the mistake (aynan menejer xato qildi — boshqa emas). It is education that transforms societies.",
      "IELTS Writing 2'da pozitsiyani kuchli ifodalash uchun: \"It is governments, rather than individuals, that must lead this change.\"",
    ],
    formula: "What + gap + is/was ... · It is/was X that/who ...",
    examples: [
      { en: "What I love about Tashkent is its food culture.", uz: "Toshkentda menga yoqadigani — uning taom madaniyati." },
      { en: "It was my grandmother who taught me patience.", uz: "Menga sabrni o'rgatgan — buvim edi." },
      { en: "What the city needs is a better metro system.", uz: "Shaharga kerak bo'lgani — yaxshiroq metro tizimi." },
      { en: "It is consistency that leads to success, not luck.", uz: "Muvaffaqiyatga olib boradigani omad emas — izchillik." },
      { en: "What worries scientists is the speed of change.", uz: "Olimlarni tashvishga solayotgani — o'zgarish tezligi." },
      { en: "It was only in 2020 that the law was passed.", uz: "Qonun faqat 2020-yildagina qabul qilindi." },
    ],
    mistakes: [
      { wrong: "What I need is I need more practice.", right: "What I need is more practice.", note: "'Is'dan keyin faqat urg'u berilayotgan qism keladi." },
      { wrong: "It was him who did it. (rasmiy)", right: "It was he who did it.", note: "Rasmiy uslubda 'It was he/she who...' afzal (og'zakida 'him' ham yuradi)." },
      { wrong: "That I want is peace.", right: "What I want is peace.", note: "Cleft 'what' bilan boshlanadi." },
    ],
    quiz: [
      { q: "___ I admire about her is her honesty.", options: ["That", "Which", "What", "Who"], answer: 2 },
      { q: "It was the design ___ attracted investors.", options: ["what", "who", "that", "whose"], answer: 2 },
      { q: "What this district needs ___ more green spaces.", options: ["are", "is", "be", "were"], answer: 1 },
      { q: "\"Aynan mashq muvaffaqiyat keltiradi\":", options: ["Practice is it that brings success.", "It is practice that brings success.", "What practice brings is success it.", "That practice brings success."], answer: 1 },
      { q: "It was in Bukhara ___ they first met.", options: ["where", "that", "which", "when"], answer: 1 },
    ],
  },
  {
    slug: "nominalization",
    level: "IELTS",
    title: "Nominalization (academic style)",
    titleUz: "Nominalizatsiya (akademik uslub)",
    emoji: "🎓",
    explanation: [
      "Nominalizatsiya — fe'l/sifatni OTGA aylantirish. Akademik ingliz tilining DNKsi: \"The government decided to...\" → \"The government's decision to...\"",
      "Taqqoslang: \"Because people use cars more, the air got dirtier\" (og'zaki) → \"The increase in car use has led to a decline in air quality\" (band 8). Fikr bir xil, daraja boshqa.",
      "Asosiy juftliklar: grow → growth, reduce → reduction, improve → improvement, fail → failure, develop → development, aware → awareness, able → ability.",
      "Formulla: [Ot ko'rinishdagi jarayon] + leads to / results in / contributes to + [ot ko'rinishdagi natija]. Task 1 trend tasvirlash: \"a sharp rise in prices\", \"a gradual fall in demand\".",
    ],
    formula: "fe'l → ot: growth, reduction, improvement · X leads to Y",
    examples: [
      { en: "The growth of online shopping has transformed retail.", uz: "Onlayn xaridlarning o'sishi chakana savdoni o'zgartirib yubordi." },
      { en: "A reduction in working hours may improve productivity.", uz: "Ish soatlarining qisqarishi samaradorlikni oshirishi mumkin." },
      { en: "There has been a significant improvement in literacy rates.", uz: "Savodxonlik darajasida sezilarli yaxshilanish yuz berdi." },
      { en: "The failure of the project was due to poor planning.", uz: "Loyihaning muvaffaqiyatsizligi rejaning zaifligidan edi." },
      { en: "Public awareness of climate change is rising.", uz: "Iqlim o'zgarishi haqidagi jamoatchilik xabardorligi ortmoqda." },
      { en: "The graph shows a steady decline in birth rates.", uz: "Grafik tug'ilish darajasining barqaror pasayishini ko'rsatadi." },
    ],
    mistakes: [
      { wrong: "People buy more online and shops close, this is bad.", right: "The shift to online shopping has caused many shops to close.", note: "Akademik uslub: jarayonni ot qilib, aniq bog'lang." },
      { wrong: "The improve of education...", right: "The improvement of education...", note: "Ot shakli: improvement." },
      { wrong: "A rise of prices", right: "A rise in prices", note: "Trend otlari 'in' bilan: a rise/fall/increase IN." },
    ],
    quiz: [
      { q: "'Develop' fe'lining ot shakli:", options: ["developness", "development", "developing", "developed"], answer: 1 },
      { q: "There was a sharp ___ in fuel prices.", options: ["rise", "risen", "rising", "rose"], answer: 0 },
      { q: "The chart shows an increase ___ internet use.", options: ["of", "in", "on", "at"], answer: 1 },
      { q: "Akademik variantni tanlang:", options: ["Cities got bigger fast.", "The cities grew and grew.", "Rapid urban growth occurred.", "Cities big now."], answer: 2 },
      { q: "'Fail' so'zining ot shakli:", options: ["failness", "failure", "failing", "failed"], answer: 1 },
    ],
  },
  {
    slug: "hedging",
    level: "IELTS",
    title: "Hedging (cautious language)",
    titleUz: "Ehtiyotkor til (hedging)",
    emoji: "🛡️",
    explanation: [
      "Akademik yozuvda qat'iy da'vo xavfli: \"Technology makes people lazy\" — isbotlab bo'lmaydi. Hedging — fikrni himoyalangan qilish: \"Technology may make some people less active.\"",
      "Asboblar: modal fe'llar (may, might, could), yumshoq fe'llar (tend to, appear to, seem to), ravishlar (arguably, generally, relatively), miqdor (some, many, a number of).",
      "IELTS Writing 2 uchun oltin shakllar: \"It could be argued that...\", \"This suggests that...\", \"...is likely to...\", \"In many cases,...\"",
      "Muvozanat muhim: har gapni hedge qilish ishonchsiz ko'rsatadi. Faktlar qat'iy, bashorat va umumlashmalar — ehtiyotkor.",
    ],
    formula: "may/might/could · tend to / seem to · arguably / generally · It could be argued that...",
    examples: [
      { en: "Remote work tends to blur the line between office and home.", uz: "Masofaviy ish odatda ish va uy chegarasini xiralashtiradi." },
      { en: "This policy could lead to unintended consequences.", uz: "Bu siyosat kutilmagan oqibatlarga olib kelishi mumkin." },
      { en: "It could be argued that advertising fuels overconsumption.", uz: "Reklama ortiqcha iste'molni kuchaytiradi, deb aytish mumkin." },
      { en: "Young people appear to prefer visual content.", uz: "Yoshlar vizual kontentni afzal ko'radiganga o'xshaydi." },
      { en: "In many cases, early diagnosis saves lives.", uz: "Ko'p hollarda erta tashxis hayotni saqlab qoladi." },
      { en: "The data suggests that the trend will continue.", uz: "Ma'lumotlar tendensiya davom etishini ko'rsatadi." },
    ],
    mistakes: [
      { wrong: "Social media destroys all friendships.", right: "Social media may weaken some friendships.", note: "Mutlaq da'vo (all, destroys) o'rniga ehtiyotkor shakl." },
      { wrong: "Everyone knows that...", right: "It is widely believed that...", note: "'Hamma biladi' — akademik uslubda ishlatilmaydi." },
      { wrong: "This will definitely happen.", right: "This is likely to happen.", note: "Bashoratda 'definitely' o'rniga 'likely'." },
    ],
    quiz: [
      { q: "Stricter laws ___ reduce crime rates.", options: ["will definitely", "may", "must always", "absolutely"], answer: 1 },
      { q: "City dwellers ___ to have less free time.", options: ["tend", "must", "will", "definitely"], answer: 0 },
      { q: "It could be ___ that exams cause unnecessary stress.", options: ["said definitely", "argued", "proven always", "known"], answer: 1 },
      { q: "Eng akademik variant:", options: ["All teenagers are addicted to phones.", "Many teenagers appear to overuse their phones.", "Teenagers always use phones.", "Phones destroy every teenager."], answer: 1 },
      { q: "The evidence ___ that diet affects mood.", options: ["proves 100%", "suggests", "commands", "insists definitely"], answer: 1 },
    ],
  },
  {
    slug: "conditionals-advanced",
    level: "IELTS",
    title: "Advanced conditionals",
    titleUz: "Murakkab shart shakllari",
    emoji: "🧠",
    explanation: [
      "'If' o'rniga boyroq bog'lovchilar band ko'taradi: provided (that) / as long as — \"...sharti bilan\": \"You can borrow my car provided that you drive carefully.\"",
      "'Unless' = if not: \"Unless we act now, it will be too late\" (hozir harakat qilmasak...). Diqqat: unless'dan keyin inkor QO'SHILMAYDI.",
      "'In case' — ehtiyot chorasi (agar emas!): \"Take an umbrella in case it rains\" (yomg'ir yog'ib qolsa deb). \"If it rains\" — yog'sa ochasiz; \"in case it rains\" — oldindan olasiz.",
      "'Otherwise' — aks holda: \"Leave now, otherwise you'll miss the train.\" 'Suppose/supposing' — faraz: \"Suppose you won a million, what would you do?\"",
    ],
    formula: "provided that / as long as (shart bilan) · unless (agar ...masa) · in case (ehtiyot uchun)",
    examples: [
      { en: "You'll pass, provided that you practise daily.", uz: "Har kuni mashq qilsangiz, o'tasiz." },
      { en: "Unless the government intervenes, prices will keep rising.", uz: "Hukumat aralashmasa, narxlar oshaveradi." },
      { en: "Write down my number in case you need help.", uz: "Yordam kerak bo'lib qolsa deb, raqamimni yozib oling." },
      { en: "As long as you respect others, you are welcome here.", uz: "Boshqalarni hurmat qilar ekansiz, bu yerda sizga eshik ochiq." },
      { en: "Hurry up — otherwise we'll be late.", uz: "Shoshiling — aks holda kechikamiz." },
      { en: "Supposing you lost your job, what would you do?", uz: "Faraz qiling, ishingizdan ayrildingiz — nima qilardingiz?" },
    ],
    mistakes: [
      { wrong: "Unless you don't hurry, we'll be late.", right: "Unless you hurry, we'll be late.", note: "'Unless' allaqachon inkorni o'z ichiga oladi." },
      { wrong: "Take a coat if case it gets cold.", right: "Take a coat in case it gets cold.", note: "Ibora: 'in case'." },
      { wrong: "Provided you will study, you will pass.", right: "Provided you study, you will pass.", note: "Shart qismida 'will' ishlatilmaydi." },
    ],
    quiz: [
      { q: "___ you finish your work, you can leave early.", options: ["Unless", "Provided that", "In case", "Otherwise"], answer: 1 },
      { q: "___ it stops raining, the match will be cancelled.", options: ["Provided", "As long as", "Unless", "In case"], answer: 2 },
      { q: "Take some water ___ you get thirsty.", options: ["unless", "in case", "provided", "otherwise"], answer: 1 },
      { q: "Study hard — ___ you will fail.", options: ["otherwise", "unless", "in case", "provided"], answer: 0 },
      { q: "Qaysi gap XATO?", options: ["Unless you hurry, we'll be late.", "Unless you don't hurry, we'll be late.", "Provided you hurry, we'll make it.", "Hurry, otherwise we'll be late."], answer: 1 },
    ],
  },
  {
    slug: "reduced-relative-clauses",
    level: "IELTS",
    title: "Reduced relative clauses",
    titleUz: "Qisqartirilgan aniqlovchi gaplar",
    emoji: "🪶",
    explanation: [
      "Aniqlovchi gapni qisqartirish yozuvni zichroq va akademikroq qiladi: \"The students who are taking the exam\" → \"The students taking the exam\".",
      "Faol ma'noda who/which/that + fe'l → V-ing: \"people who live in cities\" → \"people living in cities\".",
      "Passiv ma'noda who/which + be + V3 → V3: \"the bridge which was built in 1985\" → \"the bridge built in 1985\".",
      "IELTS Task 1'da juda foydali: \"The chart showing population trends...\", \"the figures given in the table...\". Bir gapda ham qisqartirilgan, ham to'liq shaklni aralashtirish mumkin.",
    ],
    formula: "who/which + fe'l → V-ing · who/which + be + V3 → V3",
    examples: [
      { en: "The number of people working remotely has doubled.", uz: "Masofadan ishlaydigan odamlar soni ikki baravar oshdi." },
      { en: "The products sold in this shop are all local.", uz: "Bu do'konda sotiladigan mahsulotlarning bari mahalliy." },
      { en: "Anyone wishing to apply should contact HR.", uz: "Ariza topshirmoqchi bo'lgan har kim HR bilan bog'lansin." },
      { en: "The data collected last year supports this theory.", uz: "O'tgan yili yig'ilgan ma'lumotlar bu nazariyani quvvatlaydi." },
      { en: "Students preparing for IELTS should read widely.", uz: "IELTSga tayyorlanayotgan talabalar keng o'qishlari kerak." },
      { en: "The palace, restored in 2010, is open to visitors.", uz: "2010-yilda ta'mirlangan saroy tashrif uchun ochiq." },
    ],
    mistakes: [
      { wrong: "People living in cities they have more stress.", right: "People living in cities have more stress.", note: "Qisqartirilgan o'ramdan keyin qo'shimcha 'they' kerak emas." },
      { wrong: "The letter sending yesterday arrived.", right: "The letter sent yesterday arrived.", note: "Passiv ma'no — V3 (sent), V-ing emas." },
      { wrong: "The man stands there is my uncle.", right: "The man standing there is my uncle.", note: "Qisqartirishda fe'l V-ing shaklini oladi." },
    ],
    quiz: [
      { q: "The people ___ in the queue looked tired.", options: ["waited", "waiting", "who waiting", "waits"], answer: 1 },
      { q: "The novel ___ into 30 languages is a bestseller.", options: ["translating", "translated", "which translated", "translates"], answer: 1 },
      { q: "Anyone ___ a visa must apply early.", options: ["needing", "needed", "who needing", "needs"], answer: 0 },
      { q: "The figures ___ in the graph relate to 2024.", options: ["showing", "shown", "showed", "show"], answer: 1 },
      { q: "\"The students who are sitting in the hall\" qisqartmasi:", options: ["The students sat in the hall", "The students sitting in the hall", "The students are sitting in the hall", "The sitting students in the hall"], answer: 1 },
    ],
  },
];
