import type { GrammarLesson } from "./types";

/** Additional high-yield structures for Band 7-9 production. */
export const IELTS_ADVANCED_LESSONS: GrammarLesson[] = [
  {
    slug: "mixed-conditionals",
    level: "IELTS",
    title: "Mixed conditionals",
    titleUz: "Aralash shart gaplar",
    emoji: "🧭",
    highlights: ["if", "would", "had", "would have"],
    explanation: [
      "Mixed conditional o'tmishdagi sababni hozirgi natija bilan yoki hozirgi holatni o'tmishdagi natija bilan bog'laydi.",
      "O'tmish sabab + hozirgi natija: If I had studied medicine, I would be a doctor now. Qaror oldin bo'lgan, natija hozir seziladi.",
      "Hozirgi holat + o'tmish natija: If she were more confident, she would have applied for the job. Uning fe'li hozir ham ishonchsiz.",
      "IELTSda bu qurilma sabab-oqibatni aniq qilish uchun foydali, lekin faqat tabiiy joyda ishlating.",
    ],
    formula: "If + had + V3, would + base verb now · If + past simple, would have + V3",
    keyPoints: [
      { title: "Past cause", body: "If + had V3 o'tmishdagi qarorni bildiradi." },
      { title: "Present result", body: "would + verb hozirgi natijani ko'rsatadi." },
      { title: "Natural use", body: "Faqat real sabab-oqibat bo'lsa mixed conditional ishlating." },
    ],
    importantNotes: ["If clause ichida would ishlatilmaydi.", "Were barcha shaxslarda rasmiyroq variant: If I were..."],
    examTips: ["Speaking Part 3da afsus yoki ehtimoliy oqibatni tushuntirishda ishlating.", "Task 2da bir aniq mixed conditional yetarli; har gapni murakkablashtirmang."],
    examples: [
      { en: "If I had saved more money, I would own a home now.", uz: "Ko'proq pul jamg'arganimda, hozir uyim bo'lardi." },
      { en: "If cities had planned better, traffic would be less severe today.", uz: "Shaharlar yaxshiroq rejalashtirganida, bugun tirbandlik kamroq bo'lardi." },
      { en: "If he were more organised, he would have met the deadline.", uz: "U tartibliroq bo'lganida, muddatga ulgurgan bo'lardi." },
      { en: "If people cared more about health, they would have changed their diets earlier.", uz: "Odamlar sog'liqqa ko'proq e'tibor berganida, ovqatlanishini oldinroq o'zgartirgan bo'lardi." },
      { en: "If I had taken that course, I would understand the topic now.", uz: "O'sha kursni olganimda, hozir mavzuni tushungan bo'lardim." },
      { en: "If the company were better managed, it would not have lost clients.", uz: "Kompaniya yaxshiroq boshqarilganda, mijozlarini yo'qotmagan bo'lardi." },
    ],
    mistakes: [
      { wrong: "If I would have studied, I would know it now.", right: "If I had studied, I would know it now.", note: "If clause ichida had + V3 kerak." },
      { wrong: "If she was confident, she would have applied.", right: "If she were confident, she would have applied.", note: "Hypothetical hozirgi holatda 'were' tabiiyroq." },
      { wrong: "If they had planned, they would have had less traffic now.", right: "If they had planned, they would have less traffic now.", note: "Natija hozirgi paytga tegishli bo'lsa, would + base verb ishlatiladi ('would have had' o'tmish natijasini bildiradi)." },
    ],
    quiz: [
      { q: "If I had accepted the offer, I ___ abroad now.", options: ["lived", "would live", "would have lived", "will live"], answer: 1 },
      { q: "If she ___ more patient by nature, she would have finished the course.", options: ["is", "were", "would be", "will be"], answer: 1 },
      { q: "If cities had invested earlier, air quality ___ better today.", options: ["would be", "would have been", "is", "was"], answer: 0 },
      { q: "Qaysi shakl mixed conditional?", options: ["If it rains, we will stay.", "If I had known, I would have called.", "If I had trained, I would be fitter now.", "If I were rich, I would travel."], answer: 2 },
      { q: "If he ___ a more careful person, he would not have made that mistake.", options: ["is", "were", "would be", "will be"], answer: 1 },
    ],
  },
  {
    slug: "passive-reporting-verbs",
    level: "IELTS",
    title: "Passive reporting verbs",
    titleUz: "Passiv reporting fe'llari",
    emoji: "🗞️",
    highlights: ["is believed to", "is thought to", "is expected to", "have + V3"],
    explanation: [
      "Passive reporting verbs kim aytganini emas, ma'lumotning o'zini markazga qo'yadi: People believe that prices will rise -> Prices are believed to rise.",
      "Hozirgi yoki kelajak ma'lumot uchun is/are believed, thought, expected, known, reported to + verb ishlatiladi.",
      "Oldingi holat uchun perfect infinitive qo'shiladi: The policy is believed to have reduced pollution.",
      "Bu struktura Task 1 va Task 2da research yoki umumiy fikrni ehtiyotkor, akademik tarzda berishga yordam beradi.",
    ],
    formula: "subject + is/are + reported/believed/expected + to + verb · to have + V3",
    keyPoints: [
      { title: "Impersonal tone", body: "Manbasi noma'lum yoki umumiy bo'lsa akademik ohang beradi." },
      { title: "Time", body: "Oldingi action uchun to have + V3 ishlating." },
      { title: "Evidence", body: "Is believed deb yozsangiz, uni fact sifatida ko'rsatmang." },
    ],
    importantNotes: ["People say that bilan ma'no bir xil, lekin passive report formalroq.", "Say va tell fe'llari bu patternni bir xil qabul qilmaydi."],
    examTips: ["Writingda 'It is widely believed that...' ni haddan tashqari takrorlamang.", "Readingda shu patternni active paraphrase bilan bog'lashni mashq qiling."],
    examples: [
      { en: "The new rail line is expected to reduce congestion.", uz: "Yangi temiryo'l liniyasi tirbandlikni kamaytirishi kutilmoqda." },
      { en: "Online learning is thought to widen access to education.", uz: "Onlayn ta'lim ta'limga kirishni kengaytiradi deb hisoblanadi." },
      { en: "The species is believed to have adapted to warmer water.", uz: "Bu tur iliqroq suvga moslashgan deb hisoblanadi." },
      { en: "The figures are reported to be inaccurate.", uz: "Bu raqamlar noto'g'ri ekani xabar qilinmoqda." },
      { en: "Public transport is known to lower household costs.", uz: "Jamoat transporti uy xo'jaligi xarajatlarini kamaytirishi ma'lum." },
      { en: "The company is said to be considering a new policy.", uz: "Kompaniya yangi siyosatni ko'rib chiqayotgani aytilmoqda." },
    ],
    mistakes: [
      { wrong: "The policy is believed that it works.", right: "The policy is believed to work.", note: "Passive subjectdan keyin to + verb keladi." },
      { wrong: "The scheme is expected reducing costs.", right: "The scheme is expected to reduce costs.", note: "Expected dan keyin infinitive ishlatiladi." },
      { wrong: "The change is believed to reduced pollution.", right: "The change is believed to have reduced pollution.", note: "Oldingi natija uchun to have + V3 kerak." },
    ],
    quiz: [
      { q: "The medicine is believed ___ effective.", options: ["being", "to be", "be", "to being"], answer: 1 },
      { q: "The policy is thought ___ emissions last year.", options: ["reduce", "to reduce", "to have reduced", "reduced"], answer: 2 },
      { q: "The results are reported ___ unreliable.", options: ["be", "to be", "being", "been"], answer: 1 },
      { q: "Formal passive reportni tanlang:", options: ["People think the trend will continue.", "The trend is thought to continue.", "The trend thinks to continue.", "It thinks trend continue."], answer: 1 },
      { q: "The company is said ___ a new product.", options: ["launch", "to launch", "launched", "launching to"], answer: 1 },
    ],
  },
  {
    slug: "concession-despite-in-spite-of",
    level: "IELTS",
    title: "Concession: despite and in spite of",
    titleUz: "Qarama-qarshilik: despite va in spite of",
    emoji: "⚖️",
    highlights: ["despite", "in spite of", "although", "the fact that"],
    explanation: [
      "Despite va in spite of 'ga qaramay' degani. Ular noun, pronoun yoki V-ing bilan keladi: despite high costs, in spite of working late.",
      "To'liq clause kerak bo'lsa despite the fact that yoki although ishlating: Although costs are high, ...",
      "Despite va in spite of ma'no jihatdan bir xil; essayda qisqa va aniq variantni tanlash kifoya.",
      "Bu connector ikki qarama-qarshi fikrni bog'lab, Task 1 trend yoki Task 2 argumentni aniqroq qiladi.",
    ],
    formula: "despite/in spite of + noun | V-ing · although + subject + verb",
    keyPoints: [
      { title: "No full clause", body: "Despite dan keyin subject + verbni bevosita qo'ymang." },
      { title: "Verb form", body: "Action bo'lsa V-ing: despite being expensive." },
      { title: "Contrast", body: "Kutilgan natija bo'lmaganini ko'rsatish uchun ishlating." },
    ],
    importantNotes: ["Despite of xato; faqat despite yoki in spite of.", "Although va despite ni bir gapda ortiqcha birlashtirmang."],
    examTips: ["Task 1da: Despite a fall in..., the figure remained high.", "Speakingda contrast uchun 'even though' ham tabiiy alternativ."],
    examples: [
      { en: "Despite the rain, the event attracted thousands of visitors.", uz: "Yomg'irga qaramay, tadbir minglab mehmonni jalb qildi." },
      { en: "In spite of being expensive, the course is popular.", uz: "Qimmat bo'lishiga qaramay, kurs ommabop." },
      { en: "Despite working full time, she attends evening classes.", uz: "To'liq stavkada ishlashiga qaramay, u kechki darslarga qatnaydi." },
      { en: "Although the city is crowded, it remains attractive to students.", uz: "Shahar gavjum bo'lsa-da, u talabalar uchun jozibali bo'lib qoladi." },
      { en: "Despite the fact that tickets were cheap, few people came.", uz: "Chiptalar arzon bo'lganiga qaramay, kam odam keldi." },
      { en: "In spite of repeated warnings, he continued to speed.", uz: "Qayta-qayta ogohlantirishlarga qaramay, u tez haydashda davom etdi." },
    ],
    mistakes: [
      { wrong: "Despite of the rain, we went out.", right: "Despite the rain, we went out.", note: "Despite dan keyin of kelmaydi." },
      { wrong: "Despite it was late, we continued.", right: "Although it was late, we continued.", note: "To'liq clause uchun although ishlating." },
      { wrong: "Despite to be tired, she worked.", right: "Despite being tired, she worked.", note: "Despite dan keyin V-ing keladi." },
    ],
    quiz: [
      { q: "___ the high price, demand remained strong.", options: ["Despite", "Although", "Because", "However"], answer: 0 },
      { q: "In spite of ___ late, he finished the task.", options: ["be", "being", "was", "to be"], answer: 1 },
      { q: "___ it was raining, they played outside.", options: ["Despite", "In spite", "Although", "Despite of"], answer: 2 },
      { q: "Qaysi biri xato?", options: ["despite the cost", "in spite of the cost", "despite of the cost", "although it costs a lot"], answer: 2 },
      { q: "Despite the fact that he ___ tired, he worked.", options: ["is", "was", "being", "be"], answer: 1 },
    ],
  },
  {
    slug: "future-in-time-clauses",
    level: "IELTS",
    title: "Future in time clauses",
    titleUz: "Vaqt ergash gaplarida kelasi zamon",
    emoji: "⏳",
    highlights: ["when", "until", "as soon as", "before", "present simple"],
    explanation: [
      "When, before, after, until, as soon as va once bilan boshlangan vaqt clause ichida kelajak haqida gapirsak ham odatda will ishlatilmaydi.",
      "To'g'ri: When the course ends, I will take the exam. Noto'g'ri: When the course will end...",
      "Main clause kelajakni will, may yoki imperative bilan beradi; time clause esa present simple yoki present perfect ishlatadi.",
      "Bu qoida Speaking va email writingda juda ko'p ishlatiladi, shuning uchun avtomatik bo'lishi kerak.",
    ],
    formula: "when/until/as soon as + present simple, will + verb",
    keyPoints: [
      { title: "Time clause", body: "When va until dan keyin will emas, present simple." },
      { title: "Completed future", body: "After/once + present perfect tugagan actionni urg'ulaydi." },
      { title: "Main clause", body: "Kelajak ma'nosi asosiy gapda will bilan keladi." },
    ],
    importantNotes: ["If clause ham shu qoida bilan: If it rains, we will stay.", "Will faqat willingness ma'nosida time clause ichida kamdan-kam kelishi mumkin."],
    examTips: ["Speakingda rejani aniq ayting: When I graduate, I will...", "Formal emailda: Please let us know once you receive the package."],
    examples: [
      { en: "When I finish university, I will look for a full-time job.", uz: "Universitetni tugatganimda, to'liq stavkali ish qidiraman." },
      { en: "We will start as soon as everyone arrives.", uz: "Hamma kelishi bilanoq boshlaymiz." },
      { en: "Do not leave until the teacher gives permission.", uz: "O'qituvchi ruxsat bermaguncha ketmang." },
      { en: "After she has submitted the form, she will receive a message.", uz: "U formani yuborgach, xabar oladi." },
      { en: "Once the weather improves, tourists will return.", uz: "Ob-havo yaxshilangach, sayyohlar qaytadi." },
      { en: "Before you make a decision, compare the options carefully.", uz: "Qaror qabul qilishdan oldin, variantlarni diqqat bilan solishtiring." },
    ],
    mistakes: [
      { wrong: "When I will arrive, I will call you.", right: "When I arrive, I will call you.", note: "When clause ichida present simple ishlatiladi." },
      { wrong: "We will wait until he will come.", right: "We will wait until he comes.", note: "Until dan keyin will ishlatmang." },
      { wrong: "After I will finish, I go home.", right: "After I finish, I will go home.", note: "Will asosiy gapga o'tadi." },
    ],
    quiz: [
      { q: "When she ___, we will begin.", options: ["will arrive", "arrives", "arrived", "arriving"], answer: 1 },
      { q: "I will call you as soon as I ___ home.", options: ["will get", "get", "got", "getting"], answer: 1 },
      { q: "Do not submit the form until you ___ it.", options: ["will check", "check", "checked", "checking"], answer: 1 },
      { q: "Once the project ___, we will publish the results.", options: ["completes", "is complete", "will complete", "completed"], answer: 1 },
      { q: "Qaysi gap to'g'ri?", options: ["Before I will leave, I will email you.", "Before I leave, I will email you.", "Before I leave, I email you yesterday.", "Before leaving will, I email."], answer: 1 },
    ],
  },
  {
    slug: "verb-patterns-reporting-and-stance",
    level: "IELTS",
    title: "Verb patterns for reporting and stance",
    titleUz: "Reporting va pozitsiya fe'l patternlari",
    emoji: "🧩",
    highlights: ["suggest doing", "recommend that", "avoid doing", "tend to"],
    explanation: [
      "Advanced writingda verbdan keyingi shakl ko'p xato qilinadi. Suggest va recommend odatda V-ing yoki that clause bilan keladi.",
      "Avoid, consider, admit, deny va involve dan keyin gerund keladi: avoid wasting, consider moving.",
      "Tend, appear, seem, claim va aim dan keyin to-infinitive keladi: tend to increase, appear to be.",
      "To'g'ri pattern vocabulary va grammar score uchun birdek muhim, chunki bitta xato butun gapni buzishi mumkin.",
    ],
    formula: "suggest/recommend + V-ing | that + clause · avoid/consider + V-ing · tend/seem + to + verb",
    keyPoints: [
      { title: "Gerund group", body: "avoid, consider, suggest bilan V-ing ishlating." },
      { title: "Infinitive group", body: "tend, seem, appear bilan to + verb ishlating." },
      { title: "That clause", body: "recommend that governments invest... formal essay uchun yaxshi." },
    ],
    importantNotes: ["Suggest to do xato; suggest doing yoki suggest that...", "Recommend someone to do odatda bu ma'noda ishlatilmaydi."],
    examTips: ["Task 2 conclusionda recommend that + subject + base verb juda foydali.", "Readingda verb pattern meaningni aniqlashga yordam beradi."],
    examples: [
      { en: "Experts suggest investing more in early education.", uz: "Mutaxassislar erta ta'limga ko'proq sarmoya kiritishni taklif qiladi." },
      { en: "I recommend that the city improve its bus network.", uz: "Shahar avtobus tarmog'ini yaxshilashini tavsiya qilaman." },
      { en: "Many students avoid speaking because they fear mistakes.", uz: "Ko'p talabalar xatodan qo'rqqani uchun gapirishdan qochadi." },
      { en: "Young adults tend to use digital payments more often.", uz: "Yosh kattalar raqamli to'lovlardan ko'proq foydalanishga moyil." },
      { en: "The data appears to support the first explanation.", uz: "Ma'lumotlar birinchi izohni qo'llab-quvvatlayotgandek ko'rinadi." },
      { en: "The council considered building a new public library.", uz: "Kengash yangi jamoat kutubxonasi qurishni ko'rib chiqdi." },
    ],
    mistakes: [
      { wrong: "They suggest to invest more.", right: "They suggest investing more.", note: "Suggest dan keyin V-ing ishlating." },
      { wrong: "She avoided to answer.", right: "She avoided answering.", note: "Avoid + gerund." },
      { wrong: "The trend tends increasing.", right: "The trend tends to increase.", note: "Tend + to-infinitive." },
    ],
    quiz: [
      { q: "Experts recommend ___ public transport.", options: ["improve", "improving", "to improving", "improved"], answer: 1 },
      { q: "The report suggests that governments ___ more.", options: ["invest", "investing", "to invest", "invested"], answer: 0 },
      { q: "Many people avoid ___ waste.", options: ["create", "creating", "to create", "created"], answer: 1 },
      { q: "Prices tend ___ during winter.", options: ["rise", "to rise", "rising", "risen"], answer: 1 },
      { q: "The results appear ___ reliable.", options: ["be", "to be", "being", "been"], answer: 1 },
    ],
  },
  {
    slug: "relative-clauses-with-prepositions",
    level: "IELTS",
    title: "Relative clauses with prepositions",
    titleUz: "Predlogli relative clause'lar",
    emoji: "🔗",
    highlights: ["to whom", "for which", "in which", "whose"],
    explanation: [
      "Formal relative clause'da predlog relative pronoun oldiga chiqishi mumkin: the person to whom I spoke, the issue about which we disagreed.",
      "Kundalik nutqda predlog oxirida qoladi: the person who I spoke to. IELTS Writingda formal variantni ba'zan ishlatish yaxshi taassurot beradi.",
      "Which narsalar, whom odamlar uchun ishlatiladi. Whose esa egalikni bildiradi: a company whose profits increased.",
      "Juda uzun relative clause o'quvchini charchatadi; formal grammar clarity o'rnini bosmaydi.",
    ],
    formula: "noun + preposition + which/whom · noun + whose + noun",
    keyPoints: [
      { title: "Formal order", body: "preposition + which/whom writing uchun rasmiyroq." },
      { title: "People", body: "To whom, with whom kabi shakllar odamlar bilan keladi." },
      { title: "Possession", body: "Whose odam va narsalar uchun ham ishlatilishi mumkin." },
    ],
    importantNotes: ["Preposition oldida that ishlatilmaydi: the issue about which, not about that.", "Who o'rniga whom rasmiy object holatda keladi."],
    examTips: ["Task 1da 'the period during which' kabi phrase'lar tabiiy.", "Speakingda haddan tashqari formal bo'lmang; oddiy relative clause yetarli."],
    examples: [
      { en: "The programme from which students benefit is free.", uz: "Talabalar foyda oladigan dastur bepul." },
      { en: "The colleague with whom I worked was very supportive.", uz: "Men birga ishlagan hamkasb juda qo'llab-quvvatlovchi edi." },
      { en: "This is the reason for which the policy was introduced.", uz: "Bu siyosat joriy qilingan sabab shu." },
      { en: "The city in which I grew up has changed greatly.", uz: "Men ulg'aygan shahar juda o'zgardi." },
      { en: "They visited a village whose economy depends on tourism.", uz: "Ular iqtisodiyoti turizmga bog'liq qishloqqa tashrif buyurdi." },
      { en: "The period during which sales rose was relatively short.", uz: "Savdo oshgan davr nisbatan qisqa edi." },
    ],
    mistakes: [
      { wrong: "The issue about that we argued", right: "The issue about which we argued", note: "Predlogdan keyin which/whom, that emas." },
      { wrong: "The person to who I spoke", right: "The person to whom I spoke", note: "Formal object shakli whom." },
      { wrong: "The company which profits rose", right: "The company whose profits rose", note: "Egalik uchun whose ishlating." },
    ],
    quiz: [
      { q: "The topic ___ we discussed was difficult.", options: ["about which", "about that", "which about", "about who"], answer: 0 },
      { q: "The person ___ I spoke was helpful.", options: ["to whom", "to which", "whose", "that to"], answer: 0 },
      { q: "A company ___ staff are well trained performs better.", options: ["which", "whose", "whom", "where"], answer: 1 },
      { q: "The year ___ the law changed was 2024.", options: ["during which", "during that", "which during", "whom"], answer: 0 },
      { q: "Formal variantni tanlang:", options: ["the town I live in", "the town in which I live", "the town which I live", "the town in that I live"], answer: 1 },
    ],
  },
  {
    slug: "advanced-article-choices",
    level: "IELTS",
    title: "Advanced article choices",
    titleUz: "Murakkab article tanlovi",
    emoji: "🔎",
    highlights: ["the", "zero article", "a", "an", "general"],
    explanation: [
      "Article xatolari IELTSda juda ko'p uchraydi. A/an bir noma'lum countable item, the aniq yoki yagona narsa, zero article esa umumiy plural va uncountable idea bilan keladi.",
      "General idea: Education improves lives. Aniq tizim: The education system in this city needs reform.",
      "Institutions ko'pincha zero article oladi: go to school, be in prison, at university. Lekin building nazarda tutilsa the school ishlatiladi.",
      "Geography va groups ham o'ziga xos: the Netherlands, the elderly, but Uzbekistan and young people.",
    ],
    formula: "a/an = one non-specific · the = specific/unique · zero = general plural/uncountable",
    keyPoints: [
      { title: "General vs specific", body: "General education va the education system bir xil emas." },
      { title: "Countability", body: "Advice, information, research uncountable; a bilan kelmaydi." },
      { title: "Context", body: "Narsa oldin tilga olinsa, keyin the ishlating." },
    ],
    importantNotes: ["The people umumiy odamlar emas, aniq guruh uchun.", "An information xato; a piece of information deng."],
    examTips: ["Essayni tekshirganda general abstract nouns oldidagi the'ni tekshiring.", "Task 1da the number of, the percentage of kabi aniq phrase'larni yodlang."],
    examples: [
      { en: "Education can transform lives, especially in rural areas.", uz: "Ta'lim, ayniqsa qishloq joylarda, hayotni o'zgartirishi mumkin." },
      { en: "The education system needs more practical training.", uz: "Ta'lim tizimiga ko'proq amaliy tayyorgarlik kerak." },
      { en: "She gave me a useful piece of advice.", uz: "U menga foydali bir maslahat berdi." },
      { en: "Young people often use social media for news.", uz: "Yoshlar ko'pincha yangilik uchun ijtimoiy tarmoqlardan foydalanadi." },
      { en: "The elderly may need better access to healthcare.", uz: "Keksalarga sog'liqni saqlashga yaxshiroq kirish kerak bo'lishi mumkin." },
      { en: "He went to school to meet the head teacher.", uz: "U direktor bilan uchrashish uchun maktabga bordi." },
    ],
    mistakes: [
      { wrong: "The education is important for everyone.", right: "Education is important for everyone.", note: "General abstract idea bilan zero article." },
      { wrong: "She gave me an advice.", right: "She gave me some advice.", note: "Advice uncountable." },
      { wrong: "People should help the elderly people.", right: "People should help the elderly.", note: "The + adjective guruhni bildiradi." },
    ],
    quiz: [
      { q: "___ information on this page is useful.", options: ["A", "An", "The", "An information"], answer: 2 },
      { q: "___ education is essential for development.", options: ["A", "An", "The", "Zero article"], answer: 3 },
      { q: "She gave me ___ advice.", options: ["an", "a", "some", "the a"], answer: 2 },
      { q: "___ elderly often need extra support.", options: ["Elderly", "The elderly", "An elderly", "A elderly"], answer: 1 },
      { q: "We visited ___ school where my mother teaches.", options: ["school", "a school", "the school", "an school"], answer: 2 },
    ],
  },
  {
    slug: "cohesion-reference-words",
    level: "IELTS",
    title: "Cohesion with reference words",
    titleUz: "Reference so'zlar bilan cohesion",
    emoji: "🧵",
    highlights: ["this", "these", "such", "former", "latter"],
    explanation: [
      "Reference words oldingi fikrga qaytib, takrorni kamaytiradi: this trend, these measures, such a policy. Ular cohesion beradi.",
      "This/that birlik idea yoki noun, these/those ko'plik noun bilan mos keladi. Reference qaysi idea ekanini o'quvchi darhol anglashini tekshiring.",
      "Former va latter faqat ikki narsa aniq tilga olinganda ishlating. Uch yoki ko'p variantda ular noaniq bo'ladi.",
      "Task 1 va Task 2da reference words paragraph ichidagi oqimni yaxshilaydi, ammo ular topic noun o'rnini to'liq yashirmasligi kerak.",
    ],
    formula: "this/that + singular idea · these/those + plural noun · such + a/an + noun",
    keyPoints: [
      { title: "Clear noun", body: "This dan keyin trend, change, problem kabi noun qo'shsangiz clarity oshadi." },
      { title: "Number agreement", body: "These measures, this measure; birlik-ko'plikni tekshiring." },
      { title: "Avoid ambiguity", body: "Oldingi gapda ikki idea bo'lsa, this alone noaniq bo'lishi mumkin." },
    ],
    importantNotes: ["This is bad kabi umumiy gapdan qoching; this development is harmful deng.", "Former/latter odatda aynan ikki item bilan ishlatiladi."],
    examTips: ["Har body paragraphda 1-2 aniq reference phrase yetadi.", "Readingda this/these nimaga ishora qilayotganini oldingi gapdan toping."],
    examples: [
      { en: "Car ownership rose sharply. This trend increased congestion.", uz: "Avtomobil egaligi keskin oshdi. Bu trend tirbandlikni kuchaytirdi." },
      { en: "Cities need cleaner buses. These measures can improve air quality.", uz: "Shaharlarga tozaroq avtobuslar kerak. Bu choralar havo sifatini yaxshilashi mumkin." },
      { en: "Such a policy would benefit low-income families.", uz: "Bunday siyosat kam daromadli oilalarga foyda keltiradi." },
      { en: "The chart compares trains and buses; the former carried more passengers.", uz: "Grafik poyezdlar va avtobuslarni solishtiradi; birinchisi ko'proq yo'lovchi tashigan." },
      { en: "This development may have long-term consequences.", uz: "Bu rivojlanish uzoq muddatli oqibatlarga ega bo'lishi mumkin." },
      { en: "Those who work remotely often save commuting time.", uz: "Masofadan ishlaydiganlar ko'pincha qatnov vaqtini tejaydi." },
    ],
    mistakes: [
      { wrong: "This are useful measures.", right: "These are useful measures.", note: "Ko'plik noun bilan these ishlating." },
      { wrong: "This is bad. (no context)", right: "This development is harmful to local businesses.", note: "Reference noun bilan aniq bo'lsin." },
      { wrong: "There were cars, buses and trains; the latter was fastest.", right: "There were cars, buses and trains; trains were fastest.", note: "Latter faqat ikki itemda aniq." },
    ],
    quiz: [
      { q: "Sales fell in June. ___ decline was unexpected.", options: ["These", "This", "Those", "Former"], answer: 1 },
      { q: "Governments introduced several laws. ___ laws improved safety.", options: ["This", "That", "These", "Former"], answer: 2 },
      { q: "It was ___ a difficult task that few people finished.", options: ["this", "such", "these", "former"], answer: 1 },
      { q: "The graph compares tea and coffee; ___ was more popular.", options: ["the latter", "these", "such", "those"], answer: 0 },
      { q: "Qaysi phrase aniqroq?", options: ["This is bad.", "This development is harmful.", "That bad.", "These is harmful."], answer: 1 },
    ],
  },
];
