from fastapi import APIRouter

from app.api.v1 import admin, ai, auth, coach, coach_live, expressions, flashcards, gamification, games, grammar_progress, ielts, ielts_mock, library, multiplayer, payments, skills, social, statistics, teacher, tts, users, vocabulary, writing_master_progress

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(vocabulary.router)
api_router.include_router(vocabulary.admin_router)
api_router.include_router(flashcards.router)
api_router.include_router(gamification.router)
api_router.include_router(games.router)
api_router.include_router(statistics.router)
api_router.include_router(grammar_progress.router)
api_router.include_router(writing_master_progress.router)
api_router.include_router(ai.router)
api_router.include_router(coach.router)
api_router.include_router(coach_live.router)
api_router.include_router(ielts.router)
api_router.include_router(ielts_mock.router)
api_router.include_router(payments.router)
api_router.include_router(payments.gateway_router)
api_router.include_router(teacher.router)
api_router.include_router(admin.router)
api_router.include_router(social.router)
api_router.include_router(multiplayer.router)
api_router.include_router(skills.router)
api_router.include_router(tts.router)
api_router.include_router(library.router)
api_router.include_router(expressions.router)
