#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
SITE_URL="https://vocora.uz"
SITE_READY=false

banner "Vocora · Google Search Console setup"

stage "Production SEO endpoints"
say "Google can only verify and crawl pages that are publicly reachable."
if curl -fsS "$SITE_URL/uz" >/dev/null 2>&1 \
  && curl -fsS "$SITE_URL/sitemap.xml" >/dev/null 2>&1 \
  && curl -fsS "$SITE_URL/robots.txt" | grep -Fq "Sitemap: $SITE_URL/sitemap.xml"; then
  SITE_READY=true
  say "✓ Homepage, sitemap.xml, and robots.txt are reachable."
else
  warn "Vocora is not fully crawlable yet. Deploy/start the server and Cloudflare tunnel first."
  SKIPPED+=("crawlability gate — confirm /uz, /sitemap.xml, and the Sitemap line in /robots.txt return HTTP 200")
fi
pause "Press Enter to continue with domain ownership setup."

stage "Search Console · Domain property"
say "Use a Domain property so https/http, www, api, and future subdomains are covered together."
open_url "https://search.google.com/search-console/welcome"
step "Open the property selector and choose + Add property."
step "Under Domain, enter exactly: vocora.uz"
step "Click Continue. Domain property uses DNS verification; HTML tag/file options mean URL-prefix was selected by mistake."
GOOGLE_SITE_VERIFICATION=""
if confirm "Does Google say the Domain property is already verified automatically?"; then
  say "✓ No new TXT record is needed. Keep the existing verification record in DNS."
else
  ask GOOGLE_SITE_VERIFICATION "Paste the TXT value (starts google-site-verification=):"
  if [[ "$GOOGLE_SITE_VERIFICATION" != google-site-verification=* ]]; then
    warn "The value does not start with google-site-verification=. Return and choose the Domain property, then copy its TXT value."
    pause "Press Enter after you have the correct value."
  fi
fi

stage "Cloudflare · DNS verification"
if [[ -z "$GOOGLE_SITE_VERIFICATION" ]]; then
  say "Skipped: Google reported that ownership is already verified."
else
  open_url "https://dash.cloudflare.com/"
  step "Select vocora.uz → DNS → Records → Add record."
  step "Type: TXT"
  step "Name: @"
  step "Content: $GOOGLE_SITE_VERIFICATION"
  step "TTL: Auto, then Save. Do not put this value in .env."
  pause "Press Enter after the TXT record is saved."
  if command -v dig >/dev/null 2>&1 && dig TXT vocora.uz +short | grep -Fq "$GOOGLE_SITE_VERIFICATION"; then
    say "✓ Google verification TXT is visible in public DNS."
  else
    warn "TXT is not visible yet. DNS propagation can take several minutes; verify again shortly."
  fi
fi

stage "Search Console · Verify ownership"
open_url "https://search.google.com/search-console/welcome"
step "Return to the vocora.uz verification dialog."
step "Click Verify. Keep the Cloudflare TXT record after verification."
pause "Press Enter after Search Console shows Ownership verified."

stage "Submit XML sitemap"
if [[ "$SITE_READY" != true ]]; then
  warn "The earlier crawlability gate failed. Fix the server/tunnel before submitting the sitemap."
  SKIPPED+=("Search Console sitemap submission — submit sitemap.xml after the production endpoint returns HTTP 200")
else
  open_url "https://search.google.com/search-console/sitemaps?resource_id=sc-domain%3Avocora.uz"
  step "If the Add a new sitemap box is empty, enter the full URL: $SITE_URL/sitemap.xml"
  step "If the box already displays the $SITE_URL/ prefix, enter only: sitemap.xml"
  step "Click Submit and confirm the status becomes Success."
  pause "Press Enter after sitemap.xml is submitted."
fi

stage "Request first indexing"
open_url "https://search.google.com/search-console/inspect?resource_id=sc-domain%3Avocora.uz"
step "Inspect https://vocora.uz/uz and click Request indexing."
step "Repeat for /uz/vocabulary, /uz/grammar, and /uz/ielts."
step "Use Page indexing and Sitemaps reports later; do not repeatedly request the same URL."
note "Google may need several days or weeks to crawl and process new pages."
pause "Press Enter to finish."

finish
