#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

valid_resend_key() {
  [[ "$1" == re_* && ${#1} -ge 12 ]]
}

normalize_email_from() {
  local value="$1"
  if [[ ${#value} -ge 2 ]] && {
    [[ "${value:0:1}" == '"' && "${value: -1}" == '"' ]] \
      || [[ "${value:0:1}" == "'" && "${value: -1}" == "'" ]];
  }; then
    value="${value:1:${#value}-2}"
  fi
  printf '%s' "$value"
}

valid_email_from() {
  local value
  value="$(normalize_email_from "$1")"
  [[ "$value" =~ ^[^\<\>]+\ \<[^\<\>[:space:]]+@vocora\.uz\>$ ]]
}

persist_resend_config() {
  local api_key="$1" email_from
  email_from="$(normalize_email_from "$2")"
  valid_resend_key "$api_key" || return 1
  valid_email_from "$email_from" || return 1
  write_env EMAIL_PROVIDER resend
  write_env RESEND_API_KEY "$api_key"
  write_env EMAIL_FROM "$email_from"
  write_env EMAIL_REPLY_TO support@vocora.uz
}

normalize_cloudflare_tunnel_token() {
  local value="$1"
  if [[ "$value" =~ --token(=|[[:space:]]+)([^[:space:]\"\']+) ]]; then
    value="${BASH_REMATCH[2]}"
  fi
  if [[ ${#value} -ge 2 ]] && {
    [[ "${value:0:1}" == '"' && "${value: -1}" == '"' ]] \
      || [[ "${value:0:1}" == "'" && "${value: -1}" == "'" ]];
  }; then
    value="${value:1:${#value}-2}"
  fi
  printf '%s' "$value"
}

valid_cloudflare_tunnel_token() {
  local value
  value="$(normalize_cloudflare_tunnel_token "$1")"
  [[ "$value" =~ ^eyJ[A-Za-z0-9_-]{100,}$ ]]
}

persist_cloudflare_tunnel_token() {
  local token
  token="$(normalize_cloudflare_tunnel_token "$1")"
  valid_cloudflare_tunnel_token "$token" || return 1
  write_env CLOUDFLARE_TUNNEL_TOKEN "$token"
}

if [[ "${WIZARD_VALIDATE_ONLY:-}" == "1" ]]; then
  return 0 2>/dev/null || exit 0
fi

banner "Vocora production setup"

stage "Secure production baseline"
say "Values are collected now and activated only after every required stage is complete."
current_secret="$(_existing SECRET_KEY || true)"
if [[ ${#current_secret} -lt 48 ]] || [[ "$current_secret" =~ change|replace|paste|generate|\<|\> ]]; then
  SECRET_KEY_VALUE="$(openssl rand -hex 48)"
  note "Generated a new high-entropy SECRET_KEY; its value is not displayed."
else
  SECRET_KEY_VALUE="$current_secret"
  note "Existing strong SECRET_KEY kept."
fi
warn "Changing a Postgres password does not rotate an existing database role."
DB_READY=false
existing_db_password="$(_existing POSTGRES_PASSWORD || true)"
if [[ "$existing_db_password" =~ ^[A-Za-z0-9_-]{24,}$ ]] && [[ "$existing_db_password" != "words" ]]; then
  POSTGRES_PASSWORD="$existing_db_password"
  DB_READY=true
  note "Existing non-default Postgres credentials kept."
elif docker compose exec -T postgres psql -U words -d words -Atqc "SELECT 1" >/dev/null 2>&1; then
  step "A running existing Postgres database was detected."
  if confirm "Generate a hidden password and rotate the existing words role now?"; then
    POSTGRES_PASSWORD="$(openssl rand -hex 24)"
    printf "ALTER ROLE words WITH PASSWORD '%s';\n" "$POSTGRES_PASSWORD" \
      | docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U words -d words >/dev/null
    DB_READY=true
    write_env POSTGRES_USER words
    write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
    write_env POSTGRES_DB words
    write_env DATABASE_URL "postgresql+asyncpg://words:${POSTGRES_PASSWORD}@postgres:5432/words"
    note "Database role rotated; the generated password was not displayed."
  else
    SKIPPED+=("Rotate POSTGRES_PASSWORD and matching DATABASE_URL")
  fi
else
  warn "No running Postgres database was detected."
  if confirm "Is this a brand-new production database with no existing pgdata volume?"; then
    POSTGRES_PASSWORD="$(openssl rand -hex 24)"
    DB_READY=true
    write_env POSTGRES_USER words
    write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
    write_env POSTGRES_DB words
    write_env DATABASE_URL "postgresql+asyncpg://words:${POSTGRES_PASSWORD}@postgres:5432/words"
    note "Generated a hidden password for the new database."
  else
    warn "Start the existing Postgres service, then re-run this wizard so it can rotate safely."
    SKIPPED+=("Start Postgres and safely rotate POSTGRES_PASSWORD")
  fi
fi

stage "Transactional email (Resend)"
say "Production registration, verification, and password reset require a verified sender."
open_url "https://resend.com/domains"
step "Add and verify vocora.uz using the DNS records Resend shows."
pause "Press Enter after the domain is verified (or Ctrl-C to resume later)."
open_url "https://resend.com/api-keys"
step "Create a production sending key and copy it once."
while true; do
  ask_secret RESEND_API_KEY "Paste the Resend API key (starts with re_):"
  valid_resend_key "$RESEND_API_KEY" && break
  warn "No valid Resend key was captured. Paste the complete re_... value, then press Enter."
done
while true; do
  ask EMAIL_FROM "Sender (exact format: Vocora <noreply@vocora.uz>):"
  valid_email_from "$EMAIL_FROM" && break
  warn "Use the exact friendly-address format and the verified vocora.uz domain."
done
persist_resend_config "$RESEND_API_KEY" "$EMAIL_FROM"
RESEND_READY=true

stage "Cloudflare production tunnel"
say "The tunnel is an outbound-only connector; do not expose host ports 80/443."
open_url "https://one.dash.cloudflare.com/"
step "Networks → Tunnels → vocora-production → Add a replica → Docker."
step "Copy only the token after --token (not the whole docker command)."
TUNNEL_READY=false
while true; do
  ask_secret CLOUDFLARE_TUNNEL_TOKEN "Paste the tunnel token:"
  if valid_cloudflare_tunnel_token "$CLOUDFLARE_TUNNEL_TOKEN"; then
    persist_cloudflare_tunnel_token "$CLOUDFLARE_TUNNEL_TOKEN"
    TUNNEL_READY=true
    break
  fi
  warn "That is not a valid tunnel token. Copy the eyJ... value after --token."
done
step "Published application route: vocora.uz → http://web:3000"
step "Published application route: api.vocora.uz → http://api:8000"
pause "Press Enter after both routes are saved."

stage "Production OAuth audiences"
open_url "https://console.cloud.google.com/auth/clients"
step "Open the Web application OAuth client used by Vocora and copy its Client ID."
ask GOOGLE_CLIENT_ID "Paste the Google Web Client ID:"
OAUTH_READY=false
if [[ "$GOOGLE_CLIENT_ID" == *.apps.googleusercontent.com ]]; then
  write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
  write_env NEXT_PUBLIC_GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
  OAUTH_READY=true
else
  warn "That does not look like a Google OAuth client ID."
  SKIPPED+=("Set GOOGLE_CLIENT_ID and NEXT_PUBLIC_GOOGLE_CLIENT_ID")
fi
step "Apple Developer → Identifiers → uz.vocora.mobile: verify Sign in with Apple is enabled."
pause "Press Enter after Apple capability is confirmed."

stage "Validate and launch"
say "The release gate prints variable names only; it never prints secret values."
if [[ "$DB_READY" == true && "$RESEND_READY" == true && "$TUNNEL_READY" == true && "$OAUTH_READY" == true ]]; then
  write_env ENVIRONMENT production
  write_env APP_VERSION 1.0.0
  write_env SECRET_KEY "$SECRET_KEY_VALUE"
  write_env FRONTEND_ORIGIN https://vocora.uz
  write_env COOKIE_SECURE true
  write_env API_BIND_HOST 127.0.0.1
  write_env NEXT_PUBLIC_API_URL https://api.vocora.uz
  write_env INTERNAL_API_URL http://api:8000
  write_env PAYMENTS_SANDBOX false
  write_env APPLE_CLIENT_ID uz.vocora.mobile
  write_env POSTGRES_USER words
  write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
  write_env POSTGRES_DB words
  write_env DATABASE_URL "postgresql+asyncpg://words:${POSTGRES_PASSWORD}@postgres:5432/words"
else
  warn "Required values are incomplete, so production mode was not activated."
fi
if [[ "$DB_READY" == true && "$RESEND_READY" == true && "$TUNNEL_READY" == true && "$OAUTH_READY" == true ]] && node scripts/release-preflight.mjs --server-only; then
  if confirm "Preflight passed. Run the production deploy now?"; then
    ./deploy.sh
  else
    note "Deploy skipped. Run ./deploy.sh on the production host when ready."
  fi
else
  warn "Preflight still has blockers. Fix the listed names, then re-run this wizard."
  SKIPPED+=("Pass node scripts/release-preflight.mjs --server-only")
fi

finish
