"""IELTS practice engine — AI-generated content + band scoring.

All content is generated by the AI chain (copyright-safe, unlimited), in real
IELTS formats:
- Reading: an academic passage + comprehension questions.
- Listening: a spoken-style script (read aloud by the browser) + questions.
- Writing: Task 1 / Task 2 prompts, scored against the four IELTS criteria.
- Speaking: handled by the existing Coach (examiner, Parts 1-3, band report).

Reading/Listening tests are graded server-side; the client never sees the
answer key.
"""
import json
from dataclasses import dataclass
from datetime import timedelta
from typing import Any, Dict, List, Optional, Tuple
from uuid import UUID

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import utcnow
from app.models.ielts import IeltsResult, IeltsTest
from app.models.user import User
from app.services.ai_client import AiClient
from app.services.gamification import RewardSummary, apply_skill_xp
from app.services.ielts_scoring import RELIABLE_QUESTION_COUNT, band_from_ratio, half_band as _half_band

XP_READING = 30
XP_WRITING = 40
XP_LISTENING = 30

# Static Writing prompts (Academic), rotated client-side. Original prompts in
# the exact register of real Task 1 / Task 2 questions.
WRITING_TASKS: Dict[str, List[Dict[str, Any]]] = {
    "task1": [
        {
            "title": "Task 1 — Bar chart",
            "prompt": (
                "The chart below shows the number of hours per week that students in three "
                "countries spent studying English online in 2015 and 2023. Summarise the "
                "information by selecting and reporting the main features, and make comparisons "
                "where relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "bar",
                "title": "Weekly hours spent studying English online",
                "y_label": "Hours per student",
                "categories": ["Brazil", "Japan", "Spain"],
                "series": [
                    {"name": "2015", "values": [4.5, 6.0, 5.2]},
                    {"name": "2023", "values": [9.0, 8.5, 11.0]},
                ],
            },
        },
        {
            "title": "Task 1 — Process",
            "prompt": (
                "The diagram below shows how rainwater is collected and purified for drinking in "
                "a small town. Summarise the information by describing the main stages of the "
                "process. Write at least 150 words."
            ),
            "visual": {
                "kind": "process",
                "title": "Rainwater collection and purification system",
                "categories": [
                    "Rain falls on house roofs",
                    "Gutters collect the water",
                    "Underground pipes carry it to a tank",
                    "A filter removes solid material",
                    "Water is treated with disinfectant",
                    "Clean water returns to homes",
                ],
                "series": [],
            },
        },
        {
            "title": "Task 1 — Line graph",
            "prompt": (
                "The graph below shows average house prices in one European city between 2000 and "
                "2020, compared with average salaries over the same period. Summarise the "
                "information by selecting and reporting the main features, and make comparisons "
                "where relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "line",
                "title": "Average house prices and salaries, 2000–2020",
                "y_label": "£ thousands",
                "categories": ["2000", "2005", "2010", "2015", "2020"],
                "series": [
                    {"name": "Average house price", "values": [145, 168, 214, 252, 305]},
                    {"name": "Average annual salary", "values": [24, 27, 31, 35, 39]},
                ],
            },
        },
        {
            "title": "Task 1 — Pie charts",
            "prompt": (
                "The two pie charts below show how a typical household spent its monthly income "
                "in 1990 and in 2020. Summarise the information by selecting and reporting the "
                "main features, and make comparisons where relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "pie-pair",
                "title": "Household spending by category, 1990 and 2020",
                "categories": [],
                "series": [],
                "pies": [
                    {"title": "1990", "slices": [
                        {"name": "Housing", "value": 30},
                        {"name": "Food", "value": 25},
                        {"name": "Transport", "value": 12},
                        {"name": "Leisure", "value": 10},
                        {"name": "Other", "value": 23},
                    ]},
                    {"title": "2020", "slices": [
                        {"name": "Housing", "value": 35},
                        {"name": "Food", "value": 15},
                        {"name": "Transport", "value": 18},
                        {"name": "Leisure", "value": 17},
                        {"name": "Other", "value": 15},
                    ]},
                ],
            },
        },
        {
            "title": "Task 1 — Table",
            "prompt": (
                "The table below gives information about international student numbers at five "
                "universities in 2010, 2015 and 2020. Summarise the information by selecting and "
                "reporting the main features, and make comparisons where relevant. Write at least "
                "150 words."
            ),
            "visual": {
                "kind": "table",
                "title": "International students at five universities",
                "y_label": "Number of students",
                "categories": ["2010", "2015", "2020"],
                "series": [
                    {"name": "Ashford", "values": [3200, 4100, 5600]},
                    {"name": "Barton", "values": [2800, 3500, 3900]},
                    {"name": "Crestview", "values": [4500, 5200, 7100]},
                    {"name": "Denton", "values": [1900, 2900, 4800]},
                    {"name": "Elmbridge", "values": [3600, 3400, 4200]},
                ],
            },
        },
        {
            "title": "Task 1 — Map",
            "prompt": (
                "The two maps below show a small coastal town in 1980 and today. Summarise the "
                "information by describing the main changes that have taken place. Write at "
                "least 150 words."
            ),
            "visual": {
                "kind": "map-pair",
                "title": "Seabrook coastal town: 1980 and today",
                "categories": [],
                "series": [],
                "maps": [
                    {"title": "1980", "features": [
                        {"name": "Sea", "kind": "water", "x": 0, "y": 74, "width": 100, "height": 26},
                        {"name": "Main road", "kind": "road", "x": 0, "y": 43, "width": 100, "height": 10},
                        {"name": "Fishing huts", "kind": "building", "x": 8, "y": 57, "width": 28, "height": 13},
                        {"name": "Houses", "kind": "building", "x": 13, "y": 12, "width": 31, "height": 20},
                        {"name": "Farmland", "kind": "green", "x": 60, "y": 8, "width": 32, "height": 28},
                    ]},
                    {"title": "Today", "features": [
                        {"name": "Sea", "kind": "water", "x": 0, "y": 74, "width": 100, "height": 26},
                        {"name": "Main road", "kind": "road", "x": 0, "y": 43, "width": 100, "height": 10},
                        {"name": "Marina", "kind": "water", "x": 7, "y": 56, "width": 31, "height": 14},
                        {"name": "Apartments", "kind": "building", "x": 12, "y": 9, "width": 34, "height": 25},
                        {"name": "Hotel", "kind": "building", "x": 60, "y": 10, "width": 19, "height": 23},
                        {"name": "Public park", "kind": "green", "x": 81, "y": 8, "width": 15, "height": 29},
                    ]},
                ],
            },
        },
        {
            "title": "Task 1 — Process (manufacturing)",
            "prompt": (
                "The diagram below shows the stages in the production of chocolate, from the "
                "harvesting of cocoa pods to the packaging of finished bars. Summarise the "
                "information by describing the main stages of the process. Write at least 150 "
                "words."
            ),
            "visual": {
                "kind": "process",
                "title": "From cocoa pod to packaged chocolate bar",
                "categories": [
                    "Ripe cocoa pods are harvested",
                    "Pods are split and beans removed",
                    "Beans ferment under banana leaves",
                    "Beans are dried in the sun",
                    "Dried beans are roasted",
                    "Shells are removed and nibs ground",
                    "Cocoa is mixed, refined and moulded",
                    "Finished bars are cooled and packaged",
                ],
                "series": [],
            },
        },
        {
            "title": "Task 1 — Two charts",
            "prompt": (
                "The bar chart below shows the proportion of adults using public transport in "
                "four cities, and the line graph shows petrol prices in the same cities over ten "
                "years. Summarise the information by selecting and reporting the main features, "
                "and make comparisons where relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "bar-line",
                "title": "Public transport use and petrol prices",
                "y_label": "Adults using public transport (%)",
                "categories": ["Alderton", "Bromley", "Carston", "Dunwich"],
                "series": [{"name": "Public transport", "values": [62, 48, 35, 71]}],
                "secondary": {
                    "title": "Average petrol prices, 2014–2023",
                    "y_label": "Price index (2014 = 100)",
                    "categories": ["2014", "2016", "2018", "2020", "2022", "2023"],
                    "series": [
                        {"name": "Alderton", "values": [100, 104, 111, 97, 126, 132]},
                        {"name": "Bromley", "values": [100, 106, 114, 99, 129, 135]},
                        {"name": "Carston", "values": [100, 103, 109, 95, 122, 128]},
                        {"name": "Dunwich", "values": [100, 105, 112, 98, 127, 133]},
                    ],
                },
            },
        },
        {
            "title": "Task 1 — Bakery earnings",
            "prompt": (
                "The line graph shows the annual earnings of three bakeries in London from "
                "2000 to 2010. Summarise the information by selecting and reporting the main "
                "features, and make comparisons where relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "line",
                "title": "Annual earnings of three London bakeries, 2000–2010",
                "y_label": "Yearly income (£ thousands)",
                "categories": ["2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010"],
                "series": [
                    {"name": "Bernie's Buns", "values": [20, 26, 22, 38, 38, 38, 36, 42, 61, 64, 66]},
                    {"name": "Lovely Loaves", "values": [82, 94, 90, 80, 89, 62, 57, 54, 42, 40, 40]},
                    {"name": "Robbie's Bakery", "values": [55, 55, 55, 55, 55, 54, 60, 68, 97, 102, 104]},
                ],
            },
        },
        {
            "title": "Task 1 — Future language study",
            "prompt": (
                "The line graph shows predictions for the number of people who will study "
                "three major world languages between 2020 and 2030. Summarise the information "
                "by selecting and reporting the main features, and make comparisons where "
                "relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "line",
                "title": "Students of three world languages, 2020–2030",
                "y_label": "Estimated students (millions)",
                "categories": ["2020", "2022", "2024", "2026", "2028", "2030"],
                "series": [
                    {"name": "English", "values": [550, 610, 690, 630, 700, 750]},
                    {"name": "Spanish", "values": [220, 280, 290, 350, 400, 490]},
                    {"name": "Mandarin", "values": [100, 180, 280, 350, 500, 570]},
                ],
            },
        },
        {
            "title": "Task 1 — Airport visitors",
            "prompt": (
                "The table below highlights the number of travellers using three major British "
                "airports between 1998 and 2003. Summarise the information by selecting and "
                "reporting the main features, and make comparisons where relevant. Write at "
                "least 150 words."
            ),
            "visual": {
                "kind": "table",
                "title": "Airport visitors, 1998–2003",
                "y_label": "Millions of travellers per year",
                "categories": ["1998", "1999", "2000", "2001", "2002", "2003"],
                "series": [
                    {"name": "Heathrow", "values": [27.2, 36.4, 48.2, 37.1, 33.2, 45.6]},
                    {"name": "Gatwick", "values": [36.5, 41.9, 44.4, 47.3, 51.1, 69.3]},
                    {"name": "Stansted", "values": [17.3, 26.6, 39.9, 43.3, 43.3, 43.3]},
                ],
            },
        },
        {
            "title": "Task 1 — Museum visitors",
            "prompt": (
                "The bar chart below shows the number of visitors to three museums between "
                "2000 and 2005. Summarise the information by selecting and reporting the main "
                "features, and make comparisons where relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "bar",
                "title": "Museum visitor numbers, 2000–2005",
                "y_label": "Annual visitors (millions)",
                "categories": ["2000", "2001", "2002", "2003", "2004", "2005"],
                "series": [
                    {"name": "MET, New York", "values": [12, 6, 6, 7.5, 12, 14.2]},
                    {"name": "Edo-Tokyo", "values": [13.3, 13.3, 9.5, 6.3, 8, 10]},
                    {"name": "National, China", "values": [6.2, 7.4, 9, 11, 11, 15.8]},
                ],
            },
        },
        {
            "title": "Task 1 — Saturday bakery sales",
            "prompt": (
                "The bar chart compares average Saturday sales of eight items at two bakeries "
                "in London in 2010. Summarise the information by selecting and reporting the "
                "main features, and make comparisons where relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "bar",
                "title": "Average Saturday sales at two London bakeries, 2010",
                "y_label": "Average items sold",
                "categories": ["Cakes", "Cookies", "Rolls", "Fresh loaves", "Toasted sandwiches", "Salads", "Crisps", "Doughnuts"],
                "series": [
                    {"name": "Bernie's Buns", "values": [100, 115, 75, 40, 25, 20, 75, 135]},
                    {"name": "Lovely Loaves", "values": [75, 65, 50, 45, 25, 62, 45, 122]},
                ],
            },
        },
        {
            "title": "Task 1 — Film preferences and ticket sales",
            "prompt": (
                "The bar chart compares film genres preferred by men and women, while the pie "
                "chart shows box-office takings by genre in the USA in 2010. Summarise the "
                "information by selecting and reporting the main features, and make comparisons "
                "where relevant. Write at least 150 words."
            ),
            "visual": {
                "kind": "bar-pie",
                "title": "Film preferences and USA box-office takings, 2010",
                "y_label": "Number of respondents",
                "categories": ["Action", "Comedy", "Thriller", "Science fiction", "Western", "Romantic comedy"],
                "series": [
                    {"name": "Men", "values": [40, 20, 15, 10, 10, 5]},
                    {"name": "Women", "values": [25, 20, 10, 5, 10, 30]},
                ],
                "pie": [
                    {"name": "Action", "value": 49},
                    {"name": "Comedy", "value": 24},
                    {"name": "Romantic comedy", "value": 12},
                    {"name": "Thriller", "value": 10},
                    {"name": "Other", "value": 5},
                ],
            },
        },
    ],
    "task2": [
        {
            "title": "Task 2 — Opinion",
            "prompt": (
                "Some people believe that studying a language abroad is the best way to learn "
                "it. To what extent do you agree or disagree? Give reasons for your answer and "
                "include relevant examples. Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Discussion",
            "prompt": (
                "Some people think technology has made our lives more complex, while others "
                "believe it has made life easier. Discuss both views and give your own opinion. "
                "Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Problem & solution",
            "prompt": (
                "In many large cities, traffic congestion is becoming a serious problem. What "
                "are the main causes of this problem, and what measures could governments take "
                "to solve it? Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Advantages & disadvantages",
            "prompt": (
                "More and more employees now work from home rather than travelling to an "
                "office. Do the advantages of this development outweigh the disadvantages? "
                "Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Opinion (education)",
            "prompt": (
                "Some people argue that universities should accept equal numbers of male and "
                "female students in every subject. To what extent do you agree or disagree? "
                "Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Two-part question",
            "prompt": (
                "Many young people today spend a large part of their free time on social media. "
                "Why is social media so attractive to young people? Is this a positive or "
                "negative development? Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Discussion (environment)",
            "prompt": (
                "Some people believe that protecting the environment is the responsibility of "
                "governments, while others think individuals should take responsibility. "
                "Discuss both views and give your own opinion. Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Opinion (money)",
            "prompt": (
                "Some people think that the best way to motivate employees is to pay them more, "
                "while others believe that job satisfaction matters more than salary. Discuss "
                "both views and give your own opinion. Write at least 250 words."
            ),
        },
    ],
}


# Band-conversion tables and half-band rounding now live in
# app.services.ielts_scoring (shared with coach.py and the IELTS Mock).


# --- Reading / Listening generation ------------------------------------------
_COMPREHENSION_SCHEMA = {
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "body": {"type": "string"},
        "questions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "prompt": {"type": "string"},
                    "options": {"type": "array", "items": {"type": "string"}},
                    "answer_index": {"type": "integer"},
                    "explanation": {"type": "string"},
                },
                "required": ["prompt", "options", "answer_index", "explanation"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["title", "body", "questions"],
    "additionalProperties": False,
}

_READING_PROMPT = (
    "Create one IELTS Academic Reading practice item at band {band} difficulty. Write an "
    "informative academic passage of 550-750 words with a title, split into 4-6 paragraphs "
    "(separate them with blank lines), on an interesting non-fiction topic (science, history, "
    "environment, society, technology). Then write {n} questions in authentic IELTS style: "
    "the first half TRUE/FALSE/NOT GIVEN statements (options exactly "
    "['TRUE', 'FALSE', 'NOT GIVEN'] — statement in the prompt, answer_index 0-based; include "
    "at least one NOT GIVEN), the rest multiple-choice with exactly 4 plausible options "
    "testing main ideas, detail, inference and vocabulary. For every question give a "
    "one-sentence explanation that quotes or paraphrases the exact part of the passage "
    "which settles it, so a learner can see why the answer is right."
)

_LISTENING_PROMPT = (
    "Create one IELTS Listening practice item at band {band} difficulty. Write a natural spoken "
    "MONOLOGUE or DIALOGUE script of 200-300 words (e.g. a lecture excerpt, a tour guide, or two "
    "people arranging plans) that will be read aloud to the learner. Then write {n} multiple-"
    "choice questions testing comprehension of specific details and gist. Each question has "
    "exactly 4 options with one correct answer (answer_index is 0-based). For every "
    "question give a one-sentence explanation pointing at the line of the script that "
    "settles it, so a learner can see why the answer is right."
)


async def generate_test(
    db: AsyncSession, user: User, client: AiClient, kind: str, band: float, count: int = 6
) -> Tuple[UUID, Dict[str, Any]]:
    """Generate a Reading/Listening test, persist it with its answer key, and
    return (test_id, client_payload) where client_payload omits the answers."""
    if kind == "reading":
        template, count = _READING_PROMPT, 8  # full-length passage, TFNG + MCQ
    else:
        template = _LISTENING_PROMPT
    system = (
        "You are an experienced IELTS test writer. Produce authentic, original IELTS-style "
        "material. Never reproduce copyrighted texts."
    )
    prompt = template.format(band=band, n=count)
    # Generous limit: a 750-word passage + 8 questions as JSON runs to several
    # thousand tokens, and a truncated response fails JSON parsing (seen live).
    data = await client.json(
        system=system, prompt=prompt, schema=_COMPREHENSION_SCHEMA, max_tokens=8192
    )

    questions = [
        q for q in data.get("questions", [])
        if isinstance(q.get("options"), list) and len(q["options"]) >= 2
    ]
    if not questions:
        raise ValueError("AI produced no questions")

    payload = {"title": str(data.get("title", "")), "body": str(data.get("body", "")), "questions": questions}
    test = IeltsTest(user_id=user.id, kind=kind, payload_json=json.dumps(payload))
    db.add(test)
    await db.flush()

    # Client view: same, but each question strips answer_index and explanation —
    # both are revealed only after grading.
    client_payload = {
        "title": payload["title"],
        "body": payload["body"],
        "questions": [
            {"prompt": q["prompt"], "options": q["options"]} for q in questions
        ],
    }
    return test.id, client_payload


async def start_bank_test(
    db: AsyncSession, user: User, kind: str, item_id: str
) -> Tuple[UUID, Dict[str, Any]]:
    """Start a built-in bank passage: persist it as a normal IeltsTest (with its
    answer key and bank id) so grading/XP/history reuse the same pipeline. No AI
    call, no quota."""
    from app.services.ielts_bank import bank_item

    item = bank_item(kind, item_id)
    if item is None:
        raise LookupError("bank item not found")
    payload = {
        "title": item["title"],
        "body": item["body"],
        "questions": item["questions"],
        "bank_id": item["id"],
    }
    test = IeltsTest(user_id=user.id, kind=kind, payload_json=json.dumps(payload))
    db.add(test)
    await db.flush()
    client_payload = {
        "title": payload["title"],
        "body": payload["body"],
        "questions": [
            {"prompt": q["prompt"], "options": q["options"]} for q in item["questions"]
        ],
    }
    return test.id, client_payload


async def completed_bank_ids(db: AsyncSession, user: User, kind: str) -> List[str]:
    """Bank items this user has already completed (marked ✓ in the list)."""
    skill = "reading" if kind == "reading" else "listening"
    rows = await db.scalars(
        select(IeltsResult.detail).where(
            IeltsResult.user_id == user.id, IeltsResult.skill == skill
        )
    )
    done: List[str] = []
    for detail in rows:
        if not detail:
            continue
        try:
            bank_id = json.loads(detail).get("bank_id")
        except ValueError:
            continue
        if bank_id:
            done.append(bank_id)
    return done


@dataclass
class GradeResult:
    correct: int
    total: int
    band: float
    # True when the test is too short for a single band to mean much; the client
    # shows a range and a caveat rather than a precise figure.
    approximate: bool
    # Why each answer is right, revealed with the answers after grading. The
    # results screen used to show only which option was correct.
    explanations: List[str]
    answers: List[int]  # correct answer_index per question, revealed after submit
    reward: RewardSummary


async def grade_test(
    db: AsyncSession, user: User, test_id: UUID, submitted: List[int],
    mock_session_id: Optional[UUID] = None,
) -> GradeResult:
    """Grade a submitted Reading/Listening test against the stored answer key."""
    test = await db.scalar(
        select(IeltsTest).where(IeltsTest.id == test_id, IeltsTest.user_id == user.id)
    )
    if test is None:
        raise LookupError("test not found")
    payload = json.loads(test.payload_json)
    questions = payload["questions"]
    answers = [int(q["answer_index"]) for q in questions]
    explanations = [str(q.get("explanation", "")).strip() for q in questions]

    correct = sum(
        1 for i, ans in enumerate(answers) if i < len(submitted) and submitted[i] == ans
    )
    total = len(answers)
    skill = "reading" if test.kind == "reading" else "listening"
    band = band_from_ratio(correct / total, skill) if total else 0.0
    approximate = total < RELIABLE_QUESTION_COUNT
    xp = XP_READING if test.kind == "reading" else XP_LISTENING
    reward = await apply_skill_xp(db, user, xp)
    detail: Dict[str, Any] = {"correct": correct, "total": total}
    if payload.get("bank_id"):
        detail["bank_id"] = payload["bank_id"]  # marks the bank item as done
    db.add(
        IeltsResult(
            user_id=user.id, skill=skill, band=band, detail=json.dumps(detail),
            mock_session_id=mock_session_id,
        )
    )
    # One-shot content: drop the stored test after grading.
    await db.delete(test)
    return GradeResult(
        correct=correct,
        total=total,
        band=band,
        approximate=approximate,
        answers=answers,
        explanations=explanations,
        reward=reward,
    )


# --- Writing scoring ---------------------------------------------------------
# Condensed from the official IELTS Writing Band Descriptors (ielts.org, updated
# May 2023) — Task 1 here is the Academic module only (this app's Task 1 bank is
# all charts/graphs/tables/maps/processes, never General Training letters), so
# the General Training bullet variants are dropped. Kept verbatim in substance,
# trimmed of pure formatting scaffolding, so the model grades against the real
# public criteria instead of a paraphrase of them.
_TASK1_BAND_DESCRIPTORS = """
Band 9 — TA: all requirements fully and appropriately satisfied; extremely rare lapses. CC: message followed effortlessly; cohesion very rarely attracts attention; paragraphing skilfully managed. LR: full flexibility and precise use; wide vocabulary used accurately and naturally; spelling/word-formation errors extremely rare. GRA: wide range of structures with full flexibility and control; punctuation and grammar appropriate throughout; minor errors extremely rare.
Band 8 — TA: covers all requirements appropriately, relevantly, sufficiently; key features skilfully selected and clearly presented/highlighted/illustrated; occasional omissions or lapses. CC: followed with ease; logically sequenced; cohesion well managed; occasional lapses; paragraphing sufficient and appropriate. LR: wide resource, fluent and flexible, precise meanings; skilful uncommon/idiomatic use despite occasional inaccuracies; occasional spelling/word-formation errors, minimal impact. GRA: wide range, flexible and accurate; majority of sentences error-free; punctuation well managed; occasional non-systematic errors, minimal impact.
Band 7 — TA: covers the requirements; relevant and accurate, a few omissions/lapses; appropriate format; key features covered and clearly highlighted but could be more fully/appropriately illustrated; clear overview, data appropriately categorised, main trends/differences identified. CC: logically organised, clear progression, a few minor lapses; cohesive devices used flexibly with some inaccuracies or over/under-use. LR: sufficient for some flexibility/precision; some ability with less common/idiomatic items; awareness of style/collocation, though inappropriacies occur; only a few spelling/word-formation errors, don't detract from clarity. GRA: variety of complex structures with some flexibility/accuracy; grammar/punctuation generally well controlled, frequent error-free sentences; a few persisting errors don't impede communication.
Band 6 — TA: focuses on the requirements, appropriate format; key features covered and adequately highlighted; a relevant overview attempted; information appropriately selected/supported with data; some irrelevant, inaccurate, or excessive/missing detail may occur. CC: generally coherent, clear overall progression; cohesive devices used to good effect but may be faulty or mechanical (misuse/overuse/omission); reference/substitution may lack flexibility, causing some repetition or error. LR: generally adequate and appropriate; meaning generally clear despite restricted range or imprecision; risk-takers show wider range but more inaccuracy; some spelling/word-formation errors, don't impede communication. GRA: mix of simple and complex forms, limited flexibility; complex structures less accurate than simple ones; errors occur but rarely impede communication.
Band 5 — TA: generally addresses the requirements, format may be inappropriate in places; key features not adequately covered, recounting mainly mechanical, may lack data to support the description; tendency to focus on details without the bigger picture; irrelevant/inaccurate material detracts; limited detail extending/illustrating points. CC: organisation evident but not wholly logical, lacks overall progression though an underlying coherence remains; ideas can be followed but aren't fluently linked; limited or overused cohesive devices with inaccuracy; repetitive due to inadequate reference/substitution. LR: limited but minimally adequate; simple vocabulary used accurately but little variation; frequent lapses in word-choice appropriacy, simplifications/repetitions; noticeable spelling/word-formation errors may cause difficulty for the reader. GRA: limited, repetitive range; complex sentences attempted but tend to be faulty, greatest accuracy on simple sentences; frequent grammatical errors cause some difficulty; punctuation may be faulty.
Band 4 — TA: an attempt to address the task; few key features selected; format may be inappropriate; features presented may be irrelevant, repetitive, inaccurate, or inappropriate. CC: evident but not arranged coherently, no clear progression; relationships between ideas unclear or inadequately marked; some basic cohesive devices, possibly inaccurate/repetitive; inaccurate or lacking substitution/referencing. LR: limited, inadequate for or unrelated to the task; basic, repetitive vocabulary; inappropriate use of memorised/formulaic lexical chunks; word-choice, word-formation, or spelling errors may impede meaning. GRA: very limited range; subordinate clauses rare, simple sentences predominate; some structures accurate but grammatical errors frequent and may impede meaning; punctuation often faulty or inadequate.
Bands 3-2 — Task not adequately addressed or misunderstood; largely irrelevant or repetitive content; little/no logical organisation; resource inadequate (often significantly underlength) with possible over-dependence on input material; word-choice/spelling control very limited, errors predominate and may severely impede meaning; little evidence of sentence-form control.
Band 1 — Responses of 20 words or fewer are automatically Band 1; content wholly unrelated to the task; no rateable language evident beyond isolated words.
Band 0 — Only for no attempt, a response entirely in another language, or proven fully memorised content.
""".strip()

_TASK2_BAND_DESCRIPTORS = """
Band 9 — TR: prompt appropriately addressed and explored in depth; clear, fully developed position directly answering the question(s); ideas relevant, fully extended, well supported; lapses extremely rare. CC: message followed effortlessly; cohesion very rarely attracts attention; paragraphing skilfully managed. LR: full flexibility and precise use widely evident; wide vocabulary used accurately and naturally; spelling/word-formation errors extremely rare. GRA: wide range of structures with full flexibility and control; punctuation and grammar appropriate throughout; minor errors extremely rare.
Band 8 — TR: prompt appropriately and sufficiently addressed; clear, well-developed position; ideas relevant, well extended and supported; occasional omissions or lapses. CC: followed with ease; logically sequenced; cohesion well managed; occasional lapses; paragraphing sufficient and appropriate. LR: wide resource, fluent and flexible, precise meanings; skilful uncommon/idiomatic use despite occasional inaccuracies; occasional spelling/word-formation errors, minimal impact. GRA: wide range, flexible and accurate; majority of sentences error-free; punctuation well managed; occasional non-systematic errors, minimal impact.
Band 7 — TR: main parts of the prompt appropriately addressed; clear, developed position; main ideas extended and supported but may over-generalise or lack focus/precision in supporting material. CC: logically organised, clear progression, a few minor lapses; cohesive devices used flexibly with some inaccuracies or over/under-use; paragraphing generally effective, logical sequencing within paragraphs. LR: sufficient for some flexibility/precision; some ability with less common/idiomatic items; awareness of style/collocation, though inappropriacies occur; only a few spelling/word-formation errors, don't detract from clarity. GRA: variety of complex structures with some flexibility/accuracy; grammar/punctuation generally well controlled, frequent error-free sentences; a few persisting errors don't impede communication.
Band 6 — TR: main parts addressed, though some more fully than others, appropriate format; position directly relevant but conclusions may be unclear, unjustified, or repetitive; main ideas relevant but some insufficiently developed or unclear, supporting arguments/evidence sometimes less relevant or inadequate. CC: generally coherent, clear overall progression; cohesive devices to good effect but may be faulty or mechanical; reference/substitution may lack flexibility; paragraphing not always logical or the central topic not always clear. LR: generally adequate and appropriate; meaning generally clear despite restricted range or imprecision; risk-takers show wider range but more inaccuracy; some spelling/word-formation errors, don't impede communication. GRA: mix of simple and complex forms, limited flexibility; complex structures less accurate than simple ones; errors occur but rarely impede communication.
Band 5 — TR: main parts incompletely addressed, format may be inappropriate in places; a position is expressed but development not always clear; main ideas limited and insufficiently developed, possible irrelevant detail or repetition. CC: organisation evident but not wholly logical, lacks overall progression though an underlying coherence remains; ideas can be followed but aren't fluently linked; limited or overused cohesive devices with inaccuracy; repetitive; paragraphing may be inadequate or missing. LR: limited but minimally adequate; simple vocabulary used accurately but little variation; frequent lapses in word-choice appropriacy, simplifications/repetitions; noticeable spelling/word-formation errors may cause difficulty for the reader. GRA: limited, repetitive range; complex sentences attempted but tend to be faulty, greatest accuracy on simple sentences; frequent grammatical errors cause some difficulty; punctuation may be faulty.
Band 4 — TR: prompt tackled minimally, or the answer is tangential, possibly from misunderstanding it; format may be inappropriate; a position is discernible but requires careful reading to find; main ideas difficult to identify and may lack relevance, clarity, or support; large parts may be repetitive. CC: evident but not arranged coherently, no clear progression; relationships between ideas unclear or inadequately marked; some basic cohesive devices, possibly inaccurate/repetitive; inaccurate or lacking substitution/referencing; may lack paragraphing or a clear main topic. LR: limited, inadequate for or unrelated to the task; basic, repetitive vocabulary; inappropriate use of memorised/formulaic lexical chunks; word-choice, word-formation, or spelling errors may impede meaning. GRA: very limited range; subordinate clauses rare, simple sentences predominate; some structures accurate but grammatical errors frequent and may impede meaning; punctuation often faulty or inadequate.
Bands 3-2 — No part of the prompt adequately addressed or it's misunderstood; no relevant position identifiable; few, possibly irrelevant or underdeveloped ideas; little/no logical organisation; resource inadequate (often significantly underlength) with possible over-dependence on input material; word-choice/spelling control very limited, errors predominate and may severely impede meaning; little evidence of sentence-form control.
Band 1 — Responses of 20 words or fewer are automatically Band 1; content wholly unrelated to the prompt; no rateable language evident beyond isolated words.
Band 0 — Only for no attempt, a response entirely in another language, or proven fully memorised content.
""".strip()

_CRITERION = {
    "type": "object",
    "properties": {"band": {"type": "number"}, "comment": {"type": "string"}},
    "required": ["band", "comment"],
    "additionalProperties": False,
}

_WRITING_SCHEMA = {
    "type": "object",
    "properties": {
        "band_overall": {"type": "number"},
        "task": _CRITERION,
        "coherence": _CRITERION,
        "lexical": _CRITERION,
        "grammar": _CRITERION,
        "errors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "quote": {"type": "string"},
                    "fix": {"type": "string"},
                    "note": {"type": "string"},
                    "type": {
                        "type": "string",
                        "enum": ["grammar", "vocabulary", "spelling", "punctuation", "style"],
                    },
                },
                "required": ["quote", "fix", "note", "type"],
                "additionalProperties": False,
            },
        },
        "strengths": {"type": "array", "items": {"type": "string"}},
        "feedback": {"type": "string"},
        "improved": {"type": "string"},
    },
    "required": [
        "band_overall", "task", "coherence", "lexical", "grammar",
        "errors", "strengths", "feedback", "improved",
    ],
    "additionalProperties": False,
}

_FEEDBACK_LANG = {"uz": "Uzbek (Latin script)", "ru": "Russian", "en": "English"}


@dataclass
class WritingError:
    quote: str
    fix: str
    note: str
    type: str


@dataclass
class Criterion:
    band: float
    comment: str


@dataclass
class WritingScore:
    band_overall: float
    task: Criterion
    coherence: Criterion
    lexical: Criterion
    grammar: Criterion
    errors: List[WritingError]
    strengths: List[str]
    feedback: str
    improved: str
    reward: RewardSummary


def _criterion(data: Any) -> Criterion:
    data = data if isinstance(data, dict) else {}
    return Criterion(band=_half_band(data.get("band")), comment=str(data.get("comment", "")).strip())


FREE_WRITING_CHECKS_PER_WEEK = 3


async def has_free_writing_quota(db: AsyncSession, user_id: UUID) -> bool:
    """Free tier: 3 writing checks per rolling 7 days — tighter than the
    general daily AI-action quota, and specific to this one feature (Basic/
    Speaking Pro get 5/day instead, checked separately, not through this).
    Counted from IeltsResult rows rather than a separate counter, so there's
    nothing to reset or drift out of sync with what actually happened."""
    week_ago = utcnow() - timedelta(days=7)
    count = await db.scalar(
        select(func.count(IeltsResult.id)).where(
            IeltsResult.user_id == user_id,
            IeltsResult.skill == "writing",
            IeltsResult.created_at >= week_ago,
        )
    )
    return (count or 0) < FREE_WRITING_CHECKS_PER_WEEK


async def score_writing(
    db: AsyncSession, user: User, client: AiClient, task_type: str, prompt: str,
    essay: str, lang: str = "en", mock_session_id: Optional[UUID] = None,
) -> WritingScore:
    """Professional Writing review: strict band scores per criterion, a full
    error list with corrections, strengths, and a band-8 model rewrite."""
    criteria = "Task Achievement" if task_type == "task1" else "Task Response"
    descriptors = _TASK1_BAND_DESCRIPTORS if task_type == "task1" else _TASK2_BAND_DESCRIPTORS
    feedback_lang = _FEEDBACK_LANG.get(lang, _FEEDBACK_LANG["en"])
    system = (
        "You are a certified IELTS Writing examiner and an experienced writing tutor. "
        "Score strictly and fairly on the 0-9 band scale in 0.5 steps against the four "
        "official IELTS criteria: {crit}, Coherence & Cohesion, Lexical Resource, and "
        "Grammatical Range & Accuracy — using the real public band descriptors below, "
        "not your own impression of the scale. A response must fully fit a band's "
        "positive features to be placed there; do not inflate scores.\n\n"
        "{descriptors}\n\n"
        "band_overall is the average of the four criteria, rounded to the nearest 0.5. "
        "Each criterion gets a 1-2 sentence 'comment'. 'errors' lists every significant "
        "mistake (up to 12, most damaging first): 'quote' copies the exact fragment from "
        "the response, 'fix' is the corrected fragment, 'note' explains the rule in one "
        "short sentence. 'strengths' names 2-3 concrete things the candidate did well. "
        "'feedback' is a 2-4 sentence overall summary with the single most important next "
        "step. 'improved' rewrites the WHOLE response as a band-8 model answer that keeps "
        "the candidate's ideas and structure. Write all comments, notes, strengths and "
        "feedback in {lang}; quotes, fixes and the improved response stay in English."
    ).format(crit=criteria, descriptors=descriptors, lang=feedback_lang)
    user_prompt = (
        "IELTS Writing {tt}.\n\nPROMPT:\n{p}\n\nCANDIDATE RESPONSE:\n{e}"
    ).format(tt=task_type.upper(), p=prompt, e=essay)
    data = await client.json(
        system=system, prompt=user_prompt, schema=_WRITING_SCHEMA, max_tokens=8192
    )

    reward = await apply_skill_xp(db, user, XP_WRITING)
    band = _half_band(data.get("band_overall"))
    db.add(
        IeltsResult(
            user_id=user.id, skill="writing", band=band, detail=data.get("feedback"),
            mock_session_id=mock_session_id,
        )
    )
    errors = [
        WritingError(
            quote=str(e.get("quote", "")).strip(),
            fix=str(e.get("fix", "")).strip(),
            note=str(e.get("note", "")).strip(),
            type=str(e.get("type", "grammar")),
        )
        for e in data.get("errors", [])
        if isinstance(e, dict) and str(e.get("quote", "")).strip()
    ][:12]
    return WritingScore(
        band_overall=band,
        task=_criterion(data.get("task")),
        coherence=_criterion(data.get("coherence")),
        lexical=_criterion(data.get("lexical")),
        grammar=_criterion(data.get("grammar")),
        errors=errors,
        strengths=[str(s).strip() for s in data.get("strengths", []) if str(s).strip()][:4],
        feedback=str(data.get("feedback", "")).strip(),
        improved=str(data.get("improved", "")).strip(),
        reward=reward,
    )


# --- Overview ----------------------------------------------------------------
async def best_bands(db: AsyncSession, user: User) -> Dict[str, float]:
    """Best band per skill so the hub can show progress."""
    rows = await db.scalars(select(IeltsResult).where(IeltsResult.user_id == user.id))
    best: Dict[str, float] = {}
    for r in rows:
        if r.band > best.get(r.skill, 0.0):
            best[r.skill] = r.band
    return best


async def recent_results(db: AsyncSession, user: User, limit: int = 10) -> List[IeltsResult]:
    """Latest scored attempts across all skills, newest first."""
    rows = await db.scalars(
        select(IeltsResult)
        .where(IeltsResult.user_id == user.id)
        .order_by(IeltsResult.created_at.desc())
        .limit(limit)
    )
    return list(rows)
