"""IELTS practice engine — AI-generated content + band scoring.

All content is generated by the AI chain (copyright-safe, unlimited), in real
IELTS formats:
- Reading: an academic passage + comprehension questions.
- Listening: a spoken-style script (read aloud by the browser) + questions.
- Writing: Task 1 / Task 2 prompts, scored against the four IELTS criteria.
- Speaking: handled by the existing Coach (examiner, Parts 1-3, band report).

Reading/Listening tests are graded server-side; the client never sees the
answer key.
"""
import json
from dataclasses import dataclass
from typing import Any, Dict, List, Tuple
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.ielts import IeltsResult, IeltsTest
from app.models.user import User
from app.services.ai_client import AiClient
from app.services.gamification import RewardSummary, apply_skill_xp

XP_READING = 30
XP_WRITING = 40
XP_LISTENING = 30

# Static Writing prompts (Academic), rotated client-side. Original prompts in
# the exact register of real Task 1 / Task 2 questions.
WRITING_TASKS: Dict[str, List[Dict[str, str]]] = {
    "task1": [
        {
            "title": "Task 1 — Bar chart",
            "prompt": (
                "The chart below shows the number of hours per week that students in three "
                "countries spent studying English online in 2015 and 2023. Summarise the "
                "information by selecting and reporting the main features, and make comparisons "
                "where relevant. Write at least 150 words."
            ),
        },
        {
            "title": "Task 1 — Process",
            "prompt": (
                "The diagram below shows how rainwater is collected and purified for drinking in "
                "a small town. Summarise the information by describing the main stages of the "
                "process. Write at least 150 words."
            ),
        },
        {
            "title": "Task 1 — Line graph",
            "prompt": (
                "The graph below shows average house prices in one European city between 2000 and "
                "2020, compared with average salaries over the same period. Summarise the "
                "information by selecting and reporting the main features, and make comparisons "
                "where relevant. Write at least 150 words."
            ),
        },
        {
            "title": "Task 1 — Pie charts",
            "prompt": (
                "The two pie charts below show how a typical household spent its monthly income "
                "in 1990 and in 2020. Summarise the information by selecting and reporting the "
                "main features, and make comparisons where relevant. Write at least 150 words."
            ),
        },
        {
            "title": "Task 1 — Table",
            "prompt": (
                "The table below gives information about international student numbers at five "
                "universities in 2010, 2015 and 2020. Summarise the information by selecting and "
                "reporting the main features, and make comparisons where relevant. Write at least "
                "150 words."
            ),
        },
        {
            "title": "Task 1 — Map",
            "prompt": (
                "The two maps below show a small coastal town in 1980 and today. Summarise the "
                "information by describing the main changes that have taken place. Write at "
                "least 150 words."
            ),
        },
        {
            "title": "Task 1 — Process (manufacturing)",
            "prompt": (
                "The diagram below shows the stages in the production of chocolate, from the "
                "harvesting of cocoa pods to the packaging of finished bars. Summarise the "
                "information by describing the main stages of the process. Write at least 150 "
                "words."
            ),
        },
        {
            "title": "Task 1 — Two charts",
            "prompt": (
                "The bar chart below shows the proportion of adults using public transport in "
                "four cities, and the line graph shows petrol prices in the same cities over ten "
                "years. Summarise the information by selecting and reporting the main features, "
                "and make comparisons where relevant. Write at least 150 words."
            ),
        },
    ],
    "task2": [
        {
            "title": "Task 2 — Opinion",
            "prompt": (
                "Some people believe that studying a language abroad is the best way to learn "
                "it. To what extent do you agree or disagree? Give reasons for your answer and "
                "include relevant examples. Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Discussion",
            "prompt": (
                "Some people think technology has made our lives more complex, while others "
                "believe it has made life easier. Discuss both views and give your own opinion. "
                "Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Problem & solution",
            "prompt": (
                "In many large cities, traffic congestion is becoming a serious problem. What "
                "are the main causes of this problem, and what measures could governments take "
                "to solve it? Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Advantages & disadvantages",
            "prompt": (
                "More and more employees now work from home rather than travelling to an "
                "office. Do the advantages of this development outweigh the disadvantages? "
                "Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Opinion (education)",
            "prompt": (
                "Some people argue that universities should accept equal numbers of male and "
                "female students in every subject. To what extent do you agree or disagree? "
                "Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Two-part question",
            "prompt": (
                "Many young people today spend a large part of their free time on social media. "
                "Why is social media so attractive to young people? Is this a positive or "
                "negative development? Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Discussion (environment)",
            "prompt": (
                "Some people believe that protecting the environment is the responsibility of "
                "governments, while others think individuals should take responsibility. "
                "Discuss both views and give your own opinion. Write at least 250 words."
            ),
        },
        {
            "title": "Task 2 — Opinion (money)",
            "prompt": (
                "Some people think that the best way to motivate employees is to pay them more, "
                "while others believe that job satisfaction matters more than salary. Discuss "
                "both views and give your own opinion. Write at least 250 words."
            ),
        },
    ],
}


def band_from_ratio(ratio: float) -> float:
    """Map a correct-answer ratio to an approximate IELTS band (0.5 steps)."""
    table = [
        (0.95, 9.0), (0.9, 8.5), (0.83, 8.0), (0.75, 7.5), (0.67, 7.0),
        (0.58, 6.5), (0.5, 6.0), (0.42, 5.5), (0.33, 5.0), (0.25, 4.5),
        (0.17, 4.0), (0.08, 3.5),
    ]
    for threshold, band in table:
        if ratio >= threshold:
            return band
    return 3.0


def _half_band(value: Any) -> float:
    try:
        band = float(value)
    except (TypeError, ValueError):
        band = 5.0
    return max(0.0, min(9.0, round(band * 2) / 2))


# --- Reading / Listening generation ------------------------------------------
_COMPREHENSION_SCHEMA = {
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "body": {"type": "string"},
        "questions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "prompt": {"type": "string"},
                    "options": {"type": "array", "items": {"type": "string"}},
                    "answer_index": {"type": "integer"},
                },
                "required": ["prompt", "options", "answer_index"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["title", "body", "questions"],
    "additionalProperties": False,
}

_READING_PROMPT = (
    "Create one IELTS Academic Reading practice item at band {band} difficulty. Write an "
    "informative academic passage of 550-750 words with a title, split into 4-6 paragraphs "
    "(separate them with blank lines), on an interesting non-fiction topic (science, history, "
    "environment, society, technology). Then write {n} questions in authentic IELTS style: "
    "the first half TRUE/FALSE/NOT GIVEN statements (options exactly "
    "['TRUE', 'FALSE', 'NOT GIVEN'] — statement in the prompt, answer_index 0-based; include "
    "at least one NOT GIVEN), the rest multiple-choice with exactly 4 plausible options "
    "testing main ideas, detail, inference and vocabulary."
)

_LISTENING_PROMPT = (
    "Create one IELTS Listening practice item at band {band} difficulty. Write a natural spoken "
    "MONOLOGUE or DIALOGUE script of 200-300 words (e.g. a lecture excerpt, a tour guide, or two "
    "people arranging plans) that will be read aloud to the learner. Then write {n} multiple-"
    "choice questions testing comprehension of specific details and gist. Each question has "
    "exactly 4 options with one correct answer (answer_index is 0-based)."
)


async def generate_test(
    db: AsyncSession, user: User, client: AiClient, kind: str, band: float, count: int = 6
) -> Tuple[UUID, Dict[str, Any]]:
    """Generate a Reading/Listening test, persist it with its answer key, and
    return (test_id, client_payload) where client_payload omits the answers."""
    if kind == "reading":
        template, count = _READING_PROMPT, 8  # full-length passage, TFNG + MCQ
    else:
        template = _LISTENING_PROMPT
    system = (
        "You are an experienced IELTS test writer. Produce authentic, original IELTS-style "
        "material. Never reproduce copyrighted texts."
    )
    prompt = template.format(band=band, n=count)
    # Generous limit: a 750-word passage + 8 questions as JSON runs to several
    # thousand tokens, and a truncated response fails JSON parsing (seen live).
    data = await client.json(
        system=system, prompt=prompt, schema=_COMPREHENSION_SCHEMA, max_tokens=8192
    )

    questions = [
        q for q in data.get("questions", [])
        if isinstance(q.get("options"), list) and len(q["options"]) >= 2
    ]
    if not questions:
        raise ValueError("AI produced no questions")

    payload = {"title": str(data.get("title", "")), "body": str(data.get("body", "")), "questions": questions}
    test = IeltsTest(user_id=user.id, kind=kind, payload_json=json.dumps(payload))
    db.add(test)
    await db.flush()

    # Client view: same, but each question strips answer_index.
    client_payload = {
        "title": payload["title"],
        "body": payload["body"],
        "questions": [
            {"prompt": q["prompt"], "options": q["options"]} for q in questions
        ],
    }
    return test.id, client_payload


async def start_bank_test(
    db: AsyncSession, user: User, kind: str, item_id: str
) -> Tuple[UUID, Dict[str, Any]]:
    """Start a built-in bank passage: persist it as a normal IeltsTest (with its
    answer key and bank id) so grading/XP/history reuse the same pipeline. No AI
    call, no quota."""
    from app.services.ielts_bank import bank_item

    item = bank_item(kind, item_id)
    if item is None:
        raise LookupError("bank item not found")
    payload = {
        "title": item["title"],
        "body": item["body"],
        "questions": item["questions"],
        "bank_id": item["id"],
    }
    test = IeltsTest(user_id=user.id, kind=kind, payload_json=json.dumps(payload))
    db.add(test)
    await db.flush()
    client_payload = {
        "title": payload["title"],
        "body": payload["body"],
        "questions": [
            {"prompt": q["prompt"], "options": q["options"]} for q in item["questions"]
        ],
    }
    return test.id, client_payload


async def completed_bank_ids(db: AsyncSession, user: User, kind: str) -> List[str]:
    """Bank items this user has already completed (marked ✓ in the list)."""
    skill = "reading" if kind == "reading" else "listening"
    rows = await db.scalars(
        select(IeltsResult.detail).where(
            IeltsResult.user_id == user.id, IeltsResult.skill == skill
        )
    )
    done: List[str] = []
    for detail in rows:
        if not detail:
            continue
        try:
            bank_id = json.loads(detail).get("bank_id")
        except ValueError:
            continue
        if bank_id:
            done.append(bank_id)
    return done


@dataclass
class GradeResult:
    correct: int
    total: int
    band: float
    answers: List[int]  # correct answer_index per question, revealed after submit
    reward: RewardSummary


async def grade_test(
    db: AsyncSession, user: User, test_id: UUID, submitted: List[int]
) -> GradeResult:
    """Grade a submitted Reading/Listening test against the stored answer key."""
    test = await db.scalar(
        select(IeltsTest).where(IeltsTest.id == test_id, IeltsTest.user_id == user.id)
    )
    if test is None:
        raise LookupError("test not found")
    payload = json.loads(test.payload_json)
    questions = payload["questions"]
    answers = [int(q["answer_index"]) for q in questions]

    correct = sum(
        1 for i, ans in enumerate(answers) if i < len(submitted) and submitted[i] == ans
    )
    total = len(answers)
    band = band_from_ratio(correct / total) if total else 0.0

    skill = "reading" if test.kind == "reading" else "listening"
    xp = XP_READING if test.kind == "reading" else XP_LISTENING
    reward = await apply_skill_xp(db, user, xp)
    detail: Dict[str, Any] = {"correct": correct, "total": total}
    if payload.get("bank_id"):
        detail["bank_id"] = payload["bank_id"]  # marks the bank item as done
    db.add(
        IeltsResult(user_id=user.id, skill=skill, band=band, detail=json.dumps(detail))
    )
    # One-shot content: drop the stored test after grading.
    await db.delete(test)
    return GradeResult(correct=correct, total=total, band=band, answers=answers, reward=reward)


# --- Writing scoring ---------------------------------------------------------
_WRITING_SCHEMA = {
    "type": "object",
    "properties": {
        "band_overall": {"type": "number"},
        "task": {"type": "number"},
        "coherence": {"type": "number"},
        "lexical": {"type": "number"},
        "grammar": {"type": "number"},
        "feedback": {"type": "string"},
        "improved": {"type": "string"},
    },
    "required": ["band_overall", "task", "coherence", "lexical", "grammar", "feedback", "improved"],
    "additionalProperties": False,
}


@dataclass
class WritingScore:
    band_overall: float
    task: float
    coherence: float
    lexical: float
    grammar: float
    feedback: str
    improved: str
    reward: RewardSummary


async def score_writing(
    db: AsyncSession, user: User, client: AiClient, task_type: str, prompt: str, essay: str
) -> WritingScore:
    """Score an IELTS Writing response across the four official criteria."""
    criteria = (
        "Task Achievement" if task_type == "task1" else "Task Response"
    )
    system = (
        "You are a certified IELTS Writing examiner. Score strictly and fairly on the 0-9 band "
        "scale in 0.5 steps against the four criteria: {crit}, Coherence & Cohesion, Lexical "
        "Resource, and Grammatical Range & Accuracy. band_overall is their average rounded to "
        "the nearest 0.5. 'feedback' is 2-4 concrete sentences; 'improved' rewrites ONE weak "
        "sentence from the response as a band-8 example. Do not inflate scores."
    ).format(crit=criteria)
    user_prompt = (
        "IELTS Writing {tt}.\n\nPROMPT:\n{p}\n\nCANDIDATE RESPONSE:\n{e}"
    ).format(tt=task_type.upper(), p=prompt, e=essay)
    data = await client.json(
        system=system, prompt=user_prompt, schema=_WRITING_SCHEMA, max_tokens=900
    )

    reward = await apply_skill_xp(db, user, XP_WRITING)
    band = _half_band(data.get("band_overall"))
    db.add(IeltsResult(user_id=user.id, skill="writing", band=band, detail=data.get("feedback")))
    return WritingScore(
        band_overall=band,
        task=_half_band(data.get("task")),
        coherence=_half_band(data.get("coherence")),
        lexical=_half_band(data.get("lexical")),
        grammar=_half_band(data.get("grammar")),
        feedback=str(data.get("feedback", "")).strip(),
        improved=str(data.get("improved", "")).strip(),
        reward=reward,
    )


# --- Overview ----------------------------------------------------------------
async def best_bands(db: AsyncSession, user: User) -> Dict[str, float]:
    """Best band per skill so the hub can show progress."""
    rows = await db.scalars(select(IeltsResult).where(IeltsResult.user_id == user.id))
    best: Dict[str, float] = {}
    for r in rows:
        if r.band > best.get(r.skill, 0.0):
            best[r.skill] = r.band
    return best
