"""multiplayer: sessions, questions, players, answers

Revision ID: 07f01708e7fc
Revises: b4d8f1a6c3e9
Create Date: 2026-08-22 00:25:06.538448

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07f01708e7fc'
down_revision: Union[str, None] = 'b4d8f1a6c3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_code', sa.String(length=4), nullable=False),
    sa.Column('host_user_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mp_sessions_host_created', 'mp_sessions', ['host_user_id', 'created_at'], unique=False)
    op.create_index('ix_mp_sessions_room_code', 'mp_sessions', ['room_code'], unique=False)
    op.create_table('mp_players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('display_name_snapshot', sa.String(length=80), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('avg_response_ms', sa.Float(), nullable=True),
    sa.Column('fastest_response_ms', sa.Integer(), nullable=True),
    sa.Column('left_early', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['mp_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mp_players_session', 'mp_players', ['session_id'], unique=False)
    op.create_table('mp_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['mp_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_index', name='uq_mp_question_session_index')
    )
    op.create_table('mp_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('option_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('streak_at_answer', sa.Integer(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['mp_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['mp_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_mp_answer_question_user')
    )
    op.create_index('ix_mp_answers_session', 'mp_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mp_answers_session', table_name='mp_answers')
    op.drop_table('mp_answers')
    op.drop_table('mp_questions')
    op.drop_index('ix_mp_players_session', table_name='mp_players')
    op.drop_table('mp_players')
    op.drop_index('ix_mp_sessions_room_code', table_name='mp_sessions')
    op.drop_index('ix_mp_sessions_host_created', table_name='mp_sessions')
    op.drop_table('mp_sessions')
    # ### end Alembic commands ###
