"""billing: subscriptions, payments, referrals, family, user referral_code

Revision ID: 228e107c9731
Revises: 698a9ee2f9bd
Create Date: 2026-07-09 23:47:32.640022

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '228e107c9731'
down_revision: Union[str, None] = '698a9ee2f9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=12), nullable=False),
    sa.Column('plan_code', sa.String(length=24), nullable=False),
    sa.Column('amount_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('provider_txn_id', sa.String(length=64), nullable=True),
    sa.Column('create_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('perform_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('cancel_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('cancel_reason', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_provider_txn', 'payments', ['provider', 'provider_txn_id'], unique=False)
    op.create_index('ix_payments_user', 'payments', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referrer_id', sa.Uuid(), nullable=False),
    sa.Column('referee_id', sa.Uuid(), nullable=False),
    sa.Column('rewarded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referee_id')
    )
    op.create_index('ix_referrals_referrer', 'referrals', ['referrer_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('provider', sa.String(length=12), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_user', 'subscriptions', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index('ix_family_members_member', 'family_members', ['member_id'], unique=False)
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=12), nullable=True))
        batch_op.create_unique_constraint('uq_users_referral_code', ['referral_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('uq_users_referral_code', type_='unique')
        batch_op.drop_column('referral_code')
    op.drop_index('ix_family_members_member', table_name='family_members')
    op.drop_table('family_members')
    op.drop_index('ix_subscriptions_user', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_referrals_referrer', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('ix_payments_user', table_name='payments')
    op.drop_index('ix_payments_provider_txn', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
