"""reading passages

Revision ID: 408213cc8563
Revises: 85be33b86474
Create Date: 2026-07-10 21:53:34.663553

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '408213cc8563'
down_revision: Union[str, None] = '85be33b86474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_passages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('title_en', sa.String(length=160), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('summary_uz', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_reading_passages_cefr_level'), 'reading_passages', ['cefr_level'], unique=False)
    op.create_table('reading_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passage_id', sa.Uuid(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('answer_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_questions_passage_id'), 'reading_questions', ['passage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_questions_passage_id'), table_name='reading_questions')
    op.drop_table('reading_questions')
    op.drop_index(op.f('ix_reading_passages_cefr_level'), table_name='reading_passages')
    op.drop_table('reading_passages')
    # ### end Alembic commands ###
