"""ielts mock sessions legs

Revision ID: 9e1856c1ac3a
Revises: 07f01708e7fc
Create Date: 2026-08-23 10:01:01.752470

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e1856c1ac3a'
down_revision: Union[str, None] = '07f01708e7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ielts_mock_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('current_leg', sa.String(length=12), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('overall_band', sa.Float(), nullable=True),
    sa.Column('band_listening', sa.Float(), nullable=True),
    sa.Column('band_reading', sa.Float(), nullable=True),
    sa.Column('band_writing', sa.Float(), nullable=True),
    sa.Column('band_speaking', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ielts_mock_sessions_user_started', 'ielts_mock_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('ielts_mock_legs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('skill', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('band', sa.Float(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ielts_mock_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'skill', name='uq_mock_leg_session_skill')
    )
    op.create_index('ix_mock_legs_session', 'ielts_mock_legs', ['session_id'], unique=False)
    op.alter_column('coach_sessions', 'mode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.add_column('ielts_results', sa.Column('mock_session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ielts_results_mock_session_id'), 'ielts_results', ['mock_session_id'], unique=False)
    op.create_foreign_key(
        'fk_ielts_results_mock_session_id', 'ielts_results', 'ielts_mock_sessions',
        ['mock_session_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ielts_results_mock_session_id', 'ielts_results', type_='foreignkey')
    op.drop_index(op.f('ix_ielts_results_mock_session_id'), table_name='ielts_results')
    op.drop_column('ielts_results', 'mock_session_id')
    op.alter_column('coach_sessions', 'mode',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index('ix_mock_legs_session', table_name='ielts_mock_legs')
    op.drop_table('ielts_mock_legs')
    op.drop_index('ix_ielts_mock_sessions_user_started', table_name='ielts_mock_sessions')
    op.drop_table('ielts_mock_sessions')
    # ### end Alembic commands ###
