"""expressions table

Revision ID: 9eb452028d68
Revises: 1bcff39443d6
Create Date: 2026-07-18 19:55:49.679948

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9eb452028d68'
down_revision: Union[str, None] = '1bcff39443d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('expression', sa.String(length=200), nullable=False),
    sa.Column('uzbek', sa.Text(), nullable=False),
    sa.Column('cefr', sa.String(length=2), nullable=False),
    sa.Column('ielts_band', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('formality', sa.String(length=10), nullable=False),
    sa.Column('usage', sa.Text(), nullable=False),
    sa.Column('grammar_pattern', sa.Text(), nullable=False),
    sa.Column('native_notes', sa.Text(), nullable=False),
    sa.Column('common_mistakes', sa.JSON(), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=False),
    sa.Column('example_sentences', sa.JSON(), nullable=False),
    sa.Column('collocations', sa.JSON(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('opposites', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_expressions_category_cefr', 'expressions', ['category', 'cefr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expressions_category_cefr', table_name='expressions')
    op.drop_table('expressions')
    # ### end Alembic commands ###
