"""flashcards: decks, cards, review_logs

Revision ID: a438ed7ebc72
Revises: e00cbb24d9dd
Create Date: 2026-07-09 06:08:39.425090

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a438ed7ebc72'
down_revision: Union[str, None] = 'e00cbb24d9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decks_user_id', 'decks', ['user_id'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('state_before', sa.String(length=12), nullable=False),
    sa.Column('interval_before', sa.Float(), nullable=False),
    sa.Column('interval_after', sa.Float(), nullable=False),
    sa.Column('ease_before', sa.Float(), nullable=False),
    sa.Column('ease_after', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_logs_card', 'review_logs', ['card_id'], unique=False)
    op.create_index('ix_review_logs_user_time', 'review_logs', ['user_id', 'reviewed_at'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=True),
    sa.Column('word_id', sa.Uuid(), nullable=True),
    sa.Column('front_text', sa.Text(), nullable=True),
    sa.Column('back_text', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('memory_note', sa.Text(), nullable=True),
    sa.Column('srs_state', sa.String(length=12), nullable=False),
    sa.Column('srs_step', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_cards_user_word')
    )
    op.create_index('ix_cards_user_deck', 'cards', ['user_id', 'deck_id'], unique=False)
    op.create_index('ix_cards_user_due', 'cards', ['user_id', 'due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cards_user_due', table_name='cards')
    op.drop_index('ix_cards_user_deck', table_name='cards')
    op.drop_table('cards')
    op.drop_index('ix_review_logs_user_time', table_name='review_logs')
    op.drop_index('ix_review_logs_card', table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index('ix_decks_user_id', table_name='decks')
    op.drop_table('decks')
    # ### end Alembic commands ###
