"""vocabulary: categories, words, senses, examples, relations

Revision ID: e00cbb24d9dd
Revises: c3f22e799dd8
Create Date: 2026-07-08 23:27:53.782677

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e00cbb24d9dd'
down_revision: Union[str, None] = 'c3f22e799dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('name_uz', sa.String(length=80), nullable=False),
    sa.Column('name_ru', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('words',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('headword', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('pos', sa.String(length=20), nullable=False),
    sa.Column('ipa', sa.String(length=80), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('word_family', sa.String(length=80), nullable=True),
    sa.Column('common_mistake', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_words_headword', 'words', ['headword'], unique=False)
    op.create_index('ix_words_level_status', 'words', ['cefr_level', 'status'], unique=False)
    op.create_table('word_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.Column('related_text', sa.String(length=120), nullable=False),
    sa.Column('related_word_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['related_word_id'], ['words.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'relation_type', 'related_text', name='uq_word_relation')
    )
    op.create_index(op.f('ix_word_relations_word_id'), 'word_relations', ['word_id'], unique=False)
    op.create_table('word_senses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('sense_order', sa.Integer(), nullable=False),
    sa.Column('definition_en', sa.Text(), nullable=False),
    sa.Column('translation_uz', sa.String(length=160), nullable=False),
    sa.Column('translation_ru', sa.String(length=160), nullable=False),
    sa.Column('definition_uz', sa.Text(), nullable=True),
    sa.Column('definition_ru', sa.Text(), nullable=True),
    sa.Column('usage_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_senses_word_id'), 'word_senses', ['word_id'], unique=False)
    op.create_table('word_examples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('example_order', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_uz', sa.Text(), nullable=True),
    sa.Column('text_ru', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['word_senses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_examples_sense_id'), 'word_examples', ['sense_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_examples_sense_id'), table_name='word_examples')
    op.drop_table('word_examples')
    op.drop_index(op.f('ix_word_senses_word_id'), table_name='word_senses')
    op.drop_table('word_senses')
    op.drop_index(op.f('ix_word_relations_word_id'), table_name='word_relations')
    op.drop_table('word_relations')
    op.drop_index('ix_words_level_status', table_name='words')
    op.drop_index('ix_words_headword', table_name='words')
    op.drop_table('words')
    op.drop_table('categories')
    # ### end Alembic commands ###
