import { Ionicons } from "@expo/vector-icons";
import { type Href, router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ALL_LESSONS, localiseLesson, masteryStatus, recordGrammarAttempt, type GrammarExercise, type GrammarLesson } from "@/grammar/catalog";
import { BackButton, Button, Heading, Paper, Screen, Stamp } from "@/components/ui";
import { localeFrom, type Locale } from "@/i18n";
import { useAuth } from "@/providers/auth-provider";
import { submitGrammarAttempt } from "@/grammar/progress-sync";
import { colors, fonts } from "@/theme/tokens";

const labels = {
  uz: { back: "Grammar studio", formula: "Formula", explanation: "Tushuntirish", forms: "Shakllar", compare: "Taqqoslang", examples: "Misollar", mistakes: "Ko‘p uchraydigan xatolar", quiz: "Amaliy mashqlar", check: "Javoblarni tekshirish", passed: "Dars yaxshi o‘zlashtirildi", retryHint: "70% kerak. Izohlarga qayting va yana urinib ko‘ring.", retry: "Qayta urinish", next: "Keyingi dars", previousExercise: "Oldingi", nextExercise: "Keyingi", list: "Katalogga qaytish", correct: "to‘g‘ri", answer: "To‘g‘ri javob", placeholder: "Javobni yozing...", clear: "Tozalash", notFound: "Dars topilmadi", noLesson: "Bu dars katalogda mavjud emas." },
  ru: { back: "Grammar studio", formula: "Формула", explanation: "Объяснение", forms: "Формы", compare: "Сравните", examples: "Примеры", mistakes: "Частые ошибки", quiz: "Практика", check: "Проверить ответы", passed: "Урок хорошо освоен", retryHint: "Нужно 70%. Вернитесь к объяснениям и попробуйте снова.", retry: "Попробовать ещё", next: "Следующий урок", previousExercise: "Назад", nextExercise: "Далее", list: "К каталогу", correct: "правильных", answer: "Правильный ответ", placeholder: "Введите ответ...", clear: "Очистить", notFound: "Урок не найден", noLesson: "Этого урока нет в каталоге." },
  en: { back: "Grammar studio", formula: "Formula", explanation: "Explanation", forms: "Forms", compare: "Compare", examples: "Examples", mistakes: "Common mistakes", quiz: "Practice", check: "Check answers", passed: "Lesson learned well", retryHint: "You need 70%. Revisit the explanation and try again.", retry: "Try again", next: "Next lesson", previousExercise: "Previous", nextExercise: "Next", list: "Back to catalogue", correct: "correct", answer: "Correct answer", placeholder: "Type your answer...", clear: "Clear", notFound: "Lesson not found", noLesson: "This lesson is not in the catalogue." },
} as const;

function normalise(value: string) { return value.trim().toLocaleLowerCase().replace(/[’‘]/g, "'").replace(/[.!?]+$/g, "").replace(/\s+/g, " "); }

export default function GrammarLessonScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const lessonSlug = Array.isArray(slug) ? slug[0] : slug;
  const { user, token } = useAuth();
  const locale = localeFrom(user?.profile.ui_locale);
  const t = labels[locale];
  const base = ALL_LESSONS.find((item) => item.slug === lessonSlug);
  const lesson = useMemo(() => base ? localiseLesson(base, locale) : undefined, [base, locale]);
  if (!lesson) return <Screen appHeader><BackButton label={t.back} onPress={() => router.replace("/grammar" as Href)} /><Heading sub={t.noLesson}>{t.notFound}</Heading><Button onPress={() => router.replace("/grammar" as Href)}>{t.list}</Button></Screen>;
  return <LessonContent key={`${lesson.slug}-${locale}`} lesson={lesson} locale={locale} token={token} userId={user?.id} />;
}

function LessonContent({ lesson, locale, token, userId }: { lesson: GrammarLesson; locale: Locale; token: string | null; userId?: string }) {
  const t = labels[locale];
  const exercises = lesson.exercises ?? [];
  const [answers, setAnswers] = useState<string[]>(() => Array(exercises.length).fill(""));
  const [checked, setChecked] = useState(false);
  const [exerciseStep, setExerciseStep] = useState(0);
  const [saving, setSaving] = useState(false);
  const index = ALL_LESSONS.findIndex((item) => item.slug === lesson.slug);
  const next = ALL_LESSONS[index + 1];
  const correct = exercises.filter((item, questionIndex) => normalise(answers[questionIndex]) === normalise(item.correctAnswer)).length;
  const score = exercises.length ? Math.round((correct / exercises.length) * 100) : 0;
  const passed = checked && score >= 70;
  const check = async () => {
    setChecked(true);
    setSaving(true);
    try {
      await recordGrammarAttempt(lesson.slug, correct, exercises.length);
      if (token && userId) await submitGrammarAttempt(token, userId, lesson.slug, score);
    } catch {
      // Keep the local result. Global sync uploads it when connectivity returns.
    } finally {
      setSaving(false);
    }
  };
  const retry = () => { setChecked(false); setAnswers(Array(exercises.length).fill("")); setExerciseStep(0); };
  return <Screen appHeader>
    <BackButton label={t.back} onPress={() => router.replace("/grammar" as Href)} />
    <Stamp tone="teal">{lesson.level}</Stamp>
    <Heading sub={lesson.titleUz}>{lesson.title}</Heading>
    {lesson.introduction ? <Text style={styles.introduction}>{lesson.introduction}</Text> : null}
    <View style={styles.lessonMeta}><Ionicons name="time-outline" size={16} color={colors.muted} /><Text style={styles.lessonMetaText}>{lesson.estimatedMinutes ?? 15} min · {lesson.category}</Text></View>
    {lesson.formula ? <Paper style={styles.formula}><View style={styles.sectionHead}><Ionicons name="flash-outline" size={18} color={colors.rust} /><Text style={styles.sectionLabel}>{t.formula}</Text></View><Text selectable style={styles.formulaText}>{lesson.formula}</Text></Paper> : null}
    <Section icon="reader-outline" title={t.explanation}>{lesson.explanation.map((paragraph, index) => <Paper key={index} style={styles.paragraph}><Text style={styles.paragraphText}>{paragraph}</Text></Paper>)}</Section>
    {lesson.forms?.length ? <Section icon="grid-outline" title={t.forms}><View style={styles.stack}>{lesson.forms.map((form) => <Paper key={`${form.label}-${form.example}`} style={styles.example}><Text style={styles.formLabel}>{form.label}</Text><Text selectable style={styles.formulaText}>{form.formula}</Text><Text selectable style={styles.exampleEn}>{form.example}</Text></Paper>)}</View></Section> : null}
    <Section icon="chatbubbles-outline" title={t.examples}><View style={styles.stack}>{lesson.examples.map((example, index) => <Paper key={`${example.en}-${index}`} style={styles.example}><Text selectable style={styles.exampleEn}>{example.en}</Text>{example.uz ? <Text style={styles.exampleTranslation}>{example.uz}</Text> : null}</Paper>)}</View></Section>
    {lesson.comparisons?.length ? <Section icon="git-compare-outline" title={t.compare}><View style={styles.stack}>{lesson.comparisons.map((comparison) => <Paper key={comparison.title} style={styles.example}><Text style={styles.comparisonTitle}>{comparison.title}</Text><Text selectable style={styles.right}>{comparison.left}</Text><Text selectable style={styles.wrong}>{comparison.right}</Text><Text style={styles.mistakeNote}>{comparison.explanation}</Text></Paper>)}</View></Section> : null}
    <Section icon="alert-circle-outline" title={t.mistakes}><View style={styles.stack}>{lesson.mistakes.map((mistake, index) => <Paper key={`${mistake.wrong}-${index}`} style={styles.mistake}><View style={styles.mistakeLine}><Ionicons name="close-circle" size={17} color={colors.danger} /><Text selectable style={styles.wrong}>{mistake.wrong}</Text></View><View style={styles.mistakeLine}><Ionicons name="checkmark-circle" size={17} color={colors.teal} /><Text selectable style={styles.right}>{mistake.right}</Text></View><Text style={styles.mistakeNote}>{mistake.note}</Text></Paper>)}</View></Section>
    <Section icon="help-circle-outline" title={t.quiz}><View style={styles.stack}><ExerciseItem key={exercises[exerciseStep].id} number={exerciseStep + 1} total={exercises.length} exercise={exercises[exerciseStep]} answer={answers[exerciseStep]} checked={checked} labels={t} onChange={(answer) => setAnswers((current) => current.map((value, answerIndex) => answerIndex === exerciseStep ? answer : value))} /><View style={styles.exerciseNavigation}><Pressable accessibilityRole="button" disabled={exerciseStep === 0} onPress={() => setExerciseStep((current) => Math.max(0, current - 1))} style={({ pressed }) => [styles.exerciseNavButton, exerciseStep === 0 && styles.exerciseNavDisabled, pressed && exerciseStep > 0 && styles.pressed]}><Ionicons name="arrow-back" size={17} color={colors.ink} /><Text style={styles.exerciseNavText}>{t.previousExercise}</Text></Pressable><Pressable accessibilityRole="button" disabled={exerciseStep >= exercises.length - 1 || !answers[exerciseStep]?.trim()} onPress={() => setExerciseStep((current) => Math.min(exercises.length - 1, current + 1))} style={({ pressed }) => [styles.exerciseNavButton, styles.exerciseNavPrimary, (exerciseStep >= exercises.length - 1 || !answers[exerciseStep]?.trim()) && styles.exerciseNavDisabled, pressed && exerciseStep < exercises.length - 1 && Boolean(answers[exerciseStep]?.trim()) && styles.pressed]}><Text style={styles.exerciseNavPrimaryText}>{t.nextExercise}</Text><Ionicons name="arrow-forward" size={17} color={colors.onAccent} /></Pressable></View></View></Section>
    {!checked ? <Button loading={saving} disabled={answers.some((answer) => !answer.trim())} onPress={() => void check()}>{t.check}</Button> : <Paper style={styles.result}><Ionicons name={passed ? "ribbon-outline" : "refresh-circle-outline"} size={35} color={passed ? colors.teal : colors.rust} /><Text style={styles.resultScore}>{score}%</Text><Text style={styles.resultStatus}>{masteryStatus(score).replaceAll("-", " ")}</Text><Text style={styles.resultBody}>{correct}/{exercises.length} {t.correct}. {passed ? t.passed : t.retryHint}</Text>{passed && next ? <Button icon="arrow-forward" onPress={() => router.replace(`/grammar/${next.slug}` as Href)}>{`${t.next}: ${next.title}`}</Button> : null}{!passed ? <Button variant="secondary" icon="refresh" onPress={retry}>{t.retry}</Button> : <Button variant="secondary" onPress={() => router.replace("/grammar" as Href)}>{t.list}</Button>}</Paper>}
  </Screen>;
}

function Section({ icon, title, children }: { icon: keyof typeof Ionicons.glyphMap; title: string; children: React.ReactNode }) { return <View style={styles.section}><View style={styles.sectionHead}><Ionicons name={icon} size={19} color={colors.rust} /><Text style={styles.sectionTitle}>{title}</Text></View>{children}</View>; }
function ExerciseItem({ number, total, exercise, answer, checked, labels: t, onChange }: { number: number; total: number; exercise: GrammarExercise; answer: string; checked: boolean; labels: (typeof labels)[Locale]; onChange: (value: string) => void }) { const correct = normalise(answer) === normalise(exercise.correctAnswer); return <Paper style={[styles.quiz, checked && correct && styles.quizCorrect, checked && !correct && styles.quizWrong]}><View style={styles.quizTop}><Text style={styles.questionNumber}>{number}</Text><View style={styles.questionCopy}><Text style={styles.exerciseType}>{exercise.type.replaceAll("-", " ")} · {number}/{total}</Text>{exercise.context ? <Text style={styles.exerciseContext}>{exercise.context}</Text> : null}<Text style={styles.quizQuestion}>{exercise.prompt}</Text></View></View>{exercise.options?.length ? <View style={styles.options}>{exercise.options.map((option, optionIndex) => { const selected = answer === option; const isCorrect = checked && normalise(option) === normalise(exercise.correctAnswer); return <Pressable key={`${option}-${optionIndex}`} accessibilityRole="radio" accessibilityState={{ selected, disabled: checked }} disabled={checked} onPress={() => onChange(option)} style={({ pressed }) => [styles.option, selected && styles.optionSelected, isCorrect && styles.optionCorrect, checked && selected && !isCorrect && styles.optionIncorrect, pressed && !checked && styles.pressed]}><Text style={styles.optionText}>{option}</Text>{checked && (isCorrect || selected) ? <Ionicons name={isCorrect ? "checkmark-circle" : "close-circle"} size={18} color={isCorrect ? colors.teal : colors.danger} /> : null}</Pressable>; })}</View> : exercise.type === "sentence-builder" && exercise.words?.length ? <View style={styles.builder}><View style={styles.builderAnswer}><Text style={styles.optionText}>{answer || t.placeholder}</Text></View><View style={styles.wordBank}>{exercise.words.map((word, index) => <Pressable key={`${word}-${index}`} disabled={checked} onPress={() => onChange(`${answer}${answer ? " " : ""}${word}`)} style={styles.word}><Text style={styles.optionText}>{word}</Text></Pressable>)}<Pressable disabled={checked} onPress={() => onChange("")} style={styles.clear}><Text style={styles.clearText}>{t.clear}</Text></Pressable></View></View> : <TextInput value={answer} editable={!checked} onChangeText={onChange} placeholder={t.placeholder} placeholderTextColor={colors.muted} autoCorrect={false} style={styles.answerInput} />}{checked ? <View style={[styles.feedback, correct ? styles.feedbackCorrect : styles.feedbackWrong]}><Text style={styles.feedbackAnswer}>{t.answer}: {exercise.correctAnswer}</Text><Text style={styles.feedbackText}>{exercise.explanation}</Text></View> : null}</Paper>; }

const styles = StyleSheet.create({
  introduction: { fontFamily: fonts.ui, fontSize: 16, lineHeight: 26, color: colors.ink }, lessonMeta: { flexDirection: "row", alignItems: "center", gap: 6 }, lessonMetaText: { flex: 1, fontFamily: fonts.uiMedium, fontSize: 12, color: colors.muted }, formula: { gap: 9, backgroundColor: colors.brand100 }, section: { gap: 10 }, sectionHead: { flexDirection: "row", alignItems: "center", gap: 7 }, sectionLabel: { fontFamily: fonts.uiBold, fontSize: 12, letterSpacing: .7, textTransform: "uppercase", color: colors.rustDark }, sectionTitle: { flex: 1, fontFamily: fonts.uiBold, fontSize: 18, color: colors.ink }, formulaText: { fontFamily: fonts.uiBold, fontSize: 16, lineHeight: 25, color: colors.rustDark }, formLabel: { fontFamily: fonts.uiBold, fontSize: 11, textTransform: "uppercase", letterSpacing: .7, color: colors.rust },
  paragraph: { padding: 14, backgroundColor: colors.raised }, paragraphText: { fontFamily: fonts.ui, fontSize: 15, lineHeight: 25, color: colors.ink }, stack: { gap: 9 }, example: { gap: 5, padding: 13 }, exampleEn: { fontFamily: fonts.uiBold, fontSize: 14, lineHeight: 21, color: colors.ink }, exampleTranslation: { fontFamily: fonts.ui, fontSize: 13, lineHeight: 20, color: colors.muted },
  mistake: { gap: 7, padding: 13 }, mistakeLine: { flexDirection: "row", alignItems: "flex-start", gap: 7 }, wrong: { flex: 1, fontFamily: fonts.uiMedium, fontSize: 13, lineHeight: 19, color: colors.danger, textDecorationLine: "line-through" }, right: { flex: 1, fontFamily: fonts.uiBold, fontSize: 13, lineHeight: 19, color: colors.teal }, comparisonTitle: { fontFamily: fonts.uiBold, fontSize: 14, lineHeight: 21, color: colors.ink }, mistakeNote: { marginTop: 1, fontFamily: fonts.ui, fontSize: 12, lineHeight: 19, color: colors.muted },
  quiz: { gap: 12 }, quizCorrect: { borderColor: "rgba(70,120,120,.46)", backgroundColor: "rgba(70,120,120,.06)" }, quizWrong: { borderColor: "rgba(220,38,38,.36)", backgroundColor: "rgba(220,38,38,.05)" }, quizTop: { flexDirection: "row", alignItems: "flex-start", gap: 8 }, questionNumber: { width: 27, height: 27, overflow: "hidden", borderRadius: 14, textAlign: "center", fontFamily: fonts.uiBold, fontSize: 11, lineHeight: 27, color: colors.onAccent, backgroundColor: colors.brand600 }, questionCopy: { flex: 1, minWidth: 0, gap: 5 }, exerciseType: { fontFamily: fonts.uiBold, fontSize: 10, letterSpacing: .6, textTransform: "uppercase", color: colors.rust }, exerciseContext: { fontFamily: fonts.ui, fontSize: 13, lineHeight: 20, color: colors.muted }, quizQuestion: { fontFamily: fonts.uiBold, fontSize: 15, lineHeight: 23, color: colors.ink }, options: { gap: 7 }, option: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 9, backgroundColor: colors.raised }, optionSelected: { borderColor: colors.brand600, backgroundColor: "rgba(185,78,40,.10)" }, optionCorrect: { borderColor: colors.teal, backgroundColor: "rgba(70,120,120,.12)" }, optionIncorrect: { borderColor: colors.danger, backgroundColor: "rgba(220,38,38,.09)" }, optionText: { flex: 1, fontFamily: fonts.uiMedium, fontSize: 14, lineHeight: 20, color: colors.ink }, answerInput: { minHeight: 50, borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 12, fontFamily: fonts.ui, fontSize: 16, color: colors.ink, backgroundColor: colors.raised }, builder: { gap: 9 }, builderAnswer: { minHeight: 50, justifyContent: "center", borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 12, backgroundColor: colors.raised }, wordBank: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, word: { minHeight: 48, justifyContent: "center", borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 11, backgroundColor: colors.raised }, clear: { minHeight: 48, justifyContent: "center", paddingHorizontal: 11 }, clearText: { fontFamily: fonts.uiBold, fontSize: 13, color: colors.danger }, feedback: { gap: 4, borderWidth: 1, borderRadius: 10, padding: 11 }, feedbackCorrect: { borderColor: "rgba(70,120,120,.35)", backgroundColor: "rgba(70,120,120,.08)" }, feedbackWrong: { borderColor: "rgba(220,38,38,.3)", backgroundColor: "rgba(220,38,38,.06)" }, feedbackAnswer: { fontFamily: fonts.uiBold, fontSize: 13, lineHeight: 20, color: colors.ink }, feedbackText: { fontFamily: fonts.ui, fontSize: 12, lineHeight: 19, color: colors.muted },
  result: { alignItems: "center", gap: 8, paddingVertical: 25 }, resultScore: { fontFamily: fonts.display, fontSize: 47, lineHeight: 52, color: colors.ink }, resultStatus: { fontFamily: fonts.uiBold, fontSize: 13, textTransform: "capitalize", color: colors.teal }, resultBody: { fontFamily: fonts.uiMedium, fontSize: 13, lineHeight: 20, textAlign: "center", color: colors.muted }, pressed: { opacity: .72, transform: [{ translateY: 1 }] },
  exerciseNavigation: { flexDirection: "row", gap: 9 }, exerciseNavButton: { minHeight: 48, flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 10, backgroundColor: colors.raised }, exerciseNavPrimary: { borderColor: colors.brand600, backgroundColor: colors.brand600 }, exerciseNavDisabled: { opacity: .38 }, exerciseNavText: { fontFamily: fonts.uiBold, fontSize: 13, color: colors.ink }, exerciseNavPrimaryText: { fontFamily: fonts.uiBold, fontSize: 13, color: colors.onAccent },
});
